/*
Pricing API

Testing RecommendationsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package pricing_api_client

import (
	"context"
	openapiclient "github.com/baselinehq/pricingapi-client-golang"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_pricing_api_client_RecommendationsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test RecommendationsAPIService V1RecommendationsComputePost", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.RecommendationsAPI.V1RecommendationsComputePost(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RecommendationsAPIService V1RecommendationsDisksPost", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.RecommendationsAPI.V1RecommendationsDisksPost(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
