/*
Pricing API

Provides API level access to the Costgraph Services.

API version: 1.0
Contact: contact@baselinehq.cloud
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pricing_api_client

import (
	"encoding/json"
)

// checks if the TypesDisk type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TypesDisk{}

// TypesDisk struct for TypesDisk
type TypesDisk struct {
	AvailabilityZone *string `json:"availability_zone,omitempty"`
	CapacityGb *float32 `json:"capacity_gb,omitempty"`
	Id *string `json:"id,omitempty"`
	Iops *float32 `json:"iops,omitempty"`
	Provider *GithubComBaselinehqGolangSharedTypesProvider `json:"provider,omitempty"`
	Region *string `json:"region,omitempty"`
	Service *GithubComBaselinehqGolangSharedTypesService `json:"service,omitempty"`
	ThroughputMbps *float32 `json:"throughput_mbps,omitempty"`
	Type *string `json:"type,omitempty"`
	UsageType *GithubComBaselinehqGolangSharedTypesUsageType `json:"usage_type,omitempty"`
}

// NewTypesDisk instantiates a new TypesDisk object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTypesDisk() *TypesDisk {
	this := TypesDisk{}
	return &this
}

// NewTypesDiskWithDefaults instantiates a new TypesDisk object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTypesDiskWithDefaults() *TypesDisk {
	this := TypesDisk{}
	return &this
}

// GetAvailabilityZone returns the AvailabilityZone field value if set, zero value otherwise.
func (o *TypesDisk) GetAvailabilityZone() string {
	if o == nil || IsNil(o.AvailabilityZone) {
		var ret string
		return ret
	}
	return *o.AvailabilityZone
}

// GetAvailabilityZoneOk returns a tuple with the AvailabilityZone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TypesDisk) GetAvailabilityZoneOk() (*string, bool) {
	if o == nil || IsNil(o.AvailabilityZone) {
		return nil, false
	}
	return o.AvailabilityZone, true
}

// HasAvailabilityZone returns a boolean if a field has been set.
func (o *TypesDisk) HasAvailabilityZone() bool {
	if o != nil && !IsNil(o.AvailabilityZone) {
		return true
	}

	return false
}

// SetAvailabilityZone gets a reference to the given string and assigns it to the AvailabilityZone field.
func (o *TypesDisk) SetAvailabilityZone(v string) {
	o.AvailabilityZone = &v
}

// GetCapacityGb returns the CapacityGb field value if set, zero value otherwise.
func (o *TypesDisk) GetCapacityGb() float32 {
	if o == nil || IsNil(o.CapacityGb) {
		var ret float32
		return ret
	}
	return *o.CapacityGb
}

// GetCapacityGbOk returns a tuple with the CapacityGb field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TypesDisk) GetCapacityGbOk() (*float32, bool) {
	if o == nil || IsNil(o.CapacityGb) {
		return nil, false
	}
	return o.CapacityGb, true
}

// HasCapacityGb returns a boolean if a field has been set.
func (o *TypesDisk) HasCapacityGb() bool {
	if o != nil && !IsNil(o.CapacityGb) {
		return true
	}

	return false
}

// SetCapacityGb gets a reference to the given float32 and assigns it to the CapacityGb field.
func (o *TypesDisk) SetCapacityGb(v float32) {
	o.CapacityGb = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *TypesDisk) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TypesDisk) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *TypesDisk) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *TypesDisk) SetId(v string) {
	o.Id = &v
}

// GetIops returns the Iops field value if set, zero value otherwise.
func (o *TypesDisk) GetIops() float32 {
	if o == nil || IsNil(o.Iops) {
		var ret float32
		return ret
	}
	return *o.Iops
}

// GetIopsOk returns a tuple with the Iops field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TypesDisk) GetIopsOk() (*float32, bool) {
	if o == nil || IsNil(o.Iops) {
		return nil, false
	}
	return o.Iops, true
}

// HasIops returns a boolean if a field has been set.
func (o *TypesDisk) HasIops() bool {
	if o != nil && !IsNil(o.Iops) {
		return true
	}

	return false
}

// SetIops gets a reference to the given float32 and assigns it to the Iops field.
func (o *TypesDisk) SetIops(v float32) {
	o.Iops = &v
}

// GetProvider returns the Provider field value if set, zero value otherwise.
func (o *TypesDisk) GetProvider() GithubComBaselinehqGolangSharedTypesProvider {
	if o == nil || IsNil(o.Provider) {
		var ret GithubComBaselinehqGolangSharedTypesProvider
		return ret
	}
	return *o.Provider
}

// GetProviderOk returns a tuple with the Provider field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TypesDisk) GetProviderOk() (*GithubComBaselinehqGolangSharedTypesProvider, bool) {
	if o == nil || IsNil(o.Provider) {
		return nil, false
	}
	return o.Provider, true
}

// HasProvider returns a boolean if a field has been set.
func (o *TypesDisk) HasProvider() bool {
	if o != nil && !IsNil(o.Provider) {
		return true
	}

	return false
}

// SetProvider gets a reference to the given GithubComBaselinehqGolangSharedTypesProvider and assigns it to the Provider field.
func (o *TypesDisk) SetProvider(v GithubComBaselinehqGolangSharedTypesProvider) {
	o.Provider = &v
}

// GetRegion returns the Region field value if set, zero value otherwise.
func (o *TypesDisk) GetRegion() string {
	if o == nil || IsNil(o.Region) {
		var ret string
		return ret
	}
	return *o.Region
}

// GetRegionOk returns a tuple with the Region field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TypesDisk) GetRegionOk() (*string, bool) {
	if o == nil || IsNil(o.Region) {
		return nil, false
	}
	return o.Region, true
}

// HasRegion returns a boolean if a field has been set.
func (o *TypesDisk) HasRegion() bool {
	if o != nil && !IsNil(o.Region) {
		return true
	}

	return false
}

// SetRegion gets a reference to the given string and assigns it to the Region field.
func (o *TypesDisk) SetRegion(v string) {
	o.Region = &v
}

// GetService returns the Service field value if set, zero value otherwise.
func (o *TypesDisk) GetService() GithubComBaselinehqGolangSharedTypesService {
	if o == nil || IsNil(o.Service) {
		var ret GithubComBaselinehqGolangSharedTypesService
		return ret
	}
	return *o.Service
}

// GetServiceOk returns a tuple with the Service field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TypesDisk) GetServiceOk() (*GithubComBaselinehqGolangSharedTypesService, bool) {
	if o == nil || IsNil(o.Service) {
		return nil, false
	}
	return o.Service, true
}

// HasService returns a boolean if a field has been set.
func (o *TypesDisk) HasService() bool {
	if o != nil && !IsNil(o.Service) {
		return true
	}

	return false
}

// SetService gets a reference to the given GithubComBaselinehqGolangSharedTypesService and assigns it to the Service field.
func (o *TypesDisk) SetService(v GithubComBaselinehqGolangSharedTypesService) {
	o.Service = &v
}

// GetThroughputMbps returns the ThroughputMbps field value if set, zero value otherwise.
func (o *TypesDisk) GetThroughputMbps() float32 {
	if o == nil || IsNil(o.ThroughputMbps) {
		var ret float32
		return ret
	}
	return *o.ThroughputMbps
}

// GetThroughputMbpsOk returns a tuple with the ThroughputMbps field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TypesDisk) GetThroughputMbpsOk() (*float32, bool) {
	if o == nil || IsNil(o.ThroughputMbps) {
		return nil, false
	}
	return o.ThroughputMbps, true
}

// HasThroughputMbps returns a boolean if a field has been set.
func (o *TypesDisk) HasThroughputMbps() bool {
	if o != nil && !IsNil(o.ThroughputMbps) {
		return true
	}

	return false
}

// SetThroughputMbps gets a reference to the given float32 and assigns it to the ThroughputMbps field.
func (o *TypesDisk) SetThroughputMbps(v float32) {
	o.ThroughputMbps = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *TypesDisk) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TypesDisk) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *TypesDisk) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *TypesDisk) SetType(v string) {
	o.Type = &v
}

// GetUsageType returns the UsageType field value if set, zero value otherwise.
func (o *TypesDisk) GetUsageType() GithubComBaselinehqGolangSharedTypesUsageType {
	if o == nil || IsNil(o.UsageType) {
		var ret GithubComBaselinehqGolangSharedTypesUsageType
		return ret
	}
	return *o.UsageType
}

// GetUsageTypeOk returns a tuple with the UsageType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TypesDisk) GetUsageTypeOk() (*GithubComBaselinehqGolangSharedTypesUsageType, bool) {
	if o == nil || IsNil(o.UsageType) {
		return nil, false
	}
	return o.UsageType, true
}

// HasUsageType returns a boolean if a field has been set.
func (o *TypesDisk) HasUsageType() bool {
	if o != nil && !IsNil(o.UsageType) {
		return true
	}

	return false
}

// SetUsageType gets a reference to the given GithubComBaselinehqGolangSharedTypesUsageType and assigns it to the UsageType field.
func (o *TypesDisk) SetUsageType(v GithubComBaselinehqGolangSharedTypesUsageType) {
	o.UsageType = &v
}

func (o TypesDisk) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TypesDisk) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AvailabilityZone) {
		toSerialize["availability_zone"] = o.AvailabilityZone
	}
	if !IsNil(o.CapacityGb) {
		toSerialize["capacity_gb"] = o.CapacityGb
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Iops) {
		toSerialize["iops"] = o.Iops
	}
	if !IsNil(o.Provider) {
		toSerialize["provider"] = o.Provider
	}
	if !IsNil(o.Region) {
		toSerialize["region"] = o.Region
	}
	if !IsNil(o.Service) {
		toSerialize["service"] = o.Service
	}
	if !IsNil(o.ThroughputMbps) {
		toSerialize["throughput_mbps"] = o.ThroughputMbps
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.UsageType) {
		toSerialize["usage_type"] = o.UsageType
	}
	return toSerialize, nil
}

type NullableTypesDisk struct {
	value *TypesDisk
	isSet bool
}

func (v NullableTypesDisk) Get() *TypesDisk {
	return v.value
}

func (v *NullableTypesDisk) Set(val *TypesDisk) {
	v.value = val
	v.isSet = true
}

func (v NullableTypesDisk) IsSet() bool {
	return v.isSet
}

func (v *NullableTypesDisk) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTypesDisk(val *TypesDisk) *NullableTypesDisk {
	return &NullableTypesDisk{value: val, isSet: true}
}

func (v NullableTypesDisk) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTypesDisk) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


