/*
Pricing API

Provides API level access to the Costgraph Services.

API version: 1.0
Contact: support@costgraph.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pricing_api_client

import (
	"encoding/json"
)

// checks if the ModelPricePage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelPricePage{}

// ModelPricePage struct for ModelPricePage
type ModelPricePage struct {
	Data []ModelPrice `json:"data,omitempty"`
	Page *Page        `json:"page,omitempty"`
}

// NewModelPricePage instantiates a new ModelPricePage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelPricePage() *ModelPricePage {
	this := ModelPricePage{}
	return &this
}

// NewModelPricePageWithDefaults instantiates a new ModelPricePage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelPricePageWithDefaults() *ModelPricePage {
	this := ModelPricePage{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *ModelPricePage) GetData() []ModelPrice {
	if o == nil || IsNil(o.Data) {
		var ret []ModelPrice
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelPricePage) GetDataOk() ([]ModelPrice, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ModelPricePage) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []ModelPrice and assigns it to the Data field.
func (o *ModelPricePage) SetData(v []ModelPrice) {
	o.Data = v
}

// GetPage returns the Page field value if set, zero value otherwise.
func (o *ModelPricePage) GetPage() Page {
	if o == nil || IsNil(o.Page) {
		var ret Page
		return ret
	}
	return *o.Page
}

// GetPageOk returns a tuple with the Page field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelPricePage) GetPageOk() (*Page, bool) {
	if o == nil || IsNil(o.Page) {
		return nil, false
	}
	return o.Page, true
}

// HasPage returns a boolean if a field has been set.
func (o *ModelPricePage) HasPage() bool {
	if o != nil && !IsNil(o.Page) {
		return true
	}

	return false
}

// SetPage gets a reference to the given Page and assigns it to the Page field.
func (o *ModelPricePage) SetPage(v Page) {
	o.Page = &v
}

func (o ModelPricePage) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelPricePage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Page) {
		toSerialize["page"] = o.Page
	}
	return toSerialize, nil
}

type NullableModelPricePage struct {
	value *ModelPricePage
	isSet bool
}

func (v NullableModelPricePage) Get() *ModelPricePage {
	return v.value
}

func (v *NullableModelPricePage) Set(val *ModelPricePage) {
	v.value = val
	v.isSet = true
}

func (v NullableModelPricePage) IsSet() bool {
	return v.isSet
}

func (v *NullableModelPricePage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelPricePage(val *ModelPricePage) *NullableModelPricePage {
	return &NullableModelPricePage{value: val, isSet: true}
}

func (v NullableModelPricePage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelPricePage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
