/*
Pricing API

Provides API level access to the Costgraph Services.

API version: 1.0
Contact: support@costgraph.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pricing_api_client

import (
	"encoding/json"
)

// checks if the DatabasePrice type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DatabasePrice{}

// DatabasePrice struct for DatabasePrice
type DatabasePrice struct {
	Architecture               *string                `json:"architecture,omitempty"`
	AvailabilityZone           *string                `json:"availability_zone,omitempty"`
	BillingConfig              *string                `json:"billing_config,omitempty"`
	CapacityUnit               *string                `json:"capacity_unit,omitempty"`
	CostPerCapacityUnit        *float32               `json:"cost_per_capacity_unit,omitempty"`
	CostPerHour                *float32               `json:"cost_per_hour,omitempty"`
	CostPerIoRequest           *float32               `json:"cost_per_io_request,omitempty"`
	CostPerIopsHour            *float32               `json:"cost_per_iops_hour,omitempty"`
	CostPerStorageGbHour       *float32               `json:"cost_per_storage_gb_hour,omitempty"`
	CostPerThroughputMbpsHour  *float32               `json:"cost_per_throughput_mbps_hour,omitempty"`
	CostPerVcpuLicenseHour     *float32               `json:"cost_per_vcpu_license_hour,omitempty"`
	CpuCores                   *float32               `json:"cpu_cores,omitempty"`
	CpuCoresCostPerHour        *float32               `json:"cpu_cores_cost_per_hour,omitempty"`
	CreatedAt                  *string                `json:"created_at,omitempty"`
	Currency                   *string                `json:"currency,omitempty"`
	DeploymentOption           *string                `json:"deployment_option,omitempty"`
	Edition                    *string                `json:"edition,omitempty"`
	Engine                     *string                `json:"engine,omitempty"`
	Id                         *string                `json:"id,omitempty"`
	InstanceType               *string                `json:"instance_type,omitempty"`
	MaxIops                    *float32               `json:"max_iops,omitempty"`
	MaxStorageGb               *float32               `json:"max_storage_gb,omitempty"`
	MaxThroughputMbps          *float32               `json:"max_throughput_mbps,omitempty"`
	MinIops                    *float32               `json:"min_iops,omitempty"`
	MinStorageGb               *float32               `json:"min_storage_gb,omitempty"`
	MinThroughputMbps          *float32               `json:"min_throughput_mbps,omitempty"`
	NativeCostPerHour          *float32               `json:"native_cost_per_hour,omitempty"`
	NativeCostPerStorageGbHour *float32               `json:"native_cost_per_storage_gb_hour,omitempty"`
	PeriodBillingHours         *float32               `json:"period_billing_hours,omitempty"`
	Provider                   *string                `json:"provider,omitempty"`
	RamGb                      *float32               `json:"ram_gb,omitempty"`
	RamGbCostPerHour           *float32               `json:"ram_gb_cost_per_hour,omitempty"`
	RawPricingData             map[string]interface{} `json:"raw_pricing_data,omitempty"`
	Region                     *string                `json:"region,omitempty"`
	Service                    *string                `json:"service,omitempty"`
	StorageType                *string                `json:"storage_type,omitempty"`
	Tags                       map[string]interface{} `json:"tags,omitempty"`
	UpdatedAt                  *string                `json:"updated_at,omitempty"`
	UsageType                  *string                `json:"usage_type,omitempty"`
}

// NewDatabasePrice instantiates a new DatabasePrice object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDatabasePrice() *DatabasePrice {
	this := DatabasePrice{}
	return &this
}

// NewDatabasePriceWithDefaults instantiates a new DatabasePrice object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDatabasePriceWithDefaults() *DatabasePrice {
	this := DatabasePrice{}
	return &this
}

// GetArchitecture returns the Architecture field value if set, zero value otherwise.
func (o *DatabasePrice) GetArchitecture() string {
	if o == nil || IsNil(o.Architecture) {
		var ret string
		return ret
	}
	return *o.Architecture
}

// GetArchitectureOk returns a tuple with the Architecture field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DatabasePrice) GetArchitectureOk() (*string, bool) {
	if o == nil || IsNil(o.Architecture) {
		return nil, false
	}
	return o.Architecture, true
}

// HasArchitecture returns a boolean if a field has been set.
func (o *DatabasePrice) HasArchitecture() bool {
	if o != nil && !IsNil(o.Architecture) {
		return true
	}

	return false
}

// SetArchitecture gets a reference to the given string and assigns it to the Architecture field.
func (o *DatabasePrice) SetArchitecture(v string) {
	o.Architecture = &v
}

// GetAvailabilityZone returns the AvailabilityZone field value if set, zero value otherwise.
func (o *DatabasePrice) GetAvailabilityZone() string {
	if o == nil || IsNil(o.AvailabilityZone) {
		var ret string
		return ret
	}
	return *o.AvailabilityZone
}

// GetAvailabilityZoneOk returns a tuple with the AvailabilityZone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DatabasePrice) GetAvailabilityZoneOk() (*string, bool) {
	if o == nil || IsNil(o.AvailabilityZone) {
		return nil, false
	}
	return o.AvailabilityZone, true
}

// HasAvailabilityZone returns a boolean if a field has been set.
func (o *DatabasePrice) HasAvailabilityZone() bool {
	if o != nil && !IsNil(o.AvailabilityZone) {
		return true
	}

	return false
}

// SetAvailabilityZone gets a reference to the given string and assigns it to the AvailabilityZone field.
func (o *DatabasePrice) SetAvailabilityZone(v string) {
	o.AvailabilityZone = &v
}

// GetBillingConfig returns the BillingConfig field value if set, zero value otherwise.
func (o *DatabasePrice) GetBillingConfig() string {
	if o == nil || IsNil(o.BillingConfig) {
		var ret string
		return ret
	}
	return *o.BillingConfig
}

// GetBillingConfigOk returns a tuple with the BillingConfig field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DatabasePrice) GetBillingConfigOk() (*string, bool) {
	if o == nil || IsNil(o.BillingConfig) {
		return nil, false
	}
	return o.BillingConfig, true
}

// HasBillingConfig returns a boolean if a field has been set.
func (o *DatabasePrice) HasBillingConfig() bool {
	if o != nil && !IsNil(o.BillingConfig) {
		return true
	}

	return false
}

// SetBillingConfig gets a reference to the given string and assigns it to the BillingConfig field.
func (o *DatabasePrice) SetBillingConfig(v string) {
	o.BillingConfig = &v
}

// GetCapacityUnit returns the CapacityUnit field value if set, zero value otherwise.
func (o *DatabasePrice) GetCapacityUnit() string {
	if o == nil || IsNil(o.CapacityUnit) {
		var ret string
		return ret
	}
	return *o.CapacityUnit
}

// GetCapacityUnitOk returns a tuple with the CapacityUnit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DatabasePrice) GetCapacityUnitOk() (*string, bool) {
	if o == nil || IsNil(o.CapacityUnit) {
		return nil, false
	}
	return o.CapacityUnit, true
}

// HasCapacityUnit returns a boolean if a field has been set.
func (o *DatabasePrice) HasCapacityUnit() bool {
	if o != nil && !IsNil(o.CapacityUnit) {
		return true
	}

	return false
}

// SetCapacityUnit gets a reference to the given string and assigns it to the CapacityUnit field.
func (o *DatabasePrice) SetCapacityUnit(v string) {
	o.CapacityUnit = &v
}

// GetCostPerCapacityUnit returns the CostPerCapacityUnit field value if set, zero value otherwise.
func (o *DatabasePrice) GetCostPerCapacityUnit() float32 {
	if o == nil || IsNil(o.CostPerCapacityUnit) {
		var ret float32
		return ret
	}
	return *o.CostPerCapacityUnit
}

// GetCostPerCapacityUnitOk returns a tuple with the CostPerCapacityUnit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DatabasePrice) GetCostPerCapacityUnitOk() (*float32, bool) {
	if o == nil || IsNil(o.CostPerCapacityUnit) {
		return nil, false
	}
	return o.CostPerCapacityUnit, true
}

// HasCostPerCapacityUnit returns a boolean if a field has been set.
func (o *DatabasePrice) HasCostPerCapacityUnit() bool {
	if o != nil && !IsNil(o.CostPerCapacityUnit) {
		return true
	}

	return false
}

// SetCostPerCapacityUnit gets a reference to the given float32 and assigns it to the CostPerCapacityUnit field.
func (o *DatabasePrice) SetCostPerCapacityUnit(v float32) {
	o.CostPerCapacityUnit = &v
}

// GetCostPerHour returns the CostPerHour field value if set, zero value otherwise.
func (o *DatabasePrice) GetCostPerHour() float32 {
	if o == nil || IsNil(o.CostPerHour) {
		var ret float32
		return ret
	}
	return *o.CostPerHour
}

// GetCostPerHourOk returns a tuple with the CostPerHour field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DatabasePrice) GetCostPerHourOk() (*float32, bool) {
	if o == nil || IsNil(o.CostPerHour) {
		return nil, false
	}
	return o.CostPerHour, true
}

// HasCostPerHour returns a boolean if a field has been set.
func (o *DatabasePrice) HasCostPerHour() bool {
	if o != nil && !IsNil(o.CostPerHour) {
		return true
	}

	return false
}

// SetCostPerHour gets a reference to the given float32 and assigns it to the CostPerHour field.
func (o *DatabasePrice) SetCostPerHour(v float32) {
	o.CostPerHour = &v
}

// GetCostPerIoRequest returns the CostPerIoRequest field value if set, zero value otherwise.
func (o *DatabasePrice) GetCostPerIoRequest() float32 {
	if o == nil || IsNil(o.CostPerIoRequest) {
		var ret float32
		return ret
	}
	return *o.CostPerIoRequest
}

// GetCostPerIoRequestOk returns a tuple with the CostPerIoRequest field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DatabasePrice) GetCostPerIoRequestOk() (*float32, bool) {
	if o == nil || IsNil(o.CostPerIoRequest) {
		return nil, false
	}
	return o.CostPerIoRequest, true
}

// HasCostPerIoRequest returns a boolean if a field has been set.
func (o *DatabasePrice) HasCostPerIoRequest() bool {
	if o != nil && !IsNil(o.CostPerIoRequest) {
		return true
	}

	return false
}

// SetCostPerIoRequest gets a reference to the given float32 and assigns it to the CostPerIoRequest field.
func (o *DatabasePrice) SetCostPerIoRequest(v float32) {
	o.CostPerIoRequest = &v
}

// GetCostPerIopsHour returns the CostPerIopsHour field value if set, zero value otherwise.
func (o *DatabasePrice) GetCostPerIopsHour() float32 {
	if o == nil || IsNil(o.CostPerIopsHour) {
		var ret float32
		return ret
	}
	return *o.CostPerIopsHour
}

// GetCostPerIopsHourOk returns a tuple with the CostPerIopsHour field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DatabasePrice) GetCostPerIopsHourOk() (*float32, bool) {
	if o == nil || IsNil(o.CostPerIopsHour) {
		return nil, false
	}
	return o.CostPerIopsHour, true
}

// HasCostPerIopsHour returns a boolean if a field has been set.
func (o *DatabasePrice) HasCostPerIopsHour() bool {
	if o != nil && !IsNil(o.CostPerIopsHour) {
		return true
	}

	return false
}

// SetCostPerIopsHour gets a reference to the given float32 and assigns it to the CostPerIopsHour field.
func (o *DatabasePrice) SetCostPerIopsHour(v float32) {
	o.CostPerIopsHour = &v
}

// GetCostPerStorageGbHour returns the CostPerStorageGbHour field value if set, zero value otherwise.
func (o *DatabasePrice) GetCostPerStorageGbHour() float32 {
	if o == nil || IsNil(o.CostPerStorageGbHour) {
		var ret float32
		return ret
	}
	return *o.CostPerStorageGbHour
}

// GetCostPerStorageGbHourOk returns a tuple with the CostPerStorageGbHour field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DatabasePrice) GetCostPerStorageGbHourOk() (*float32, bool) {
	if o == nil || IsNil(o.CostPerStorageGbHour) {
		return nil, false
	}
	return o.CostPerStorageGbHour, true
}

// HasCostPerStorageGbHour returns a boolean if a field has been set.
func (o *DatabasePrice) HasCostPerStorageGbHour() bool {
	if o != nil && !IsNil(o.CostPerStorageGbHour) {
		return true
	}

	return false
}

// SetCostPerStorageGbHour gets a reference to the given float32 and assigns it to the CostPerStorageGbHour field.
func (o *DatabasePrice) SetCostPerStorageGbHour(v float32) {
	o.CostPerStorageGbHour = &v
}

// GetCostPerThroughputMbpsHour returns the CostPerThroughputMbpsHour field value if set, zero value otherwise.
func (o *DatabasePrice) GetCostPerThroughputMbpsHour() float32 {
	if o == nil || IsNil(o.CostPerThroughputMbpsHour) {
		var ret float32
		return ret
	}
	return *o.CostPerThroughputMbpsHour
}

// GetCostPerThroughputMbpsHourOk returns a tuple with the CostPerThroughputMbpsHour field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DatabasePrice) GetCostPerThroughputMbpsHourOk() (*float32, bool) {
	if o == nil || IsNil(o.CostPerThroughputMbpsHour) {
		return nil, false
	}
	return o.CostPerThroughputMbpsHour, true
}

// HasCostPerThroughputMbpsHour returns a boolean if a field has been set.
func (o *DatabasePrice) HasCostPerThroughputMbpsHour() bool {
	if o != nil && !IsNil(o.CostPerThroughputMbpsHour) {
		return true
	}

	return false
}

// SetCostPerThroughputMbpsHour gets a reference to the given float32 and assigns it to the CostPerThroughputMbpsHour field.
func (o *DatabasePrice) SetCostPerThroughputMbpsHour(v float32) {
	o.CostPerThroughputMbpsHour = &v
}

// GetCostPerVcpuLicenseHour returns the CostPerVcpuLicenseHour field value if set, zero value otherwise.
func (o *DatabasePrice) GetCostPerVcpuLicenseHour() float32 {
	if o == nil || IsNil(o.CostPerVcpuLicenseHour) {
		var ret float32
		return ret
	}
	return *o.CostPerVcpuLicenseHour
}

// GetCostPerVcpuLicenseHourOk returns a tuple with the CostPerVcpuLicenseHour field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DatabasePrice) GetCostPerVcpuLicenseHourOk() (*float32, bool) {
	if o == nil || IsNil(o.CostPerVcpuLicenseHour) {
		return nil, false
	}
	return o.CostPerVcpuLicenseHour, true
}

// HasCostPerVcpuLicenseHour returns a boolean if a field has been set.
func (o *DatabasePrice) HasCostPerVcpuLicenseHour() bool {
	if o != nil && !IsNil(o.CostPerVcpuLicenseHour) {
		return true
	}

	return false
}

// SetCostPerVcpuLicenseHour gets a reference to the given float32 and assigns it to the CostPerVcpuLicenseHour field.
func (o *DatabasePrice) SetCostPerVcpuLicenseHour(v float32) {
	o.CostPerVcpuLicenseHour = &v
}

// GetCpuCores returns the CpuCores field value if set, zero value otherwise.
func (o *DatabasePrice) GetCpuCores() float32 {
	if o == nil || IsNil(o.CpuCores) {
		var ret float32
		return ret
	}
	return *o.CpuCores
}

// GetCpuCoresOk returns a tuple with the CpuCores field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DatabasePrice) GetCpuCoresOk() (*float32, bool) {
	if o == nil || IsNil(o.CpuCores) {
		return nil, false
	}
	return o.CpuCores, true
}

// HasCpuCores returns a boolean if a field has been set.
func (o *DatabasePrice) HasCpuCores() bool {
	if o != nil && !IsNil(o.CpuCores) {
		return true
	}

	return false
}

// SetCpuCores gets a reference to the given float32 and assigns it to the CpuCores field.
func (o *DatabasePrice) SetCpuCores(v float32) {
	o.CpuCores = &v
}

// GetCpuCoresCostPerHour returns the CpuCoresCostPerHour field value if set, zero value otherwise.
func (o *DatabasePrice) GetCpuCoresCostPerHour() float32 {
	if o == nil || IsNil(o.CpuCoresCostPerHour) {
		var ret float32
		return ret
	}
	return *o.CpuCoresCostPerHour
}

// GetCpuCoresCostPerHourOk returns a tuple with the CpuCoresCostPerHour field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DatabasePrice) GetCpuCoresCostPerHourOk() (*float32, bool) {
	if o == nil || IsNil(o.CpuCoresCostPerHour) {
		return nil, false
	}
	return o.CpuCoresCostPerHour, true
}

// HasCpuCoresCostPerHour returns a boolean if a field has been set.
func (o *DatabasePrice) HasCpuCoresCostPerHour() bool {
	if o != nil && !IsNil(o.CpuCoresCostPerHour) {
		return true
	}

	return false
}

// SetCpuCoresCostPerHour gets a reference to the given float32 and assigns it to the CpuCoresCostPerHour field.
func (o *DatabasePrice) SetCpuCoresCostPerHour(v float32) {
	o.CpuCoresCostPerHour = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *DatabasePrice) GetCreatedAt() string {
	if o == nil || IsNil(o.CreatedAt) {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DatabasePrice) GetCreatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *DatabasePrice) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *DatabasePrice) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *DatabasePrice) GetCurrency() string {
	if o == nil || IsNil(o.Currency) {
		var ret string
		return ret
	}
	return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DatabasePrice) GetCurrencyOk() (*string, bool) {
	if o == nil || IsNil(o.Currency) {
		return nil, false
	}
	return o.Currency, true
}

// HasCurrency returns a boolean if a field has been set.
func (o *DatabasePrice) HasCurrency() bool {
	if o != nil && !IsNil(o.Currency) {
		return true
	}

	return false
}

// SetCurrency gets a reference to the given string and assigns it to the Currency field.
func (o *DatabasePrice) SetCurrency(v string) {
	o.Currency = &v
}

// GetDeploymentOption returns the DeploymentOption field value if set, zero value otherwise.
func (o *DatabasePrice) GetDeploymentOption() string {
	if o == nil || IsNil(o.DeploymentOption) {
		var ret string
		return ret
	}
	return *o.DeploymentOption
}

// GetDeploymentOptionOk returns a tuple with the DeploymentOption field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DatabasePrice) GetDeploymentOptionOk() (*string, bool) {
	if o == nil || IsNil(o.DeploymentOption) {
		return nil, false
	}
	return o.DeploymentOption, true
}

// HasDeploymentOption returns a boolean if a field has been set.
func (o *DatabasePrice) HasDeploymentOption() bool {
	if o != nil && !IsNil(o.DeploymentOption) {
		return true
	}

	return false
}

// SetDeploymentOption gets a reference to the given string and assigns it to the DeploymentOption field.
func (o *DatabasePrice) SetDeploymentOption(v string) {
	o.DeploymentOption = &v
}

// GetEdition returns the Edition field value if set, zero value otherwise.
func (o *DatabasePrice) GetEdition() string {
	if o == nil || IsNil(o.Edition) {
		var ret string
		return ret
	}
	return *o.Edition
}

// GetEditionOk returns a tuple with the Edition field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DatabasePrice) GetEditionOk() (*string, bool) {
	if o == nil || IsNil(o.Edition) {
		return nil, false
	}
	return o.Edition, true
}

// HasEdition returns a boolean if a field has been set.
func (o *DatabasePrice) HasEdition() bool {
	if o != nil && !IsNil(o.Edition) {
		return true
	}

	return false
}

// SetEdition gets a reference to the given string and assigns it to the Edition field.
func (o *DatabasePrice) SetEdition(v string) {
	o.Edition = &v
}

// GetEngine returns the Engine field value if set, zero value otherwise.
func (o *DatabasePrice) GetEngine() string {
	if o == nil || IsNil(o.Engine) {
		var ret string
		return ret
	}
	return *o.Engine
}

// GetEngineOk returns a tuple with the Engine field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DatabasePrice) GetEngineOk() (*string, bool) {
	if o == nil || IsNil(o.Engine) {
		return nil, false
	}
	return o.Engine, true
}

// HasEngine returns a boolean if a field has been set.
func (o *DatabasePrice) HasEngine() bool {
	if o != nil && !IsNil(o.Engine) {
		return true
	}

	return false
}

// SetEngine gets a reference to the given string and assigns it to the Engine field.
func (o *DatabasePrice) SetEngine(v string) {
	o.Engine = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *DatabasePrice) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DatabasePrice) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *DatabasePrice) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *DatabasePrice) SetId(v string) {
	o.Id = &v
}

// GetInstanceType returns the InstanceType field value if set, zero value otherwise.
func (o *DatabasePrice) GetInstanceType() string {
	if o == nil || IsNil(o.InstanceType) {
		var ret string
		return ret
	}
	return *o.InstanceType
}

// GetInstanceTypeOk returns a tuple with the InstanceType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DatabasePrice) GetInstanceTypeOk() (*string, bool) {
	if o == nil || IsNil(o.InstanceType) {
		return nil, false
	}
	return o.InstanceType, true
}

// HasInstanceType returns a boolean if a field has been set.
func (o *DatabasePrice) HasInstanceType() bool {
	if o != nil && !IsNil(o.InstanceType) {
		return true
	}

	return false
}

// SetInstanceType gets a reference to the given string and assigns it to the InstanceType field.
func (o *DatabasePrice) SetInstanceType(v string) {
	o.InstanceType = &v
}

// GetMaxIops returns the MaxIops field value if set, zero value otherwise.
func (o *DatabasePrice) GetMaxIops() float32 {
	if o == nil || IsNil(o.MaxIops) {
		var ret float32
		return ret
	}
	return *o.MaxIops
}

// GetMaxIopsOk returns a tuple with the MaxIops field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DatabasePrice) GetMaxIopsOk() (*float32, bool) {
	if o == nil || IsNil(o.MaxIops) {
		return nil, false
	}
	return o.MaxIops, true
}

// HasMaxIops returns a boolean if a field has been set.
func (o *DatabasePrice) HasMaxIops() bool {
	if o != nil && !IsNil(o.MaxIops) {
		return true
	}

	return false
}

// SetMaxIops gets a reference to the given float32 and assigns it to the MaxIops field.
func (o *DatabasePrice) SetMaxIops(v float32) {
	o.MaxIops = &v
}

// GetMaxStorageGb returns the MaxStorageGb field value if set, zero value otherwise.
func (o *DatabasePrice) GetMaxStorageGb() float32 {
	if o == nil || IsNil(o.MaxStorageGb) {
		var ret float32
		return ret
	}
	return *o.MaxStorageGb
}

// GetMaxStorageGbOk returns a tuple with the MaxStorageGb field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DatabasePrice) GetMaxStorageGbOk() (*float32, bool) {
	if o == nil || IsNil(o.MaxStorageGb) {
		return nil, false
	}
	return o.MaxStorageGb, true
}

// HasMaxStorageGb returns a boolean if a field has been set.
func (o *DatabasePrice) HasMaxStorageGb() bool {
	if o != nil && !IsNil(o.MaxStorageGb) {
		return true
	}

	return false
}

// SetMaxStorageGb gets a reference to the given float32 and assigns it to the MaxStorageGb field.
func (o *DatabasePrice) SetMaxStorageGb(v float32) {
	o.MaxStorageGb = &v
}

// GetMaxThroughputMbps returns the MaxThroughputMbps field value if set, zero value otherwise.
func (o *DatabasePrice) GetMaxThroughputMbps() float32 {
	if o == nil || IsNil(o.MaxThroughputMbps) {
		var ret float32
		return ret
	}
	return *o.MaxThroughputMbps
}

// GetMaxThroughputMbpsOk returns a tuple with the MaxThroughputMbps field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DatabasePrice) GetMaxThroughputMbpsOk() (*float32, bool) {
	if o == nil || IsNil(o.MaxThroughputMbps) {
		return nil, false
	}
	return o.MaxThroughputMbps, true
}

// HasMaxThroughputMbps returns a boolean if a field has been set.
func (o *DatabasePrice) HasMaxThroughputMbps() bool {
	if o != nil && !IsNil(o.MaxThroughputMbps) {
		return true
	}

	return false
}

// SetMaxThroughputMbps gets a reference to the given float32 and assigns it to the MaxThroughputMbps field.
func (o *DatabasePrice) SetMaxThroughputMbps(v float32) {
	o.MaxThroughputMbps = &v
}

// GetMinIops returns the MinIops field value if set, zero value otherwise.
func (o *DatabasePrice) GetMinIops() float32 {
	if o == nil || IsNil(o.MinIops) {
		var ret float32
		return ret
	}
	return *o.MinIops
}

// GetMinIopsOk returns a tuple with the MinIops field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DatabasePrice) GetMinIopsOk() (*float32, bool) {
	if o == nil || IsNil(o.MinIops) {
		return nil, false
	}
	return o.MinIops, true
}

// HasMinIops returns a boolean if a field has been set.
func (o *DatabasePrice) HasMinIops() bool {
	if o != nil && !IsNil(o.MinIops) {
		return true
	}

	return false
}

// SetMinIops gets a reference to the given float32 and assigns it to the MinIops field.
func (o *DatabasePrice) SetMinIops(v float32) {
	o.MinIops = &v
}

// GetMinStorageGb returns the MinStorageGb field value if set, zero value otherwise.
func (o *DatabasePrice) GetMinStorageGb() float32 {
	if o == nil || IsNil(o.MinStorageGb) {
		var ret float32
		return ret
	}
	return *o.MinStorageGb
}

// GetMinStorageGbOk returns a tuple with the MinStorageGb field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DatabasePrice) GetMinStorageGbOk() (*float32, bool) {
	if o == nil || IsNil(o.MinStorageGb) {
		return nil, false
	}
	return o.MinStorageGb, true
}

// HasMinStorageGb returns a boolean if a field has been set.
func (o *DatabasePrice) HasMinStorageGb() bool {
	if o != nil && !IsNil(o.MinStorageGb) {
		return true
	}

	return false
}

// SetMinStorageGb gets a reference to the given float32 and assigns it to the MinStorageGb field.
func (o *DatabasePrice) SetMinStorageGb(v float32) {
	o.MinStorageGb = &v
}

// GetMinThroughputMbps returns the MinThroughputMbps field value if set, zero value otherwise.
func (o *DatabasePrice) GetMinThroughputMbps() float32 {
	if o == nil || IsNil(o.MinThroughputMbps) {
		var ret float32
		return ret
	}
	return *o.MinThroughputMbps
}

// GetMinThroughputMbpsOk returns a tuple with the MinThroughputMbps field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DatabasePrice) GetMinThroughputMbpsOk() (*float32, bool) {
	if o == nil || IsNil(o.MinThroughputMbps) {
		return nil, false
	}
	return o.MinThroughputMbps, true
}

// HasMinThroughputMbps returns a boolean if a field has been set.
func (o *DatabasePrice) HasMinThroughputMbps() bool {
	if o != nil && !IsNil(o.MinThroughputMbps) {
		return true
	}

	return false
}

// SetMinThroughputMbps gets a reference to the given float32 and assigns it to the MinThroughputMbps field.
func (o *DatabasePrice) SetMinThroughputMbps(v float32) {
	o.MinThroughputMbps = &v
}

// GetNativeCostPerHour returns the NativeCostPerHour field value if set, zero value otherwise.
func (o *DatabasePrice) GetNativeCostPerHour() float32 {
	if o == nil || IsNil(o.NativeCostPerHour) {
		var ret float32
		return ret
	}
	return *o.NativeCostPerHour
}

// GetNativeCostPerHourOk returns a tuple with the NativeCostPerHour field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DatabasePrice) GetNativeCostPerHourOk() (*float32, bool) {
	if o == nil || IsNil(o.NativeCostPerHour) {
		return nil, false
	}
	return o.NativeCostPerHour, true
}

// HasNativeCostPerHour returns a boolean if a field has been set.
func (o *DatabasePrice) HasNativeCostPerHour() bool {
	if o != nil && !IsNil(o.NativeCostPerHour) {
		return true
	}

	return false
}

// SetNativeCostPerHour gets a reference to the given float32 and assigns it to the NativeCostPerHour field.
func (o *DatabasePrice) SetNativeCostPerHour(v float32) {
	o.NativeCostPerHour = &v
}

// GetNativeCostPerStorageGbHour returns the NativeCostPerStorageGbHour field value if set, zero value otherwise.
func (o *DatabasePrice) GetNativeCostPerStorageGbHour() float32 {
	if o == nil || IsNil(o.NativeCostPerStorageGbHour) {
		var ret float32
		return ret
	}
	return *o.NativeCostPerStorageGbHour
}

// GetNativeCostPerStorageGbHourOk returns a tuple with the NativeCostPerStorageGbHour field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DatabasePrice) GetNativeCostPerStorageGbHourOk() (*float32, bool) {
	if o == nil || IsNil(o.NativeCostPerStorageGbHour) {
		return nil, false
	}
	return o.NativeCostPerStorageGbHour, true
}

// HasNativeCostPerStorageGbHour returns a boolean if a field has been set.
func (o *DatabasePrice) HasNativeCostPerStorageGbHour() bool {
	if o != nil && !IsNil(o.NativeCostPerStorageGbHour) {
		return true
	}

	return false
}

// SetNativeCostPerStorageGbHour gets a reference to the given float32 and assigns it to the NativeCostPerStorageGbHour field.
func (o *DatabasePrice) SetNativeCostPerStorageGbHour(v float32) {
	o.NativeCostPerStorageGbHour = &v
}

// GetPeriodBillingHours returns the PeriodBillingHours field value if set, zero value otherwise.
func (o *DatabasePrice) GetPeriodBillingHours() float32 {
	if o == nil || IsNil(o.PeriodBillingHours) {
		var ret float32
		return ret
	}
	return *o.PeriodBillingHours
}

// GetPeriodBillingHoursOk returns a tuple with the PeriodBillingHours field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DatabasePrice) GetPeriodBillingHoursOk() (*float32, bool) {
	if o == nil || IsNil(o.PeriodBillingHours) {
		return nil, false
	}
	return o.PeriodBillingHours, true
}

// HasPeriodBillingHours returns a boolean if a field has been set.
func (o *DatabasePrice) HasPeriodBillingHours() bool {
	if o != nil && !IsNil(o.PeriodBillingHours) {
		return true
	}

	return false
}

// SetPeriodBillingHours gets a reference to the given float32 and assigns it to the PeriodBillingHours field.
func (o *DatabasePrice) SetPeriodBillingHours(v float32) {
	o.PeriodBillingHours = &v
}

// GetProvider returns the Provider field value if set, zero value otherwise.
func (o *DatabasePrice) GetProvider() string {
	if o == nil || IsNil(o.Provider) {
		var ret string
		return ret
	}
	return *o.Provider
}

// GetProviderOk returns a tuple with the Provider field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DatabasePrice) GetProviderOk() (*string, bool) {
	if o == nil || IsNil(o.Provider) {
		return nil, false
	}
	return o.Provider, true
}

// HasProvider returns a boolean if a field has been set.
func (o *DatabasePrice) HasProvider() bool {
	if o != nil && !IsNil(o.Provider) {
		return true
	}

	return false
}

// SetProvider gets a reference to the given string and assigns it to the Provider field.
func (o *DatabasePrice) SetProvider(v string) {
	o.Provider = &v
}

// GetRamGb returns the RamGb field value if set, zero value otherwise.
func (o *DatabasePrice) GetRamGb() float32 {
	if o == nil || IsNil(o.RamGb) {
		var ret float32
		return ret
	}
	return *o.RamGb
}

// GetRamGbOk returns a tuple with the RamGb field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DatabasePrice) GetRamGbOk() (*float32, bool) {
	if o == nil || IsNil(o.RamGb) {
		return nil, false
	}
	return o.RamGb, true
}

// HasRamGb returns a boolean if a field has been set.
func (o *DatabasePrice) HasRamGb() bool {
	if o != nil && !IsNil(o.RamGb) {
		return true
	}

	return false
}

// SetRamGb gets a reference to the given float32 and assigns it to the RamGb field.
func (o *DatabasePrice) SetRamGb(v float32) {
	o.RamGb = &v
}

// GetRamGbCostPerHour returns the RamGbCostPerHour field value if set, zero value otherwise.
func (o *DatabasePrice) GetRamGbCostPerHour() float32 {
	if o == nil || IsNil(o.RamGbCostPerHour) {
		var ret float32
		return ret
	}
	return *o.RamGbCostPerHour
}

// GetRamGbCostPerHourOk returns a tuple with the RamGbCostPerHour field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DatabasePrice) GetRamGbCostPerHourOk() (*float32, bool) {
	if o == nil || IsNil(o.RamGbCostPerHour) {
		return nil, false
	}
	return o.RamGbCostPerHour, true
}

// HasRamGbCostPerHour returns a boolean if a field has been set.
func (o *DatabasePrice) HasRamGbCostPerHour() bool {
	if o != nil && !IsNil(o.RamGbCostPerHour) {
		return true
	}

	return false
}

// SetRamGbCostPerHour gets a reference to the given float32 and assigns it to the RamGbCostPerHour field.
func (o *DatabasePrice) SetRamGbCostPerHour(v float32) {
	o.RamGbCostPerHour = &v
}

// GetRawPricingData returns the RawPricingData field value if set, zero value otherwise.
func (o *DatabasePrice) GetRawPricingData() map[string]interface{} {
	if o == nil || IsNil(o.RawPricingData) {
		var ret map[string]interface{}
		return ret
	}
	return o.RawPricingData
}

// GetRawPricingDataOk returns a tuple with the RawPricingData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DatabasePrice) GetRawPricingDataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.RawPricingData) {
		return map[string]interface{}{}, false
	}
	return o.RawPricingData, true
}

// HasRawPricingData returns a boolean if a field has been set.
func (o *DatabasePrice) HasRawPricingData() bool {
	if o != nil && !IsNil(o.RawPricingData) {
		return true
	}

	return false
}

// SetRawPricingData gets a reference to the given map[string]interface{} and assigns it to the RawPricingData field.
func (o *DatabasePrice) SetRawPricingData(v map[string]interface{}) {
	o.RawPricingData = v
}

// GetRegion returns the Region field value if set, zero value otherwise.
func (o *DatabasePrice) GetRegion() string {
	if o == nil || IsNil(o.Region) {
		var ret string
		return ret
	}
	return *o.Region
}

// GetRegionOk returns a tuple with the Region field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DatabasePrice) GetRegionOk() (*string, bool) {
	if o == nil || IsNil(o.Region) {
		return nil, false
	}
	return o.Region, true
}

// HasRegion returns a boolean if a field has been set.
func (o *DatabasePrice) HasRegion() bool {
	if o != nil && !IsNil(o.Region) {
		return true
	}

	return false
}

// SetRegion gets a reference to the given string and assigns it to the Region field.
func (o *DatabasePrice) SetRegion(v string) {
	o.Region = &v
}

// GetService returns the Service field value if set, zero value otherwise.
func (o *DatabasePrice) GetService() string {
	if o == nil || IsNil(o.Service) {
		var ret string
		return ret
	}
	return *o.Service
}

// GetServiceOk returns a tuple with the Service field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DatabasePrice) GetServiceOk() (*string, bool) {
	if o == nil || IsNil(o.Service) {
		return nil, false
	}
	return o.Service, true
}

// HasService returns a boolean if a field has been set.
func (o *DatabasePrice) HasService() bool {
	if o != nil && !IsNil(o.Service) {
		return true
	}

	return false
}

// SetService gets a reference to the given string and assigns it to the Service field.
func (o *DatabasePrice) SetService(v string) {
	o.Service = &v
}

// GetStorageType returns the StorageType field value if set, zero value otherwise.
func (o *DatabasePrice) GetStorageType() string {
	if o == nil || IsNil(o.StorageType) {
		var ret string
		return ret
	}
	return *o.StorageType
}

// GetStorageTypeOk returns a tuple with the StorageType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DatabasePrice) GetStorageTypeOk() (*string, bool) {
	if o == nil || IsNil(o.StorageType) {
		return nil, false
	}
	return o.StorageType, true
}

// HasStorageType returns a boolean if a field has been set.
func (o *DatabasePrice) HasStorageType() bool {
	if o != nil && !IsNil(o.StorageType) {
		return true
	}

	return false
}

// SetStorageType gets a reference to the given string and assigns it to the StorageType field.
func (o *DatabasePrice) SetStorageType(v string) {
	o.StorageType = &v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *DatabasePrice) GetTags() map[string]interface{} {
	if o == nil || IsNil(o.Tags) {
		var ret map[string]interface{}
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DatabasePrice) GetTagsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Tags) {
		return map[string]interface{}{}, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *DatabasePrice) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given map[string]interface{} and assigns it to the Tags field.
func (o *DatabasePrice) SetTags(v map[string]interface{}) {
	o.Tags = v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *DatabasePrice) GetUpdatedAt() string {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret string
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DatabasePrice) GetUpdatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *DatabasePrice) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given string and assigns it to the UpdatedAt field.
func (o *DatabasePrice) SetUpdatedAt(v string) {
	o.UpdatedAt = &v
}

// GetUsageType returns the UsageType field value if set, zero value otherwise.
func (o *DatabasePrice) GetUsageType() string {
	if o == nil || IsNil(o.UsageType) {
		var ret string
		return ret
	}
	return *o.UsageType
}

// GetUsageTypeOk returns a tuple with the UsageType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DatabasePrice) GetUsageTypeOk() (*string, bool) {
	if o == nil || IsNil(o.UsageType) {
		return nil, false
	}
	return o.UsageType, true
}

// HasUsageType returns a boolean if a field has been set.
func (o *DatabasePrice) HasUsageType() bool {
	if o != nil && !IsNil(o.UsageType) {
		return true
	}

	return false
}

// SetUsageType gets a reference to the given string and assigns it to the UsageType field.
func (o *DatabasePrice) SetUsageType(v string) {
	o.UsageType = &v
}

func (o DatabasePrice) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DatabasePrice) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Architecture) {
		toSerialize["architecture"] = o.Architecture
	}
	if !IsNil(o.AvailabilityZone) {
		toSerialize["availability_zone"] = o.AvailabilityZone
	}
	if !IsNil(o.BillingConfig) {
		toSerialize["billing_config"] = o.BillingConfig
	}
	if !IsNil(o.CapacityUnit) {
		toSerialize["capacity_unit"] = o.CapacityUnit
	}
	if !IsNil(o.CostPerCapacityUnit) {
		toSerialize["cost_per_capacity_unit"] = o.CostPerCapacityUnit
	}
	if !IsNil(o.CostPerHour) {
		toSerialize["cost_per_hour"] = o.CostPerHour
	}
	if !IsNil(o.CostPerIoRequest) {
		toSerialize["cost_per_io_request"] = o.CostPerIoRequest
	}
	if !IsNil(o.CostPerIopsHour) {
		toSerialize["cost_per_iops_hour"] = o.CostPerIopsHour
	}
	if !IsNil(o.CostPerStorageGbHour) {
		toSerialize["cost_per_storage_gb_hour"] = o.CostPerStorageGbHour
	}
	if !IsNil(o.CostPerThroughputMbpsHour) {
		toSerialize["cost_per_throughput_mbps_hour"] = o.CostPerThroughputMbpsHour
	}
	if !IsNil(o.CostPerVcpuLicenseHour) {
		toSerialize["cost_per_vcpu_license_hour"] = o.CostPerVcpuLicenseHour
	}
	if !IsNil(o.CpuCores) {
		toSerialize["cpu_cores"] = o.CpuCores
	}
	if !IsNil(o.CpuCoresCostPerHour) {
		toSerialize["cpu_cores_cost_per_hour"] = o.CpuCoresCostPerHour
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.Currency) {
		toSerialize["currency"] = o.Currency
	}
	if !IsNil(o.DeploymentOption) {
		toSerialize["deployment_option"] = o.DeploymentOption
	}
	if !IsNil(o.Edition) {
		toSerialize["edition"] = o.Edition
	}
	if !IsNil(o.Engine) {
		toSerialize["engine"] = o.Engine
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.InstanceType) {
		toSerialize["instance_type"] = o.InstanceType
	}
	if !IsNil(o.MaxIops) {
		toSerialize["max_iops"] = o.MaxIops
	}
	if !IsNil(o.MaxStorageGb) {
		toSerialize["max_storage_gb"] = o.MaxStorageGb
	}
	if !IsNil(o.MaxThroughputMbps) {
		toSerialize["max_throughput_mbps"] = o.MaxThroughputMbps
	}
	if !IsNil(o.MinIops) {
		toSerialize["min_iops"] = o.MinIops
	}
	if !IsNil(o.MinStorageGb) {
		toSerialize["min_storage_gb"] = o.MinStorageGb
	}
	if !IsNil(o.MinThroughputMbps) {
		toSerialize["min_throughput_mbps"] = o.MinThroughputMbps
	}
	if !IsNil(o.NativeCostPerHour) {
		toSerialize["native_cost_per_hour"] = o.NativeCostPerHour
	}
	if !IsNil(o.NativeCostPerStorageGbHour) {
		toSerialize["native_cost_per_storage_gb_hour"] = o.NativeCostPerStorageGbHour
	}
	if !IsNil(o.PeriodBillingHours) {
		toSerialize["period_billing_hours"] = o.PeriodBillingHours
	}
	if !IsNil(o.Provider) {
		toSerialize["provider"] = o.Provider
	}
	if !IsNil(o.RamGb) {
		toSerialize["ram_gb"] = o.RamGb
	}
	if !IsNil(o.RamGbCostPerHour) {
		toSerialize["ram_gb_cost_per_hour"] = o.RamGbCostPerHour
	}
	if !IsNil(o.RawPricingData) {
		toSerialize["raw_pricing_data"] = o.RawPricingData
	}
	if !IsNil(o.Region) {
		toSerialize["region"] = o.Region
	}
	if !IsNil(o.Service) {
		toSerialize["service"] = o.Service
	}
	if !IsNil(o.StorageType) {
		toSerialize["storage_type"] = o.StorageType
	}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	if !IsNil(o.UsageType) {
		toSerialize["usage_type"] = o.UsageType
	}
	return toSerialize, nil
}

type NullableDatabasePrice struct {
	value *DatabasePrice
	isSet bool
}

func (v NullableDatabasePrice) Get() *DatabasePrice {
	return v.value
}

func (v *NullableDatabasePrice) Set(val *DatabasePrice) {
	v.value = val
	v.isSet = true
}

func (v NullableDatabasePrice) IsSet() bool {
	return v.isSet
}

func (v *NullableDatabasePrice) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDatabasePrice(val *DatabasePrice) *NullableDatabasePrice {
	return &NullableDatabasePrice{value: val, isSet: true}
}

func (v NullableDatabasePrice) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDatabasePrice) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
