/*
Pricing API

Provides API level access to the Costgraph Services.

API version: 1.0
Contact: contact@baselinehq.cloud
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pricing_api_client

import (
	"encoding/json"
)

// checks if the SchemaDiskPricingsRow type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SchemaDiskPricingsRow{}

// SchemaDiskPricingsRow struct for SchemaDiskPricingsRow
type SchemaDiskPricingsRow struct {
	AvailabilityZone *string `json:"availability_zone,omitempty"`
	CostPerGbHour *float32 `json:"cost_per_gb_hour,omitempty"`
	CostPerIopsHour *float32 `json:"cost_per_iops_hour,omitempty"`
	CostPerThroughputMbpsHour *float32 `json:"cost_per_throughput_mbps_hour,omitempty"`
	CreatedAt *string `json:"created_at,omitempty"`
	Id *string `json:"id,omitempty"`
	MaxCapacityGb *float32 `json:"max_capacity_gb,omitempty"`
	MaxIops *float32 `json:"max_iops,omitempty"`
	MaxThroughputMbps *float32 `json:"max_throughput_mbps,omitempty"`
	MinCapacityGb *float32 `json:"min_capacity_gb,omitempty"`
	MinIops *float32 `json:"min_iops,omitempty"`
	MinThroughputMbps *float32 `json:"min_throughput_mbps,omitempty"`
	PeriodBillingHours *float32 `json:"period_billing_hours,omitempty"`
	Provider *string `json:"provider,omitempty"`
	RawPricingData map[string]interface{} `json:"raw_pricing_data,omitempty"`
	Region *string `json:"region,omitempty"`
	Service *string `json:"service,omitempty"`
	Tags map[string]interface{} `json:"tags,omitempty"`
	Type *string `json:"type,omitempty"`
	UpdatedAt *string `json:"updated_at,omitempty"`
	UsageType *string `json:"usage_type,omitempty"`
}

// NewSchemaDiskPricingsRow instantiates a new SchemaDiskPricingsRow object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSchemaDiskPricingsRow() *SchemaDiskPricingsRow {
	this := SchemaDiskPricingsRow{}
	return &this
}

// NewSchemaDiskPricingsRowWithDefaults instantiates a new SchemaDiskPricingsRow object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSchemaDiskPricingsRowWithDefaults() *SchemaDiskPricingsRow {
	this := SchemaDiskPricingsRow{}
	return &this
}

// GetAvailabilityZone returns the AvailabilityZone field value if set, zero value otherwise.
func (o *SchemaDiskPricingsRow) GetAvailabilityZone() string {
	if o == nil || IsNil(o.AvailabilityZone) {
		var ret string
		return ret
	}
	return *o.AvailabilityZone
}

// GetAvailabilityZoneOk returns a tuple with the AvailabilityZone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SchemaDiskPricingsRow) GetAvailabilityZoneOk() (*string, bool) {
	if o == nil || IsNil(o.AvailabilityZone) {
		return nil, false
	}
	return o.AvailabilityZone, true
}

// HasAvailabilityZone returns a boolean if a field has been set.
func (o *SchemaDiskPricingsRow) HasAvailabilityZone() bool {
	if o != nil && !IsNil(o.AvailabilityZone) {
		return true
	}

	return false
}

// SetAvailabilityZone gets a reference to the given string and assigns it to the AvailabilityZone field.
func (o *SchemaDiskPricingsRow) SetAvailabilityZone(v string) {
	o.AvailabilityZone = &v
}

// GetCostPerGbHour returns the CostPerGbHour field value if set, zero value otherwise.
func (o *SchemaDiskPricingsRow) GetCostPerGbHour() float32 {
	if o == nil || IsNil(o.CostPerGbHour) {
		var ret float32
		return ret
	}
	return *o.CostPerGbHour
}

// GetCostPerGbHourOk returns a tuple with the CostPerGbHour field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SchemaDiskPricingsRow) GetCostPerGbHourOk() (*float32, bool) {
	if o == nil || IsNil(o.CostPerGbHour) {
		return nil, false
	}
	return o.CostPerGbHour, true
}

// HasCostPerGbHour returns a boolean if a field has been set.
func (o *SchemaDiskPricingsRow) HasCostPerGbHour() bool {
	if o != nil && !IsNil(o.CostPerGbHour) {
		return true
	}

	return false
}

// SetCostPerGbHour gets a reference to the given float32 and assigns it to the CostPerGbHour field.
func (o *SchemaDiskPricingsRow) SetCostPerGbHour(v float32) {
	o.CostPerGbHour = &v
}

// GetCostPerIopsHour returns the CostPerIopsHour field value if set, zero value otherwise.
func (o *SchemaDiskPricingsRow) GetCostPerIopsHour() float32 {
	if o == nil || IsNil(o.CostPerIopsHour) {
		var ret float32
		return ret
	}
	return *o.CostPerIopsHour
}

// GetCostPerIopsHourOk returns a tuple with the CostPerIopsHour field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SchemaDiskPricingsRow) GetCostPerIopsHourOk() (*float32, bool) {
	if o == nil || IsNil(o.CostPerIopsHour) {
		return nil, false
	}
	return o.CostPerIopsHour, true
}

// HasCostPerIopsHour returns a boolean if a field has been set.
func (o *SchemaDiskPricingsRow) HasCostPerIopsHour() bool {
	if o != nil && !IsNil(o.CostPerIopsHour) {
		return true
	}

	return false
}

// SetCostPerIopsHour gets a reference to the given float32 and assigns it to the CostPerIopsHour field.
func (o *SchemaDiskPricingsRow) SetCostPerIopsHour(v float32) {
	o.CostPerIopsHour = &v
}

// GetCostPerThroughputMbpsHour returns the CostPerThroughputMbpsHour field value if set, zero value otherwise.
func (o *SchemaDiskPricingsRow) GetCostPerThroughputMbpsHour() float32 {
	if o == nil || IsNil(o.CostPerThroughputMbpsHour) {
		var ret float32
		return ret
	}
	return *o.CostPerThroughputMbpsHour
}

// GetCostPerThroughputMbpsHourOk returns a tuple with the CostPerThroughputMbpsHour field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SchemaDiskPricingsRow) GetCostPerThroughputMbpsHourOk() (*float32, bool) {
	if o == nil || IsNil(o.CostPerThroughputMbpsHour) {
		return nil, false
	}
	return o.CostPerThroughputMbpsHour, true
}

// HasCostPerThroughputMbpsHour returns a boolean if a field has been set.
func (o *SchemaDiskPricingsRow) HasCostPerThroughputMbpsHour() bool {
	if o != nil && !IsNil(o.CostPerThroughputMbpsHour) {
		return true
	}

	return false
}

// SetCostPerThroughputMbpsHour gets a reference to the given float32 and assigns it to the CostPerThroughputMbpsHour field.
func (o *SchemaDiskPricingsRow) SetCostPerThroughputMbpsHour(v float32) {
	o.CostPerThroughputMbpsHour = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *SchemaDiskPricingsRow) GetCreatedAt() string {
	if o == nil || IsNil(o.CreatedAt) {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SchemaDiskPricingsRow) GetCreatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *SchemaDiskPricingsRow) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *SchemaDiskPricingsRow) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *SchemaDiskPricingsRow) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SchemaDiskPricingsRow) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *SchemaDiskPricingsRow) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *SchemaDiskPricingsRow) SetId(v string) {
	o.Id = &v
}

// GetMaxCapacityGb returns the MaxCapacityGb field value if set, zero value otherwise.
func (o *SchemaDiskPricingsRow) GetMaxCapacityGb() float32 {
	if o == nil || IsNil(o.MaxCapacityGb) {
		var ret float32
		return ret
	}
	return *o.MaxCapacityGb
}

// GetMaxCapacityGbOk returns a tuple with the MaxCapacityGb field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SchemaDiskPricingsRow) GetMaxCapacityGbOk() (*float32, bool) {
	if o == nil || IsNil(o.MaxCapacityGb) {
		return nil, false
	}
	return o.MaxCapacityGb, true
}

// HasMaxCapacityGb returns a boolean if a field has been set.
func (o *SchemaDiskPricingsRow) HasMaxCapacityGb() bool {
	if o != nil && !IsNil(o.MaxCapacityGb) {
		return true
	}

	return false
}

// SetMaxCapacityGb gets a reference to the given float32 and assigns it to the MaxCapacityGb field.
func (o *SchemaDiskPricingsRow) SetMaxCapacityGb(v float32) {
	o.MaxCapacityGb = &v
}

// GetMaxIops returns the MaxIops field value if set, zero value otherwise.
func (o *SchemaDiskPricingsRow) GetMaxIops() float32 {
	if o == nil || IsNil(o.MaxIops) {
		var ret float32
		return ret
	}
	return *o.MaxIops
}

// GetMaxIopsOk returns a tuple with the MaxIops field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SchemaDiskPricingsRow) GetMaxIopsOk() (*float32, bool) {
	if o == nil || IsNil(o.MaxIops) {
		return nil, false
	}
	return o.MaxIops, true
}

// HasMaxIops returns a boolean if a field has been set.
func (o *SchemaDiskPricingsRow) HasMaxIops() bool {
	if o != nil && !IsNil(o.MaxIops) {
		return true
	}

	return false
}

// SetMaxIops gets a reference to the given float32 and assigns it to the MaxIops field.
func (o *SchemaDiskPricingsRow) SetMaxIops(v float32) {
	o.MaxIops = &v
}

// GetMaxThroughputMbps returns the MaxThroughputMbps field value if set, zero value otherwise.
func (o *SchemaDiskPricingsRow) GetMaxThroughputMbps() float32 {
	if o == nil || IsNil(o.MaxThroughputMbps) {
		var ret float32
		return ret
	}
	return *o.MaxThroughputMbps
}

// GetMaxThroughputMbpsOk returns a tuple with the MaxThroughputMbps field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SchemaDiskPricingsRow) GetMaxThroughputMbpsOk() (*float32, bool) {
	if o == nil || IsNil(o.MaxThroughputMbps) {
		return nil, false
	}
	return o.MaxThroughputMbps, true
}

// HasMaxThroughputMbps returns a boolean if a field has been set.
func (o *SchemaDiskPricingsRow) HasMaxThroughputMbps() bool {
	if o != nil && !IsNil(o.MaxThroughputMbps) {
		return true
	}

	return false
}

// SetMaxThroughputMbps gets a reference to the given float32 and assigns it to the MaxThroughputMbps field.
func (o *SchemaDiskPricingsRow) SetMaxThroughputMbps(v float32) {
	o.MaxThroughputMbps = &v
}

// GetMinCapacityGb returns the MinCapacityGb field value if set, zero value otherwise.
func (o *SchemaDiskPricingsRow) GetMinCapacityGb() float32 {
	if o == nil || IsNil(o.MinCapacityGb) {
		var ret float32
		return ret
	}
	return *o.MinCapacityGb
}

// GetMinCapacityGbOk returns a tuple with the MinCapacityGb field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SchemaDiskPricingsRow) GetMinCapacityGbOk() (*float32, bool) {
	if o == nil || IsNil(o.MinCapacityGb) {
		return nil, false
	}
	return o.MinCapacityGb, true
}

// HasMinCapacityGb returns a boolean if a field has been set.
func (o *SchemaDiskPricingsRow) HasMinCapacityGb() bool {
	if o != nil && !IsNil(o.MinCapacityGb) {
		return true
	}

	return false
}

// SetMinCapacityGb gets a reference to the given float32 and assigns it to the MinCapacityGb field.
func (o *SchemaDiskPricingsRow) SetMinCapacityGb(v float32) {
	o.MinCapacityGb = &v
}

// GetMinIops returns the MinIops field value if set, zero value otherwise.
func (o *SchemaDiskPricingsRow) GetMinIops() float32 {
	if o == nil || IsNil(o.MinIops) {
		var ret float32
		return ret
	}
	return *o.MinIops
}

// GetMinIopsOk returns a tuple with the MinIops field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SchemaDiskPricingsRow) GetMinIopsOk() (*float32, bool) {
	if o == nil || IsNil(o.MinIops) {
		return nil, false
	}
	return o.MinIops, true
}

// HasMinIops returns a boolean if a field has been set.
func (o *SchemaDiskPricingsRow) HasMinIops() bool {
	if o != nil && !IsNil(o.MinIops) {
		return true
	}

	return false
}

// SetMinIops gets a reference to the given float32 and assigns it to the MinIops field.
func (o *SchemaDiskPricingsRow) SetMinIops(v float32) {
	o.MinIops = &v
}

// GetMinThroughputMbps returns the MinThroughputMbps field value if set, zero value otherwise.
func (o *SchemaDiskPricingsRow) GetMinThroughputMbps() float32 {
	if o == nil || IsNil(o.MinThroughputMbps) {
		var ret float32
		return ret
	}
	return *o.MinThroughputMbps
}

// GetMinThroughputMbpsOk returns a tuple with the MinThroughputMbps field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SchemaDiskPricingsRow) GetMinThroughputMbpsOk() (*float32, bool) {
	if o == nil || IsNil(o.MinThroughputMbps) {
		return nil, false
	}
	return o.MinThroughputMbps, true
}

// HasMinThroughputMbps returns a boolean if a field has been set.
func (o *SchemaDiskPricingsRow) HasMinThroughputMbps() bool {
	if o != nil && !IsNil(o.MinThroughputMbps) {
		return true
	}

	return false
}

// SetMinThroughputMbps gets a reference to the given float32 and assigns it to the MinThroughputMbps field.
func (o *SchemaDiskPricingsRow) SetMinThroughputMbps(v float32) {
	o.MinThroughputMbps = &v
}

// GetPeriodBillingHours returns the PeriodBillingHours field value if set, zero value otherwise.
func (o *SchemaDiskPricingsRow) GetPeriodBillingHours() float32 {
	if o == nil || IsNil(o.PeriodBillingHours) {
		var ret float32
		return ret
	}
	return *o.PeriodBillingHours
}

// GetPeriodBillingHoursOk returns a tuple with the PeriodBillingHours field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SchemaDiskPricingsRow) GetPeriodBillingHoursOk() (*float32, bool) {
	if o == nil || IsNil(o.PeriodBillingHours) {
		return nil, false
	}
	return o.PeriodBillingHours, true
}

// HasPeriodBillingHours returns a boolean if a field has been set.
func (o *SchemaDiskPricingsRow) HasPeriodBillingHours() bool {
	if o != nil && !IsNil(o.PeriodBillingHours) {
		return true
	}

	return false
}

// SetPeriodBillingHours gets a reference to the given float32 and assigns it to the PeriodBillingHours field.
func (o *SchemaDiskPricingsRow) SetPeriodBillingHours(v float32) {
	o.PeriodBillingHours = &v
}

// GetProvider returns the Provider field value if set, zero value otherwise.
func (o *SchemaDiskPricingsRow) GetProvider() string {
	if o == nil || IsNil(o.Provider) {
		var ret string
		return ret
	}
	return *o.Provider
}

// GetProviderOk returns a tuple with the Provider field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SchemaDiskPricingsRow) GetProviderOk() (*string, bool) {
	if o == nil || IsNil(o.Provider) {
		return nil, false
	}
	return o.Provider, true
}

// HasProvider returns a boolean if a field has been set.
func (o *SchemaDiskPricingsRow) HasProvider() bool {
	if o != nil && !IsNil(o.Provider) {
		return true
	}

	return false
}

// SetProvider gets a reference to the given string and assigns it to the Provider field.
func (o *SchemaDiskPricingsRow) SetProvider(v string) {
	o.Provider = &v
}

// GetRawPricingData returns the RawPricingData field value if set, zero value otherwise.
func (o *SchemaDiskPricingsRow) GetRawPricingData() map[string]interface{} {
	if o == nil || IsNil(o.RawPricingData) {
		var ret map[string]interface{}
		return ret
	}
	return o.RawPricingData
}

// GetRawPricingDataOk returns a tuple with the RawPricingData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SchemaDiskPricingsRow) GetRawPricingDataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.RawPricingData) {
		return map[string]interface{}{}, false
	}
	return o.RawPricingData, true
}

// HasRawPricingData returns a boolean if a field has been set.
func (o *SchemaDiskPricingsRow) HasRawPricingData() bool {
	if o != nil && !IsNil(o.RawPricingData) {
		return true
	}

	return false
}

// SetRawPricingData gets a reference to the given map[string]interface{} and assigns it to the RawPricingData field.
func (o *SchemaDiskPricingsRow) SetRawPricingData(v map[string]interface{}) {
	o.RawPricingData = v
}

// GetRegion returns the Region field value if set, zero value otherwise.
func (o *SchemaDiskPricingsRow) GetRegion() string {
	if o == nil || IsNil(o.Region) {
		var ret string
		return ret
	}
	return *o.Region
}

// GetRegionOk returns a tuple with the Region field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SchemaDiskPricingsRow) GetRegionOk() (*string, bool) {
	if o == nil || IsNil(o.Region) {
		return nil, false
	}
	return o.Region, true
}

// HasRegion returns a boolean if a field has been set.
func (o *SchemaDiskPricingsRow) HasRegion() bool {
	if o != nil && !IsNil(o.Region) {
		return true
	}

	return false
}

// SetRegion gets a reference to the given string and assigns it to the Region field.
func (o *SchemaDiskPricingsRow) SetRegion(v string) {
	o.Region = &v
}

// GetService returns the Service field value if set, zero value otherwise.
func (o *SchemaDiskPricingsRow) GetService() string {
	if o == nil || IsNil(o.Service) {
		var ret string
		return ret
	}
	return *o.Service
}

// GetServiceOk returns a tuple with the Service field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SchemaDiskPricingsRow) GetServiceOk() (*string, bool) {
	if o == nil || IsNil(o.Service) {
		return nil, false
	}
	return o.Service, true
}

// HasService returns a boolean if a field has been set.
func (o *SchemaDiskPricingsRow) HasService() bool {
	if o != nil && !IsNil(o.Service) {
		return true
	}

	return false
}

// SetService gets a reference to the given string and assigns it to the Service field.
func (o *SchemaDiskPricingsRow) SetService(v string) {
	o.Service = &v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *SchemaDiskPricingsRow) GetTags() map[string]interface{} {
	if o == nil || IsNil(o.Tags) {
		var ret map[string]interface{}
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SchemaDiskPricingsRow) GetTagsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Tags) {
		return map[string]interface{}{}, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *SchemaDiskPricingsRow) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given map[string]interface{} and assigns it to the Tags field.
func (o *SchemaDiskPricingsRow) SetTags(v map[string]interface{}) {
	o.Tags = v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *SchemaDiskPricingsRow) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SchemaDiskPricingsRow) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *SchemaDiskPricingsRow) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *SchemaDiskPricingsRow) SetType(v string) {
	o.Type = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *SchemaDiskPricingsRow) GetUpdatedAt() string {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret string
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SchemaDiskPricingsRow) GetUpdatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *SchemaDiskPricingsRow) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given string and assigns it to the UpdatedAt field.
func (o *SchemaDiskPricingsRow) SetUpdatedAt(v string) {
	o.UpdatedAt = &v
}

// GetUsageType returns the UsageType field value if set, zero value otherwise.
func (o *SchemaDiskPricingsRow) GetUsageType() string {
	if o == nil || IsNil(o.UsageType) {
		var ret string
		return ret
	}
	return *o.UsageType
}

// GetUsageTypeOk returns a tuple with the UsageType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SchemaDiskPricingsRow) GetUsageTypeOk() (*string, bool) {
	if o == nil || IsNil(o.UsageType) {
		return nil, false
	}
	return o.UsageType, true
}

// HasUsageType returns a boolean if a field has been set.
func (o *SchemaDiskPricingsRow) HasUsageType() bool {
	if o != nil && !IsNil(o.UsageType) {
		return true
	}

	return false
}

// SetUsageType gets a reference to the given string and assigns it to the UsageType field.
func (o *SchemaDiskPricingsRow) SetUsageType(v string) {
	o.UsageType = &v
}

func (o SchemaDiskPricingsRow) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SchemaDiskPricingsRow) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AvailabilityZone) {
		toSerialize["availability_zone"] = o.AvailabilityZone
	}
	if !IsNil(o.CostPerGbHour) {
		toSerialize["cost_per_gb_hour"] = o.CostPerGbHour
	}
	if !IsNil(o.CostPerIopsHour) {
		toSerialize["cost_per_iops_hour"] = o.CostPerIopsHour
	}
	if !IsNil(o.CostPerThroughputMbpsHour) {
		toSerialize["cost_per_throughput_mbps_hour"] = o.CostPerThroughputMbpsHour
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.MaxCapacityGb) {
		toSerialize["max_capacity_gb"] = o.MaxCapacityGb
	}
	if !IsNil(o.MaxIops) {
		toSerialize["max_iops"] = o.MaxIops
	}
	if !IsNil(o.MaxThroughputMbps) {
		toSerialize["max_throughput_mbps"] = o.MaxThroughputMbps
	}
	if !IsNil(o.MinCapacityGb) {
		toSerialize["min_capacity_gb"] = o.MinCapacityGb
	}
	if !IsNil(o.MinIops) {
		toSerialize["min_iops"] = o.MinIops
	}
	if !IsNil(o.MinThroughputMbps) {
		toSerialize["min_throughput_mbps"] = o.MinThroughputMbps
	}
	if !IsNil(o.PeriodBillingHours) {
		toSerialize["period_billing_hours"] = o.PeriodBillingHours
	}
	if !IsNil(o.Provider) {
		toSerialize["provider"] = o.Provider
	}
	if !IsNil(o.RawPricingData) {
		toSerialize["raw_pricing_data"] = o.RawPricingData
	}
	if !IsNil(o.Region) {
		toSerialize["region"] = o.Region
	}
	if !IsNil(o.Service) {
		toSerialize["service"] = o.Service
	}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	if !IsNil(o.UsageType) {
		toSerialize["usage_type"] = o.UsageType
	}
	return toSerialize, nil
}

type NullableSchemaDiskPricingsRow struct {
	value *SchemaDiskPricingsRow
	isSet bool
}

func (v NullableSchemaDiskPricingsRow) Get() *SchemaDiskPricingsRow {
	return v.value
}

func (v *NullableSchemaDiskPricingsRow) Set(val *SchemaDiskPricingsRow) {
	v.value = val
	v.isSet = true
}

func (v NullableSchemaDiskPricingsRow) IsSet() bool {
	return v.isSet
}

func (v *NullableSchemaDiskPricingsRow) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSchemaDiskPricingsRow(val *SchemaDiskPricingsRow) *NullableSchemaDiskPricingsRow {
	return &NullableSchemaDiskPricingsRow{value: val, isSet: true}
}

func (v NullableSchemaDiskPricingsRow) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSchemaDiskPricingsRow) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


