/*
Pricing API

Provides API level access to the Costgraph Services.

API version: 1.0
Contact: support@costgraph.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pricing_api_client

import (
	"encoding/json"
)

// checks if the ModelPriceList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelPriceList{}

// ModelPriceList struct for ModelPriceList
type ModelPriceList struct {
	Providers []ModelPrice `json:"providers,omitempty"`
}

// NewModelPriceList instantiates a new ModelPriceList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelPriceList() *ModelPriceList {
	this := ModelPriceList{}
	return &this
}

// NewModelPriceListWithDefaults instantiates a new ModelPriceList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelPriceListWithDefaults() *ModelPriceList {
	this := ModelPriceList{}
	return &this
}

// GetProviders returns the Providers field value if set, zero value otherwise.
func (o *ModelPriceList) GetProviders() []ModelPrice {
	if o == nil || IsNil(o.Providers) {
		var ret []ModelPrice
		return ret
	}
	return o.Providers
}

// GetProvidersOk returns a tuple with the Providers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelPriceList) GetProvidersOk() ([]ModelPrice, bool) {
	if o == nil || IsNil(o.Providers) {
		return nil, false
	}
	return o.Providers, true
}

// HasProviders returns a boolean if a field has been set.
func (o *ModelPriceList) HasProviders() bool {
	if o != nil && !IsNil(o.Providers) {
		return true
	}

	return false
}

// SetProviders gets a reference to the given []ModelPrice and assigns it to the Providers field.
func (o *ModelPriceList) SetProviders(v []ModelPrice) {
	o.Providers = v
}

func (o ModelPriceList) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelPriceList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Providers) {
		toSerialize["providers"] = o.Providers
	}
	return toSerialize, nil
}

type NullableModelPriceList struct {
	value *ModelPriceList
	isSet bool
}

func (v NullableModelPriceList) Get() *ModelPriceList {
	return v.value
}

func (v *NullableModelPriceList) Set(val *ModelPriceList) {
	v.value = val
	v.isSet = true
}

func (v NullableModelPriceList) IsSet() bool {
	return v.isSet
}

func (v *NullableModelPriceList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelPriceList(val *ModelPriceList) *NullableModelPriceList {
	return &NullableModelPriceList{value: val, isSet: true}
}

func (v NullableModelPriceList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelPriceList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
