/*
Pricing API

Provides API level access to the Costgraph Services.

API version: 1.0
Contact: support@costgraph.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pricing_api_client

import (
	"encoding/json"
)

// checks if the DatabasePricePage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DatabasePricePage{}

// DatabasePricePage struct for DatabasePricePage
type DatabasePricePage struct {
	Data []DatabasePrice `json:"data,omitempty"`
	Page *Page           `json:"page,omitempty"`
}

// NewDatabasePricePage instantiates a new DatabasePricePage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDatabasePricePage() *DatabasePricePage {
	this := DatabasePricePage{}
	return &this
}

// NewDatabasePricePageWithDefaults instantiates a new DatabasePricePage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDatabasePricePageWithDefaults() *DatabasePricePage {
	this := DatabasePricePage{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *DatabasePricePage) GetData() []DatabasePrice {
	if o == nil || IsNil(o.Data) {
		var ret []DatabasePrice
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DatabasePricePage) GetDataOk() ([]DatabasePrice, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *DatabasePricePage) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []DatabasePrice and assigns it to the Data field.
func (o *DatabasePricePage) SetData(v []DatabasePrice) {
	o.Data = v
}

// GetPage returns the Page field value if set, zero value otherwise.
func (o *DatabasePricePage) GetPage() Page {
	if o == nil || IsNil(o.Page) {
		var ret Page
		return ret
	}
	return *o.Page
}

// GetPageOk returns a tuple with the Page field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DatabasePricePage) GetPageOk() (*Page, bool) {
	if o == nil || IsNil(o.Page) {
		return nil, false
	}
	return o.Page, true
}

// HasPage returns a boolean if a field has been set.
func (o *DatabasePricePage) HasPage() bool {
	if o != nil && !IsNil(o.Page) {
		return true
	}

	return false
}

// SetPage gets a reference to the given Page and assigns it to the Page field.
func (o *DatabasePricePage) SetPage(v Page) {
	o.Page = &v
}

func (o DatabasePricePage) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DatabasePricePage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Page) {
		toSerialize["page"] = o.Page
	}
	return toSerialize, nil
}

type NullableDatabasePricePage struct {
	value *DatabasePricePage
	isSet bool
}

func (v NullableDatabasePricePage) Get() *DatabasePricePage {
	return v.value
}

func (v *NullableDatabasePricePage) Set(val *DatabasePricePage) {
	v.value = val
	v.isSet = true
}

func (v NullableDatabasePricePage) IsSet() bool {
	return v.isSet
}

func (v *NullableDatabasePricePage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDatabasePricePage(val *DatabasePricePage) *NullableDatabasePricePage {
	return &NullableDatabasePricePage{value: val, isSet: true}
}

func (v NullableDatabasePricePage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDatabasePricePage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
