/*
Pricing API

Provides API level access to the Costgraph Services.

API version: 1.0
Contact: support@costgraph.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pricing_api_client

import (
	"encoding/json"
)

// checks if the ModelPrice type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelPrice{}

// ModelPrice struct for ModelPrice
type ModelPrice struct {
	ContextLimit     *int32                 `json:"context_limit,omitempty"`
	Currency         *string                `json:"currency,omitempty"`
	EffectiveFrom    *string                `json:"effective_from,omitempty"`
	EffectiveTo      *string                `json:"effective_to,omitempty"`
	FetchedAt        *string                `json:"fetched_at,omitempty"`
	Host             *string                `json:"host,omitempty"`
	Id               *string                `json:"id,omitempty"`
	ModalitiesInput  []string               `json:"modalities_input,omitempty"`
	ModalitiesOutput []string               `json:"modalities_output,omitempty"`
	Model            *string                `json:"model,omitempty"`
	ModelId          *string                `json:"model_id,omitempty"`
	OpenWeights      *bool                  `json:"open_weights,omitempty"`
	OutputLimit      *int32                 `json:"output_limit,omitempty"`
	Provider         *string                `json:"provider,omitempty"`
	Publisher        *string                `json:"publisher,omitempty"`
	RawPricingData   map[string]interface{} `json:"raw_pricing_data,omitempty"`
	Reasoning        *bool                  `json:"reasoning,omitempty"`
	Region           *string                `json:"region,omitempty"`
	SkuPriceId       *string                `json:"sku_price_id,omitempty"`
	Source           *string                `json:"source,omitempty"`
	SourceUrl        *string                `json:"source_url,omitempty"`
	StructuredOutput *bool                  `json:"structured_output,omitempty"`
	Tags             map[string]interface{} `json:"tags,omitempty"`
	TokenBucket      *string                `json:"token_bucket,omitempty"`
	ToolCall         *bool                  `json:"tool_call,omitempty"`
	UnitPricePerMtok *float32               `json:"unit_price_per_mtok,omitempty"`
}

// NewModelPrice instantiates a new ModelPrice object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelPrice() *ModelPrice {
	this := ModelPrice{}
	return &this
}

// NewModelPriceWithDefaults instantiates a new ModelPrice object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelPriceWithDefaults() *ModelPrice {
	this := ModelPrice{}
	return &this
}

// GetContextLimit returns the ContextLimit field value if set, zero value otherwise.
func (o *ModelPrice) GetContextLimit() int32 {
	if o == nil || IsNil(o.ContextLimit) {
		var ret int32
		return ret
	}
	return *o.ContextLimit
}

// GetContextLimitOk returns a tuple with the ContextLimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelPrice) GetContextLimitOk() (*int32, bool) {
	if o == nil || IsNil(o.ContextLimit) {
		return nil, false
	}
	return o.ContextLimit, true
}

// HasContextLimit returns a boolean if a field has been set.
func (o *ModelPrice) HasContextLimit() bool {
	if o != nil && !IsNil(o.ContextLimit) {
		return true
	}

	return false
}

// SetContextLimit gets a reference to the given int32 and assigns it to the ContextLimit field.
func (o *ModelPrice) SetContextLimit(v int32) {
	o.ContextLimit = &v
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *ModelPrice) GetCurrency() string {
	if o == nil || IsNil(o.Currency) {
		var ret string
		return ret
	}
	return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelPrice) GetCurrencyOk() (*string, bool) {
	if o == nil || IsNil(o.Currency) {
		return nil, false
	}
	return o.Currency, true
}

// HasCurrency returns a boolean if a field has been set.
func (o *ModelPrice) HasCurrency() bool {
	if o != nil && !IsNil(o.Currency) {
		return true
	}

	return false
}

// SetCurrency gets a reference to the given string and assigns it to the Currency field.
func (o *ModelPrice) SetCurrency(v string) {
	o.Currency = &v
}

// GetEffectiveFrom returns the EffectiveFrom field value if set, zero value otherwise.
func (o *ModelPrice) GetEffectiveFrom() string {
	if o == nil || IsNil(o.EffectiveFrom) {
		var ret string
		return ret
	}
	return *o.EffectiveFrom
}

// GetEffectiveFromOk returns a tuple with the EffectiveFrom field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelPrice) GetEffectiveFromOk() (*string, bool) {
	if o == nil || IsNil(o.EffectiveFrom) {
		return nil, false
	}
	return o.EffectiveFrom, true
}

// HasEffectiveFrom returns a boolean if a field has been set.
func (o *ModelPrice) HasEffectiveFrom() bool {
	if o != nil && !IsNil(o.EffectiveFrom) {
		return true
	}

	return false
}

// SetEffectiveFrom gets a reference to the given string and assigns it to the EffectiveFrom field.
func (o *ModelPrice) SetEffectiveFrom(v string) {
	o.EffectiveFrom = &v
}

// GetEffectiveTo returns the EffectiveTo field value if set, zero value otherwise.
func (o *ModelPrice) GetEffectiveTo() string {
	if o == nil || IsNil(o.EffectiveTo) {
		var ret string
		return ret
	}
	return *o.EffectiveTo
}

// GetEffectiveToOk returns a tuple with the EffectiveTo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelPrice) GetEffectiveToOk() (*string, bool) {
	if o == nil || IsNil(o.EffectiveTo) {
		return nil, false
	}
	return o.EffectiveTo, true
}

// HasEffectiveTo returns a boolean if a field has been set.
func (o *ModelPrice) HasEffectiveTo() bool {
	if o != nil && !IsNil(o.EffectiveTo) {
		return true
	}

	return false
}

// SetEffectiveTo gets a reference to the given string and assigns it to the EffectiveTo field.
func (o *ModelPrice) SetEffectiveTo(v string) {
	o.EffectiveTo = &v
}

// GetFetchedAt returns the FetchedAt field value if set, zero value otherwise.
func (o *ModelPrice) GetFetchedAt() string {
	if o == nil || IsNil(o.FetchedAt) {
		var ret string
		return ret
	}
	return *o.FetchedAt
}

// GetFetchedAtOk returns a tuple with the FetchedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelPrice) GetFetchedAtOk() (*string, bool) {
	if o == nil || IsNil(o.FetchedAt) {
		return nil, false
	}
	return o.FetchedAt, true
}

// HasFetchedAt returns a boolean if a field has been set.
func (o *ModelPrice) HasFetchedAt() bool {
	if o != nil && !IsNil(o.FetchedAt) {
		return true
	}

	return false
}

// SetFetchedAt gets a reference to the given string and assigns it to the FetchedAt field.
func (o *ModelPrice) SetFetchedAt(v string) {
	o.FetchedAt = &v
}

// GetHost returns the Host field value if set, zero value otherwise.
func (o *ModelPrice) GetHost() string {
	if o == nil || IsNil(o.Host) {
		var ret string
		return ret
	}
	return *o.Host
}

// GetHostOk returns a tuple with the Host field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelPrice) GetHostOk() (*string, bool) {
	if o == nil || IsNil(o.Host) {
		return nil, false
	}
	return o.Host, true
}

// HasHost returns a boolean if a field has been set.
func (o *ModelPrice) HasHost() bool {
	if o != nil && !IsNil(o.Host) {
		return true
	}

	return false
}

// SetHost gets a reference to the given string and assigns it to the Host field.
func (o *ModelPrice) SetHost(v string) {
	o.Host = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ModelPrice) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelPrice) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ModelPrice) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ModelPrice) SetId(v string) {
	o.Id = &v
}

// GetModalitiesInput returns the ModalitiesInput field value if set, zero value otherwise.
func (o *ModelPrice) GetModalitiesInput() []string {
	if o == nil || IsNil(o.ModalitiesInput) {
		var ret []string
		return ret
	}
	return o.ModalitiesInput
}

// GetModalitiesInputOk returns a tuple with the ModalitiesInput field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelPrice) GetModalitiesInputOk() ([]string, bool) {
	if o == nil || IsNil(o.ModalitiesInput) {
		return nil, false
	}
	return o.ModalitiesInput, true
}

// HasModalitiesInput returns a boolean if a field has been set.
func (o *ModelPrice) HasModalitiesInput() bool {
	if o != nil && !IsNil(o.ModalitiesInput) {
		return true
	}

	return false
}

// SetModalitiesInput gets a reference to the given []string and assigns it to the ModalitiesInput field.
func (o *ModelPrice) SetModalitiesInput(v []string) {
	o.ModalitiesInput = v
}

// GetModalitiesOutput returns the ModalitiesOutput field value if set, zero value otherwise.
func (o *ModelPrice) GetModalitiesOutput() []string {
	if o == nil || IsNil(o.ModalitiesOutput) {
		var ret []string
		return ret
	}
	return o.ModalitiesOutput
}

// GetModalitiesOutputOk returns a tuple with the ModalitiesOutput field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelPrice) GetModalitiesOutputOk() ([]string, bool) {
	if o == nil || IsNil(o.ModalitiesOutput) {
		return nil, false
	}
	return o.ModalitiesOutput, true
}

// HasModalitiesOutput returns a boolean if a field has been set.
func (o *ModelPrice) HasModalitiesOutput() bool {
	if o != nil && !IsNil(o.ModalitiesOutput) {
		return true
	}

	return false
}

// SetModalitiesOutput gets a reference to the given []string and assigns it to the ModalitiesOutput field.
func (o *ModelPrice) SetModalitiesOutput(v []string) {
	o.ModalitiesOutput = v
}

// GetModel returns the Model field value if set, zero value otherwise.
func (o *ModelPrice) GetModel() string {
	if o == nil || IsNil(o.Model) {
		var ret string
		return ret
	}
	return *o.Model
}

// GetModelOk returns a tuple with the Model field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelPrice) GetModelOk() (*string, bool) {
	if o == nil || IsNil(o.Model) {
		return nil, false
	}
	return o.Model, true
}

// HasModel returns a boolean if a field has been set.
func (o *ModelPrice) HasModel() bool {
	if o != nil && !IsNil(o.Model) {
		return true
	}

	return false
}

// SetModel gets a reference to the given string and assigns it to the Model field.
func (o *ModelPrice) SetModel(v string) {
	o.Model = &v
}

// GetModelId returns the ModelId field value if set, zero value otherwise.
func (o *ModelPrice) GetModelId() string {
	if o == nil || IsNil(o.ModelId) {
		var ret string
		return ret
	}
	return *o.ModelId
}

// GetModelIdOk returns a tuple with the ModelId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelPrice) GetModelIdOk() (*string, bool) {
	if o == nil || IsNil(o.ModelId) {
		return nil, false
	}
	return o.ModelId, true
}

// HasModelId returns a boolean if a field has been set.
func (o *ModelPrice) HasModelId() bool {
	if o != nil && !IsNil(o.ModelId) {
		return true
	}

	return false
}

// SetModelId gets a reference to the given string and assigns it to the ModelId field.
func (o *ModelPrice) SetModelId(v string) {
	o.ModelId = &v
}

// GetOpenWeights returns the OpenWeights field value if set, zero value otherwise.
func (o *ModelPrice) GetOpenWeights() bool {
	if o == nil || IsNil(o.OpenWeights) {
		var ret bool
		return ret
	}
	return *o.OpenWeights
}

// GetOpenWeightsOk returns a tuple with the OpenWeights field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelPrice) GetOpenWeightsOk() (*bool, bool) {
	if o == nil || IsNil(o.OpenWeights) {
		return nil, false
	}
	return o.OpenWeights, true
}

// HasOpenWeights returns a boolean if a field has been set.
func (o *ModelPrice) HasOpenWeights() bool {
	if o != nil && !IsNil(o.OpenWeights) {
		return true
	}

	return false
}

// SetOpenWeights gets a reference to the given bool and assigns it to the OpenWeights field.
func (o *ModelPrice) SetOpenWeights(v bool) {
	o.OpenWeights = &v
}

// GetOutputLimit returns the OutputLimit field value if set, zero value otherwise.
func (o *ModelPrice) GetOutputLimit() int32 {
	if o == nil || IsNil(o.OutputLimit) {
		var ret int32
		return ret
	}
	return *o.OutputLimit
}

// GetOutputLimitOk returns a tuple with the OutputLimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelPrice) GetOutputLimitOk() (*int32, bool) {
	if o == nil || IsNil(o.OutputLimit) {
		return nil, false
	}
	return o.OutputLimit, true
}

// HasOutputLimit returns a boolean if a field has been set.
func (o *ModelPrice) HasOutputLimit() bool {
	if o != nil && !IsNil(o.OutputLimit) {
		return true
	}

	return false
}

// SetOutputLimit gets a reference to the given int32 and assigns it to the OutputLimit field.
func (o *ModelPrice) SetOutputLimit(v int32) {
	o.OutputLimit = &v
}

// GetProvider returns the Provider field value if set, zero value otherwise.
func (o *ModelPrice) GetProvider() string {
	if o == nil || IsNil(o.Provider) {
		var ret string
		return ret
	}
	return *o.Provider
}

// GetProviderOk returns a tuple with the Provider field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelPrice) GetProviderOk() (*string, bool) {
	if o == nil || IsNil(o.Provider) {
		return nil, false
	}
	return o.Provider, true
}

// HasProvider returns a boolean if a field has been set.
func (o *ModelPrice) HasProvider() bool {
	if o != nil && !IsNil(o.Provider) {
		return true
	}

	return false
}

// SetProvider gets a reference to the given string and assigns it to the Provider field.
func (o *ModelPrice) SetProvider(v string) {
	o.Provider = &v
}

// GetPublisher returns the Publisher field value if set, zero value otherwise.
func (o *ModelPrice) GetPublisher() string {
	if o == nil || IsNil(o.Publisher) {
		var ret string
		return ret
	}
	return *o.Publisher
}

// GetPublisherOk returns a tuple with the Publisher field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelPrice) GetPublisherOk() (*string, bool) {
	if o == nil || IsNil(o.Publisher) {
		return nil, false
	}
	return o.Publisher, true
}

// HasPublisher returns a boolean if a field has been set.
func (o *ModelPrice) HasPublisher() bool {
	if o != nil && !IsNil(o.Publisher) {
		return true
	}

	return false
}

// SetPublisher gets a reference to the given string and assigns it to the Publisher field.
func (o *ModelPrice) SetPublisher(v string) {
	o.Publisher = &v
}

// GetRawPricingData returns the RawPricingData field value if set, zero value otherwise.
func (o *ModelPrice) GetRawPricingData() map[string]interface{} {
	if o == nil || IsNil(o.RawPricingData) {
		var ret map[string]interface{}
		return ret
	}
	return o.RawPricingData
}

// GetRawPricingDataOk returns a tuple with the RawPricingData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelPrice) GetRawPricingDataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.RawPricingData) {
		return map[string]interface{}{}, false
	}
	return o.RawPricingData, true
}

// HasRawPricingData returns a boolean if a field has been set.
func (o *ModelPrice) HasRawPricingData() bool {
	if o != nil && !IsNil(o.RawPricingData) {
		return true
	}

	return false
}

// SetRawPricingData gets a reference to the given map[string]interface{} and assigns it to the RawPricingData field.
func (o *ModelPrice) SetRawPricingData(v map[string]interface{}) {
	o.RawPricingData = v
}

// GetReasoning returns the Reasoning field value if set, zero value otherwise.
func (o *ModelPrice) GetReasoning() bool {
	if o == nil || IsNil(o.Reasoning) {
		var ret bool
		return ret
	}
	return *o.Reasoning
}

// GetReasoningOk returns a tuple with the Reasoning field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelPrice) GetReasoningOk() (*bool, bool) {
	if o == nil || IsNil(o.Reasoning) {
		return nil, false
	}
	return o.Reasoning, true
}

// HasReasoning returns a boolean if a field has been set.
func (o *ModelPrice) HasReasoning() bool {
	if o != nil && !IsNil(o.Reasoning) {
		return true
	}

	return false
}

// SetReasoning gets a reference to the given bool and assigns it to the Reasoning field.
func (o *ModelPrice) SetReasoning(v bool) {
	o.Reasoning = &v
}

// GetRegion returns the Region field value if set, zero value otherwise.
func (o *ModelPrice) GetRegion() string {
	if o == nil || IsNil(o.Region) {
		var ret string
		return ret
	}
	return *o.Region
}

// GetRegionOk returns a tuple with the Region field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelPrice) GetRegionOk() (*string, bool) {
	if o == nil || IsNil(o.Region) {
		return nil, false
	}
	return o.Region, true
}

// HasRegion returns a boolean if a field has been set.
func (o *ModelPrice) HasRegion() bool {
	if o != nil && !IsNil(o.Region) {
		return true
	}

	return false
}

// SetRegion gets a reference to the given string and assigns it to the Region field.
func (o *ModelPrice) SetRegion(v string) {
	o.Region = &v
}

// GetSkuPriceId returns the SkuPriceId field value if set, zero value otherwise.
func (o *ModelPrice) GetSkuPriceId() string {
	if o == nil || IsNil(o.SkuPriceId) {
		var ret string
		return ret
	}
	return *o.SkuPriceId
}

// GetSkuPriceIdOk returns a tuple with the SkuPriceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelPrice) GetSkuPriceIdOk() (*string, bool) {
	if o == nil || IsNil(o.SkuPriceId) {
		return nil, false
	}
	return o.SkuPriceId, true
}

// HasSkuPriceId returns a boolean if a field has been set.
func (o *ModelPrice) HasSkuPriceId() bool {
	if o != nil && !IsNil(o.SkuPriceId) {
		return true
	}

	return false
}

// SetSkuPriceId gets a reference to the given string and assigns it to the SkuPriceId field.
func (o *ModelPrice) SetSkuPriceId(v string) {
	o.SkuPriceId = &v
}

// GetSource returns the Source field value if set, zero value otherwise.
func (o *ModelPrice) GetSource() string {
	if o == nil || IsNil(o.Source) {
		var ret string
		return ret
	}
	return *o.Source
}

// GetSourceOk returns a tuple with the Source field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelPrice) GetSourceOk() (*string, bool) {
	if o == nil || IsNil(o.Source) {
		return nil, false
	}
	return o.Source, true
}

// HasSource returns a boolean if a field has been set.
func (o *ModelPrice) HasSource() bool {
	if o != nil && !IsNil(o.Source) {
		return true
	}

	return false
}

// SetSource gets a reference to the given string and assigns it to the Source field.
func (o *ModelPrice) SetSource(v string) {
	o.Source = &v
}

// GetSourceUrl returns the SourceUrl field value if set, zero value otherwise.
func (o *ModelPrice) GetSourceUrl() string {
	if o == nil || IsNil(o.SourceUrl) {
		var ret string
		return ret
	}
	return *o.SourceUrl
}

// GetSourceUrlOk returns a tuple with the SourceUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelPrice) GetSourceUrlOk() (*string, bool) {
	if o == nil || IsNil(o.SourceUrl) {
		return nil, false
	}
	return o.SourceUrl, true
}

// HasSourceUrl returns a boolean if a field has been set.
func (o *ModelPrice) HasSourceUrl() bool {
	if o != nil && !IsNil(o.SourceUrl) {
		return true
	}

	return false
}

// SetSourceUrl gets a reference to the given string and assigns it to the SourceUrl field.
func (o *ModelPrice) SetSourceUrl(v string) {
	o.SourceUrl = &v
}

// GetStructuredOutput returns the StructuredOutput field value if set, zero value otherwise.
func (o *ModelPrice) GetStructuredOutput() bool {
	if o == nil || IsNil(o.StructuredOutput) {
		var ret bool
		return ret
	}
	return *o.StructuredOutput
}

// GetStructuredOutputOk returns a tuple with the StructuredOutput field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelPrice) GetStructuredOutputOk() (*bool, bool) {
	if o == nil || IsNil(o.StructuredOutput) {
		return nil, false
	}
	return o.StructuredOutput, true
}

// HasStructuredOutput returns a boolean if a field has been set.
func (o *ModelPrice) HasStructuredOutput() bool {
	if o != nil && !IsNil(o.StructuredOutput) {
		return true
	}

	return false
}

// SetStructuredOutput gets a reference to the given bool and assigns it to the StructuredOutput field.
func (o *ModelPrice) SetStructuredOutput(v bool) {
	o.StructuredOutput = &v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *ModelPrice) GetTags() map[string]interface{} {
	if o == nil || IsNil(o.Tags) {
		var ret map[string]interface{}
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelPrice) GetTagsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Tags) {
		return map[string]interface{}{}, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *ModelPrice) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given map[string]interface{} and assigns it to the Tags field.
func (o *ModelPrice) SetTags(v map[string]interface{}) {
	o.Tags = v
}

// GetTokenBucket returns the TokenBucket field value if set, zero value otherwise.
func (o *ModelPrice) GetTokenBucket() string {
	if o == nil || IsNil(o.TokenBucket) {
		var ret string
		return ret
	}
	return *o.TokenBucket
}

// GetTokenBucketOk returns a tuple with the TokenBucket field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelPrice) GetTokenBucketOk() (*string, bool) {
	if o == nil || IsNil(o.TokenBucket) {
		return nil, false
	}
	return o.TokenBucket, true
}

// HasTokenBucket returns a boolean if a field has been set.
func (o *ModelPrice) HasTokenBucket() bool {
	if o != nil && !IsNil(o.TokenBucket) {
		return true
	}

	return false
}

// SetTokenBucket gets a reference to the given string and assigns it to the TokenBucket field.
func (o *ModelPrice) SetTokenBucket(v string) {
	o.TokenBucket = &v
}

// GetToolCall returns the ToolCall field value if set, zero value otherwise.
func (o *ModelPrice) GetToolCall() bool {
	if o == nil || IsNil(o.ToolCall) {
		var ret bool
		return ret
	}
	return *o.ToolCall
}

// GetToolCallOk returns a tuple with the ToolCall field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelPrice) GetToolCallOk() (*bool, bool) {
	if o == nil || IsNil(o.ToolCall) {
		return nil, false
	}
	return o.ToolCall, true
}

// HasToolCall returns a boolean if a field has been set.
func (o *ModelPrice) HasToolCall() bool {
	if o != nil && !IsNil(o.ToolCall) {
		return true
	}

	return false
}

// SetToolCall gets a reference to the given bool and assigns it to the ToolCall field.
func (o *ModelPrice) SetToolCall(v bool) {
	o.ToolCall = &v
}

// GetUnitPricePerMtok returns the UnitPricePerMtok field value if set, zero value otherwise.
func (o *ModelPrice) GetUnitPricePerMtok() float32 {
	if o == nil || IsNil(o.UnitPricePerMtok) {
		var ret float32
		return ret
	}
	return *o.UnitPricePerMtok
}

// GetUnitPricePerMtokOk returns a tuple with the UnitPricePerMtok field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelPrice) GetUnitPricePerMtokOk() (*float32, bool) {
	if o == nil || IsNil(o.UnitPricePerMtok) {
		return nil, false
	}
	return o.UnitPricePerMtok, true
}

// HasUnitPricePerMtok returns a boolean if a field has been set.
func (o *ModelPrice) HasUnitPricePerMtok() bool {
	if o != nil && !IsNil(o.UnitPricePerMtok) {
		return true
	}

	return false
}

// SetUnitPricePerMtok gets a reference to the given float32 and assigns it to the UnitPricePerMtok field.
func (o *ModelPrice) SetUnitPricePerMtok(v float32) {
	o.UnitPricePerMtok = &v
}

func (o ModelPrice) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelPrice) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ContextLimit) {
		toSerialize["context_limit"] = o.ContextLimit
	}
	if !IsNil(o.Currency) {
		toSerialize["currency"] = o.Currency
	}
	if !IsNil(o.EffectiveFrom) {
		toSerialize["effective_from"] = o.EffectiveFrom
	}
	if !IsNil(o.EffectiveTo) {
		toSerialize["effective_to"] = o.EffectiveTo
	}
	if !IsNil(o.FetchedAt) {
		toSerialize["fetched_at"] = o.FetchedAt
	}
	if !IsNil(o.Host) {
		toSerialize["host"] = o.Host
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.ModalitiesInput) {
		toSerialize["modalities_input"] = o.ModalitiesInput
	}
	if !IsNil(o.ModalitiesOutput) {
		toSerialize["modalities_output"] = o.ModalitiesOutput
	}
	if !IsNil(o.Model) {
		toSerialize["model"] = o.Model
	}
	if !IsNil(o.ModelId) {
		toSerialize["model_id"] = o.ModelId
	}
	if !IsNil(o.OpenWeights) {
		toSerialize["open_weights"] = o.OpenWeights
	}
	if !IsNil(o.OutputLimit) {
		toSerialize["output_limit"] = o.OutputLimit
	}
	if !IsNil(o.Provider) {
		toSerialize["provider"] = o.Provider
	}
	if !IsNil(o.Publisher) {
		toSerialize["publisher"] = o.Publisher
	}
	if !IsNil(o.RawPricingData) {
		toSerialize["raw_pricing_data"] = o.RawPricingData
	}
	if !IsNil(o.Reasoning) {
		toSerialize["reasoning"] = o.Reasoning
	}
	if !IsNil(o.Region) {
		toSerialize["region"] = o.Region
	}
	if !IsNil(o.SkuPriceId) {
		toSerialize["sku_price_id"] = o.SkuPriceId
	}
	if !IsNil(o.Source) {
		toSerialize["source"] = o.Source
	}
	if !IsNil(o.SourceUrl) {
		toSerialize["source_url"] = o.SourceUrl
	}
	if !IsNil(o.StructuredOutput) {
		toSerialize["structured_output"] = o.StructuredOutput
	}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	if !IsNil(o.TokenBucket) {
		toSerialize["token_bucket"] = o.TokenBucket
	}
	if !IsNil(o.ToolCall) {
		toSerialize["tool_call"] = o.ToolCall
	}
	if !IsNil(o.UnitPricePerMtok) {
		toSerialize["unit_price_per_mtok"] = o.UnitPricePerMtok
	}
	return toSerialize, nil
}

type NullableModelPrice struct {
	value *ModelPrice
	isSet bool
}

func (v NullableModelPrice) Get() *ModelPrice {
	return v.value
}

func (v *NullableModelPrice) Set(val *ModelPrice) {
	v.value = val
	v.isSet = true
}

func (v NullableModelPrice) IsSet() bool {
	return v.isSet
}

func (v *NullableModelPrice) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelPrice(val *ModelPrice) *NullableModelPrice {
	return &NullableModelPrice{value: val, isSet: true}
}

func (v NullableModelPrice) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelPrice) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
