/*
Pricing API

Provides API level access to the Costgraph Services.

API version: 1.0
Contact: support@costgraph.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pricing_api_client

import (
	"encoding/json"
	"fmt"
)

// TypesService the model 'TypesService'
type TypesService string

// List of types.Service
const (
	ComputeEngine               TypesService = "ComputeEngine"
	AmazonEC2                   TypesService = "AmazonEC2"
	Droplet                     TypesService = "Droplet"
	AzureCompute                TypesService = "AzureCompute"
	AzureManagedDisks           TypesService = "AzureManagedDisks"
	HetznerCompute              TypesService = "HetznerCompute"
	OVHPublicCloud              TypesService = "OVHPublicCloud"
	BaseCompute                 TypesService = "BaseCompute"
	BaseDisks                   TypesService = "BaseDisks"
	AmazonEBS                   TypesService = "AmazonEBS"
	AmazonRDS                   TypesService = "AmazonRDS"
	AuroraDSQL                  TypesService = "AuroraDSQL"
	CloudSQL                    TypesService = "CloudSQL"
	AlloyDB                     TypesService = "AlloyDB"
	CloudSpanner                TypesService = "CloudSpanner"
	AzureDatabaseForPostgreSQL  TypesService = "AzureDatabaseForPostgreSQL"
	AzureDatabaseForMySQL       TypesService = "AzureDatabaseForMySQL"
	AzureSQLDatabase            TypesService = "AzureSQLDatabase"
	AzureSQLManagedInstance     TypesService = "AzureSQLManagedInstance"
	PlanetScaleDB               TypesService = "PlanetScale"
	ComputeEnginePersistentDisk TypesService = "ComputeEnginePersistentDisk"
	STACKITCompute              TypesService = "STACKITCompute"
	STACKITBlockStorage         TypesService = "STACKITBlockStorage"
	STACKITDatabase             TypesService = "STACKITDatabase"
	AkamaiLinode                TypesService = "AkamaiLinode"
	AkamaiBlockStorage          TypesService = "AkamaiBlockStorage"
	AkamaiDatabase              TypesService = "AkamaiDatabase"
)

// All allowed values of TypesService enum
var AllowedTypesServiceEnumValues = []TypesService{
	"ComputeEngine",
	"AmazonEC2",
	"Droplet",
	"AzureCompute",
	"AzureManagedDisks",
	"HetznerCompute",
	"OVHPublicCloud",
	"BaseCompute",
	"BaseDisks",
	"AmazonEBS",
	"AmazonRDS",
	"AuroraDSQL",
	"CloudSQL",
	"AlloyDB",
	"CloudSpanner",
	"AzureDatabaseForPostgreSQL",
	"AzureDatabaseForMySQL",
	"AzureSQLDatabase",
	"AzureSQLManagedInstance",
	"PlanetScale",
	"ComputeEnginePersistentDisk",
	"STACKITCompute",
	"STACKITBlockStorage",
	"STACKITDatabase",
	"AkamaiLinode",
	"AkamaiBlockStorage",
	"AkamaiDatabase",
}

func (v *TypesService) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := TypesService(value)
	for _, existing := range AllowedTypesServiceEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid TypesService", value)
}

// NewTypesServiceFromValue returns a pointer to a valid TypesService
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewTypesServiceFromValue(v string) (*TypesService, error) {
	ev := TypesService(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for TypesService: valid values are %v", v, AllowedTypesServiceEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v TypesService) IsValid() bool {
	for _, existing := range AllowedTypesServiceEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to types.Service value
func (v TypesService) Ptr() *TypesService {
	return &v
}

type NullableTypesService struct {
	value *TypesService
	isSet bool
}

func (v NullableTypesService) Get() *TypesService {
	return v.value
}

func (v *NullableTypesService) Set(val *TypesService) {
	v.value = val
	v.isSet = true
}

func (v NullableTypesService) IsSet() bool {
	return v.isSet
}

func (v *NullableTypesService) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTypesService(val *TypesService) *NullableTypesService {
	return &NullableTypesService{value: val, isSet: true}
}

func (v NullableTypesService) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTypesService) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
