/*
Pricing API

Provides API level access to the Costgraph Services.

API version: 1.0
Contact: support@costgraph.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pricing_api_client

import (
	"encoding/json"
)

// checks if the PublishedComputePrices type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PublishedComputePrices{}

// PublishedComputePrices struct for PublishedComputePrices
type PublishedComputePrices struct {
	Data []ComputePrice `json:"data,omitempty"`
}

// NewPublishedComputePrices instantiates a new PublishedComputePrices object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPublishedComputePrices() *PublishedComputePrices {
	this := PublishedComputePrices{}
	return &this
}

// NewPublishedComputePricesWithDefaults instantiates a new PublishedComputePrices object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPublishedComputePricesWithDefaults() *PublishedComputePrices {
	this := PublishedComputePrices{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *PublishedComputePrices) GetData() []ComputePrice {
	if o == nil || IsNil(o.Data) {
		var ret []ComputePrice
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PublishedComputePrices) GetDataOk() ([]ComputePrice, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *PublishedComputePrices) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []ComputePrice and assigns it to the Data field.
func (o *PublishedComputePrices) SetData(v []ComputePrice) {
	o.Data = v
}

func (o PublishedComputePrices) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PublishedComputePrices) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullablePublishedComputePrices struct {
	value *PublishedComputePrices
	isSet bool
}

func (v NullablePublishedComputePrices) Get() *PublishedComputePrices {
	return v.value
}

func (v *NullablePublishedComputePrices) Set(val *PublishedComputePrices) {
	v.value = val
	v.isSet = true
}

func (v NullablePublishedComputePrices) IsSet() bool {
	return v.isSet
}

func (v *NullablePublishedComputePrices) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePublishedComputePrices(val *PublishedComputePrices) *NullablePublishedComputePrices {
	return &NullablePublishedComputePrices{value: val, isSet: true}
}

func (v NullablePublishedComputePrices) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePublishedComputePrices) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
