/*
Pricing API

Provides API level access to the Costgraph Services.

API version: 1.0
Contact: contact@baselinehq.cloud
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pricing_api_client

import (
	"encoding/json"
)

// checks if the TypesComputeRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TypesComputeRequest{}

// TypesComputeRequest struct for TypesComputeRequest
type TypesComputeRequest struct {
	IncludeMetadata *bool `json:"include_metadata,omitempty"`
	Instance *GithubComBaselinehqGolangSharedTypesInstance `json:"instance,omitempty"`
	Predicates *TypesPredicates `json:"predicates,omitempty"`
	Usage *GithubComBaselinehqGolangSharedTypesVM `json:"usage,omitempty"`
}

// NewTypesComputeRequest instantiates a new TypesComputeRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTypesComputeRequest() *TypesComputeRequest {
	this := TypesComputeRequest{}
	return &this
}

// NewTypesComputeRequestWithDefaults instantiates a new TypesComputeRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTypesComputeRequestWithDefaults() *TypesComputeRequest {
	this := TypesComputeRequest{}
	return &this
}

// GetIncludeMetadata returns the IncludeMetadata field value if set, zero value otherwise.
func (o *TypesComputeRequest) GetIncludeMetadata() bool {
	if o == nil || IsNil(o.IncludeMetadata) {
		var ret bool
		return ret
	}
	return *o.IncludeMetadata
}

// GetIncludeMetadataOk returns a tuple with the IncludeMetadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TypesComputeRequest) GetIncludeMetadataOk() (*bool, bool) {
	if o == nil || IsNil(o.IncludeMetadata) {
		return nil, false
	}
	return o.IncludeMetadata, true
}

// HasIncludeMetadata returns a boolean if a field has been set.
func (o *TypesComputeRequest) HasIncludeMetadata() bool {
	if o != nil && !IsNil(o.IncludeMetadata) {
		return true
	}

	return false
}

// SetIncludeMetadata gets a reference to the given bool and assigns it to the IncludeMetadata field.
func (o *TypesComputeRequest) SetIncludeMetadata(v bool) {
	o.IncludeMetadata = &v
}

// GetInstance returns the Instance field value if set, zero value otherwise.
func (o *TypesComputeRequest) GetInstance() GithubComBaselinehqGolangSharedTypesInstance {
	if o == nil || IsNil(o.Instance) {
		var ret GithubComBaselinehqGolangSharedTypesInstance
		return ret
	}
	return *o.Instance
}

// GetInstanceOk returns a tuple with the Instance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TypesComputeRequest) GetInstanceOk() (*GithubComBaselinehqGolangSharedTypesInstance, bool) {
	if o == nil || IsNil(o.Instance) {
		return nil, false
	}
	return o.Instance, true
}

// HasInstance returns a boolean if a field has been set.
func (o *TypesComputeRequest) HasInstance() bool {
	if o != nil && !IsNil(o.Instance) {
		return true
	}

	return false
}

// SetInstance gets a reference to the given GithubComBaselinehqGolangSharedTypesInstance and assigns it to the Instance field.
func (o *TypesComputeRequest) SetInstance(v GithubComBaselinehqGolangSharedTypesInstance) {
	o.Instance = &v
}

// GetPredicates returns the Predicates field value if set, zero value otherwise.
func (o *TypesComputeRequest) GetPredicates() TypesPredicates {
	if o == nil || IsNil(o.Predicates) {
		var ret TypesPredicates
		return ret
	}
	return *o.Predicates
}

// GetPredicatesOk returns a tuple with the Predicates field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TypesComputeRequest) GetPredicatesOk() (*TypesPredicates, bool) {
	if o == nil || IsNil(o.Predicates) {
		return nil, false
	}
	return o.Predicates, true
}

// HasPredicates returns a boolean if a field has been set.
func (o *TypesComputeRequest) HasPredicates() bool {
	if o != nil && !IsNil(o.Predicates) {
		return true
	}

	return false
}

// SetPredicates gets a reference to the given TypesPredicates and assigns it to the Predicates field.
func (o *TypesComputeRequest) SetPredicates(v TypesPredicates) {
	o.Predicates = &v
}

// GetUsage returns the Usage field value if set, zero value otherwise.
func (o *TypesComputeRequest) GetUsage() GithubComBaselinehqGolangSharedTypesVM {
	if o == nil || IsNil(o.Usage) {
		var ret GithubComBaselinehqGolangSharedTypesVM
		return ret
	}
	return *o.Usage
}

// GetUsageOk returns a tuple with the Usage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TypesComputeRequest) GetUsageOk() (*GithubComBaselinehqGolangSharedTypesVM, bool) {
	if o == nil || IsNil(o.Usage) {
		return nil, false
	}
	return o.Usage, true
}

// HasUsage returns a boolean if a field has been set.
func (o *TypesComputeRequest) HasUsage() bool {
	if o != nil && !IsNil(o.Usage) {
		return true
	}

	return false
}

// SetUsage gets a reference to the given GithubComBaselinehqGolangSharedTypesVM and assigns it to the Usage field.
func (o *TypesComputeRequest) SetUsage(v GithubComBaselinehqGolangSharedTypesVM) {
	o.Usage = &v
}

func (o TypesComputeRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TypesComputeRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.IncludeMetadata) {
		toSerialize["include_metadata"] = o.IncludeMetadata
	}
	if !IsNil(o.Instance) {
		toSerialize["instance"] = o.Instance
	}
	if !IsNil(o.Predicates) {
		toSerialize["predicates"] = o.Predicates
	}
	if !IsNil(o.Usage) {
		toSerialize["usage"] = o.Usage
	}
	return toSerialize, nil
}

type NullableTypesComputeRequest struct {
	value *TypesComputeRequest
	isSet bool
}

func (v NullableTypesComputeRequest) Get() *TypesComputeRequest {
	return v.value
}

func (v *NullableTypesComputeRequest) Set(val *TypesComputeRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableTypesComputeRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableTypesComputeRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTypesComputeRequest(val *TypesComputeRequest) *NullableTypesComputeRequest {
	return &NullableTypesComputeRequest{value: val, isSet: true}
}

func (v NullableTypesComputeRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTypesComputeRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


