/*
Pricing API

Provides API level access to the Costgraph Services.

API version: 1.0
Contact: support@costgraph.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pricing_api_client

import (
	"encoding/json"
)

// checks if the PublishedDiskPrices type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PublishedDiskPrices{}

// PublishedDiskPrices struct for PublishedDiskPrices
type PublishedDiskPrices struct {
	Data []DiskPrice `json:"data,omitempty"`
}

// NewPublishedDiskPrices instantiates a new PublishedDiskPrices object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPublishedDiskPrices() *PublishedDiskPrices {
	this := PublishedDiskPrices{}
	return &this
}

// NewPublishedDiskPricesWithDefaults instantiates a new PublishedDiskPrices object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPublishedDiskPricesWithDefaults() *PublishedDiskPrices {
	this := PublishedDiskPrices{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *PublishedDiskPrices) GetData() []DiskPrice {
	if o == nil || IsNil(o.Data) {
		var ret []DiskPrice
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PublishedDiskPrices) GetDataOk() ([]DiskPrice, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *PublishedDiskPrices) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []DiskPrice and assigns it to the Data field.
func (o *PublishedDiskPrices) SetData(v []DiskPrice) {
	o.Data = v
}

func (o PublishedDiskPrices) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PublishedDiskPrices) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullablePublishedDiskPrices struct {
	value *PublishedDiskPrices
	isSet bool
}

func (v NullablePublishedDiskPrices) Get() *PublishedDiskPrices {
	return v.value
}

func (v *NullablePublishedDiskPrices) Set(val *PublishedDiskPrices) {
	v.value = val
	v.isSet = true
}

func (v NullablePublishedDiskPrices) IsSet() bool {
	return v.isSet
}

func (v *NullablePublishedDiskPrices) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePublishedDiskPrices(val *PublishedDiskPrices) *NullablePublishedDiskPrices {
	return &NullablePublishedDiskPrices{value: val, isSet: true}
}

func (v NullablePublishedDiskPrices) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePublishedDiskPrices) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
