/*
Pricing API

Provides API level access to the Costgraph Services.

API version: 1.0
Contact: support@costgraph.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pricing_api_client

import (
	"encoding/json"
)

// checks if the PublishedModelPrices type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PublishedModelPrices{}

// PublishedModelPrices struct for PublishedModelPrices
type PublishedModelPrices struct {
	Data []ModelPrice `json:"data,omitempty"`
}

// NewPublishedModelPrices instantiates a new PublishedModelPrices object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPublishedModelPrices() *PublishedModelPrices {
	this := PublishedModelPrices{}
	return &this
}

// NewPublishedModelPricesWithDefaults instantiates a new PublishedModelPrices object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPublishedModelPricesWithDefaults() *PublishedModelPrices {
	this := PublishedModelPrices{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *PublishedModelPrices) GetData() []ModelPrice {
	if o == nil || IsNil(o.Data) {
		var ret []ModelPrice
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PublishedModelPrices) GetDataOk() ([]ModelPrice, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *PublishedModelPrices) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []ModelPrice and assigns it to the Data field.
func (o *PublishedModelPrices) SetData(v []ModelPrice) {
	o.Data = v
}

func (o PublishedModelPrices) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PublishedModelPrices) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullablePublishedModelPrices struct {
	value *PublishedModelPrices
	isSet bool
}

func (v NullablePublishedModelPrices) Get() *PublishedModelPrices {
	return v.value
}

func (v *NullablePublishedModelPrices) Set(val *PublishedModelPrices) {
	v.value = val
	v.isSet = true
}

func (v NullablePublishedModelPrices) IsSet() bool {
	return v.isSet
}

func (v *NullablePublishedModelPrices) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePublishedModelPrices(val *PublishedModelPrices) *NullablePublishedModelPrices {
	return &NullablePublishedModelPrices{value: val, isSet: true}
}

func (v NullablePublishedModelPrices) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePublishedModelPrices) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
