/*
Pricing API

Provides API level access to the Costgraph Services.

API version: 1.0
Contact: support@costgraph.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pricing_api_client

import (
	"encoding/json"
)

// checks if the DiskPriceList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DiskPriceList{}

// DiskPriceList struct for DiskPriceList
type DiskPriceList struct {
	Providers []DiskPrice `json:"providers,omitempty"`
}

// NewDiskPriceList instantiates a new DiskPriceList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDiskPriceList() *DiskPriceList {
	this := DiskPriceList{}
	return &this
}

// NewDiskPriceListWithDefaults instantiates a new DiskPriceList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDiskPriceListWithDefaults() *DiskPriceList {
	this := DiskPriceList{}
	return &this
}

// GetProviders returns the Providers field value if set, zero value otherwise.
func (o *DiskPriceList) GetProviders() []DiskPrice {
	if o == nil || IsNil(o.Providers) {
		var ret []DiskPrice
		return ret
	}
	return o.Providers
}

// GetProvidersOk returns a tuple with the Providers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DiskPriceList) GetProvidersOk() ([]DiskPrice, bool) {
	if o == nil || IsNil(o.Providers) {
		return nil, false
	}
	return o.Providers, true
}

// HasProviders returns a boolean if a field has been set.
func (o *DiskPriceList) HasProviders() bool {
	if o != nil && !IsNil(o.Providers) {
		return true
	}

	return false
}

// SetProviders gets a reference to the given []DiskPrice and assigns it to the Providers field.
func (o *DiskPriceList) SetProviders(v []DiskPrice) {
	o.Providers = v
}

func (o DiskPriceList) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DiskPriceList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Providers) {
		toSerialize["providers"] = o.Providers
	}
	return toSerialize, nil
}

type NullableDiskPriceList struct {
	value *DiskPriceList
	isSet bool
}

func (v NullableDiskPriceList) Get() *DiskPriceList {
	return v.value
}

func (v *NullableDiskPriceList) Set(val *DiskPriceList) {
	v.value = val
	v.isSet = true
}

func (v NullableDiskPriceList) IsSet() bool {
	return v.isSet
}

func (v *NullableDiskPriceList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDiskPriceList(val *DiskPriceList) *NullableDiskPriceList {
	return &NullableDiskPriceList{value: val, isSet: true}
}

func (v NullableDiskPriceList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDiskPriceList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
