/*
Pricing API

Provides API level access to the Costgraph Services.

API version: 1.0
Contact: contact@baselinehq.cloud
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pricing_api_client

import (
	"encoding/json"
)

// checks if the TypesCustomDiskPricingResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TypesCustomDiskPricingResponse{}

// TypesCustomDiskPricingResponse struct for TypesCustomDiskPricingResponse
type TypesCustomDiskPricingResponse struct {
	Entries []SchemaDiskPricingsRow                      `json:"entries,omitempty"`
	Status  *GithubComBaselinehqPricingapiPkgTypesStatus `json:"status,omitempty"`
}

// NewTypesCustomDiskPricingResponse instantiates a new TypesCustomDiskPricingResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTypesCustomDiskPricingResponse() *TypesCustomDiskPricingResponse {
	this := TypesCustomDiskPricingResponse{}
	return &this
}

// NewTypesCustomDiskPricingResponseWithDefaults instantiates a new TypesCustomDiskPricingResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTypesCustomDiskPricingResponseWithDefaults() *TypesCustomDiskPricingResponse {
	this := TypesCustomDiskPricingResponse{}
	return &this
}

// GetEntries returns the Entries field value if set, zero value otherwise.
func (o *TypesCustomDiskPricingResponse) GetEntries() []SchemaDiskPricingsRow {
	if o == nil || IsNil(o.Entries) {
		var ret []SchemaDiskPricingsRow
		return ret
	}
	return o.Entries
}

// GetEntriesOk returns a tuple with the Entries field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TypesCustomDiskPricingResponse) GetEntriesOk() ([]SchemaDiskPricingsRow, bool) {
	if o == nil || IsNil(o.Entries) {
		return nil, false
	}
	return o.Entries, true
}

// HasEntries returns a boolean if a field has been set.
func (o *TypesCustomDiskPricingResponse) HasEntries() bool {
	if o != nil && !IsNil(o.Entries) {
		return true
	}

	return false
}

// SetEntries gets a reference to the given []SchemaDiskPricingsRow and assigns it to the Entries field.
func (o *TypesCustomDiskPricingResponse) SetEntries(v []SchemaDiskPricingsRow) {
	o.Entries = v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *TypesCustomDiskPricingResponse) GetStatus() GithubComBaselinehqPricingapiPkgTypesStatus {
	if o == nil || IsNil(o.Status) {
		var ret GithubComBaselinehqPricingapiPkgTypesStatus
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TypesCustomDiskPricingResponse) GetStatusOk() (*GithubComBaselinehqPricingapiPkgTypesStatus, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *TypesCustomDiskPricingResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given GithubComBaselinehqPricingapiPkgTypesStatus and assigns it to the Status field.
func (o *TypesCustomDiskPricingResponse) SetStatus(v GithubComBaselinehqPricingapiPkgTypesStatus) {
	o.Status = &v
}

func (o TypesCustomDiskPricingResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TypesCustomDiskPricingResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Entries) {
		toSerialize["entries"] = o.Entries
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableTypesCustomDiskPricingResponse struct {
	value *TypesCustomDiskPricingResponse
	isSet bool
}

func (v NullableTypesCustomDiskPricingResponse) Get() *TypesCustomDiskPricingResponse {
	return v.value
}

func (v *NullableTypesCustomDiskPricingResponse) Set(val *TypesCustomDiskPricingResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableTypesCustomDiskPricingResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableTypesCustomDiskPricingResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTypesCustomDiskPricingResponse(val *TypesCustomDiskPricingResponse) *NullableTypesCustomDiskPricingResponse {
	return &NullableTypesCustomDiskPricingResponse{value: val, isSet: true}
}

func (v NullableTypesCustomDiskPricingResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTypesCustomDiskPricingResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
