/*
Pricing API

Provides API level access to the Costgraph Services.

API version: 1.0
Contact: contact@baselinehq.cloud
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pricing_api_client

import (
	"encoding/json"
)

// checks if the GithubComBaselinehqGolangSharedTypesInstance type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GithubComBaselinehqGolangSharedTypesInstance{}

// GithubComBaselinehqGolangSharedTypesInstance struct for GithubComBaselinehqGolangSharedTypesInstance
type GithubComBaselinehqGolangSharedTypesInstance struct {
	AvailabilityZone *string `json:"availability_zone,omitempty"`
	Id *string `json:"id,omitempty"`
	InstanceType *string `json:"instance_type,omitempty"`
	OperatingSystem *string `json:"operating_system,omitempty"`
	Provider *GithubComBaselinehqGolangSharedTypesProvider `json:"provider,omitempty"`
	Region *string `json:"region,omitempty"`
	Service *GithubComBaselinehqGolangSharedTypesService `json:"service,omitempty"`
	UsageType *GithubComBaselinehqGolangSharedTypesUsageType `json:"usage_type,omitempty"`
	Vm *GithubComBaselinehqGolangSharedTypesVM `json:"vm,omitempty"`
}

// NewGithubComBaselinehqGolangSharedTypesInstance instantiates a new GithubComBaselinehqGolangSharedTypesInstance object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGithubComBaselinehqGolangSharedTypesInstance() *GithubComBaselinehqGolangSharedTypesInstance {
	this := GithubComBaselinehqGolangSharedTypesInstance{}
	return &this
}

// NewGithubComBaselinehqGolangSharedTypesInstanceWithDefaults instantiates a new GithubComBaselinehqGolangSharedTypesInstance object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGithubComBaselinehqGolangSharedTypesInstanceWithDefaults() *GithubComBaselinehqGolangSharedTypesInstance {
	this := GithubComBaselinehqGolangSharedTypesInstance{}
	return &this
}

// GetAvailabilityZone returns the AvailabilityZone field value if set, zero value otherwise.
func (o *GithubComBaselinehqGolangSharedTypesInstance) GetAvailabilityZone() string {
	if o == nil || IsNil(o.AvailabilityZone) {
		var ret string
		return ret
	}
	return *o.AvailabilityZone
}

// GetAvailabilityZoneOk returns a tuple with the AvailabilityZone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GithubComBaselinehqGolangSharedTypesInstance) GetAvailabilityZoneOk() (*string, bool) {
	if o == nil || IsNil(o.AvailabilityZone) {
		return nil, false
	}
	return o.AvailabilityZone, true
}

// HasAvailabilityZone returns a boolean if a field has been set.
func (o *GithubComBaselinehqGolangSharedTypesInstance) HasAvailabilityZone() bool {
	if o != nil && !IsNil(o.AvailabilityZone) {
		return true
	}

	return false
}

// SetAvailabilityZone gets a reference to the given string and assigns it to the AvailabilityZone field.
func (o *GithubComBaselinehqGolangSharedTypesInstance) SetAvailabilityZone(v string) {
	o.AvailabilityZone = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *GithubComBaselinehqGolangSharedTypesInstance) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GithubComBaselinehqGolangSharedTypesInstance) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *GithubComBaselinehqGolangSharedTypesInstance) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *GithubComBaselinehqGolangSharedTypesInstance) SetId(v string) {
	o.Id = &v
}

// GetInstanceType returns the InstanceType field value if set, zero value otherwise.
func (o *GithubComBaselinehqGolangSharedTypesInstance) GetInstanceType() string {
	if o == nil || IsNil(o.InstanceType) {
		var ret string
		return ret
	}
	return *o.InstanceType
}

// GetInstanceTypeOk returns a tuple with the InstanceType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GithubComBaselinehqGolangSharedTypesInstance) GetInstanceTypeOk() (*string, bool) {
	if o == nil || IsNil(o.InstanceType) {
		return nil, false
	}
	return o.InstanceType, true
}

// HasInstanceType returns a boolean if a field has been set.
func (o *GithubComBaselinehqGolangSharedTypesInstance) HasInstanceType() bool {
	if o != nil && !IsNil(o.InstanceType) {
		return true
	}

	return false
}

// SetInstanceType gets a reference to the given string and assigns it to the InstanceType field.
func (o *GithubComBaselinehqGolangSharedTypesInstance) SetInstanceType(v string) {
	o.InstanceType = &v
}

// GetOperatingSystem returns the OperatingSystem field value if set, zero value otherwise.
func (o *GithubComBaselinehqGolangSharedTypesInstance) GetOperatingSystem() string {
	if o == nil || IsNil(o.OperatingSystem) {
		var ret string
		return ret
	}
	return *o.OperatingSystem
}

// GetOperatingSystemOk returns a tuple with the OperatingSystem field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GithubComBaselinehqGolangSharedTypesInstance) GetOperatingSystemOk() (*string, bool) {
	if o == nil || IsNil(o.OperatingSystem) {
		return nil, false
	}
	return o.OperatingSystem, true
}

// HasOperatingSystem returns a boolean if a field has been set.
func (o *GithubComBaselinehqGolangSharedTypesInstance) HasOperatingSystem() bool {
	if o != nil && !IsNil(o.OperatingSystem) {
		return true
	}

	return false
}

// SetOperatingSystem gets a reference to the given string and assigns it to the OperatingSystem field.
func (o *GithubComBaselinehqGolangSharedTypesInstance) SetOperatingSystem(v string) {
	o.OperatingSystem = &v
}

// GetProvider returns the Provider field value if set, zero value otherwise.
func (o *GithubComBaselinehqGolangSharedTypesInstance) GetProvider() GithubComBaselinehqGolangSharedTypesProvider {
	if o == nil || IsNil(o.Provider) {
		var ret GithubComBaselinehqGolangSharedTypesProvider
		return ret
	}
	return *o.Provider
}

// GetProviderOk returns a tuple with the Provider field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GithubComBaselinehqGolangSharedTypesInstance) GetProviderOk() (*GithubComBaselinehqGolangSharedTypesProvider, bool) {
	if o == nil || IsNil(o.Provider) {
		return nil, false
	}
	return o.Provider, true
}

// HasProvider returns a boolean if a field has been set.
func (o *GithubComBaselinehqGolangSharedTypesInstance) HasProvider() bool {
	if o != nil && !IsNil(o.Provider) {
		return true
	}

	return false
}

// SetProvider gets a reference to the given GithubComBaselinehqGolangSharedTypesProvider and assigns it to the Provider field.
func (o *GithubComBaselinehqGolangSharedTypesInstance) SetProvider(v GithubComBaselinehqGolangSharedTypesProvider) {
	o.Provider = &v
}

// GetRegion returns the Region field value if set, zero value otherwise.
func (o *GithubComBaselinehqGolangSharedTypesInstance) GetRegion() string {
	if o == nil || IsNil(o.Region) {
		var ret string
		return ret
	}
	return *o.Region
}

// GetRegionOk returns a tuple with the Region field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GithubComBaselinehqGolangSharedTypesInstance) GetRegionOk() (*string, bool) {
	if o == nil || IsNil(o.Region) {
		return nil, false
	}
	return o.Region, true
}

// HasRegion returns a boolean if a field has been set.
func (o *GithubComBaselinehqGolangSharedTypesInstance) HasRegion() bool {
	if o != nil && !IsNil(o.Region) {
		return true
	}

	return false
}

// SetRegion gets a reference to the given string and assigns it to the Region field.
func (o *GithubComBaselinehqGolangSharedTypesInstance) SetRegion(v string) {
	o.Region = &v
}

// GetService returns the Service field value if set, zero value otherwise.
func (o *GithubComBaselinehqGolangSharedTypesInstance) GetService() GithubComBaselinehqGolangSharedTypesService {
	if o == nil || IsNil(o.Service) {
		var ret GithubComBaselinehqGolangSharedTypesService
		return ret
	}
	return *o.Service
}

// GetServiceOk returns a tuple with the Service field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GithubComBaselinehqGolangSharedTypesInstance) GetServiceOk() (*GithubComBaselinehqGolangSharedTypesService, bool) {
	if o == nil || IsNil(o.Service) {
		return nil, false
	}
	return o.Service, true
}

// HasService returns a boolean if a field has been set.
func (o *GithubComBaselinehqGolangSharedTypesInstance) HasService() bool {
	if o != nil && !IsNil(o.Service) {
		return true
	}

	return false
}

// SetService gets a reference to the given GithubComBaselinehqGolangSharedTypesService and assigns it to the Service field.
func (o *GithubComBaselinehqGolangSharedTypesInstance) SetService(v GithubComBaselinehqGolangSharedTypesService) {
	o.Service = &v
}

// GetUsageType returns the UsageType field value if set, zero value otherwise.
func (o *GithubComBaselinehqGolangSharedTypesInstance) GetUsageType() GithubComBaselinehqGolangSharedTypesUsageType {
	if o == nil || IsNil(o.UsageType) {
		var ret GithubComBaselinehqGolangSharedTypesUsageType
		return ret
	}
	return *o.UsageType
}

// GetUsageTypeOk returns a tuple with the UsageType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GithubComBaselinehqGolangSharedTypesInstance) GetUsageTypeOk() (*GithubComBaselinehqGolangSharedTypesUsageType, bool) {
	if o == nil || IsNil(o.UsageType) {
		return nil, false
	}
	return o.UsageType, true
}

// HasUsageType returns a boolean if a field has been set.
func (o *GithubComBaselinehqGolangSharedTypesInstance) HasUsageType() bool {
	if o != nil && !IsNil(o.UsageType) {
		return true
	}

	return false
}

// SetUsageType gets a reference to the given GithubComBaselinehqGolangSharedTypesUsageType and assigns it to the UsageType field.
func (o *GithubComBaselinehqGolangSharedTypesInstance) SetUsageType(v GithubComBaselinehqGolangSharedTypesUsageType) {
	o.UsageType = &v
}

// GetVm returns the Vm field value if set, zero value otherwise.
func (o *GithubComBaselinehqGolangSharedTypesInstance) GetVm() GithubComBaselinehqGolangSharedTypesVM {
	if o == nil || IsNil(o.Vm) {
		var ret GithubComBaselinehqGolangSharedTypesVM
		return ret
	}
	return *o.Vm
}

// GetVmOk returns a tuple with the Vm field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GithubComBaselinehqGolangSharedTypesInstance) GetVmOk() (*GithubComBaselinehqGolangSharedTypesVM, bool) {
	if o == nil || IsNil(o.Vm) {
		return nil, false
	}
	return o.Vm, true
}

// HasVm returns a boolean if a field has been set.
func (o *GithubComBaselinehqGolangSharedTypesInstance) HasVm() bool {
	if o != nil && !IsNil(o.Vm) {
		return true
	}

	return false
}

// SetVm gets a reference to the given GithubComBaselinehqGolangSharedTypesVM and assigns it to the Vm field.
func (o *GithubComBaselinehqGolangSharedTypesInstance) SetVm(v GithubComBaselinehqGolangSharedTypesVM) {
	o.Vm = &v
}

func (o GithubComBaselinehqGolangSharedTypesInstance) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GithubComBaselinehqGolangSharedTypesInstance) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AvailabilityZone) {
		toSerialize["availability_zone"] = o.AvailabilityZone
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.InstanceType) {
		toSerialize["instance_type"] = o.InstanceType
	}
	if !IsNil(o.OperatingSystem) {
		toSerialize["operating_system"] = o.OperatingSystem
	}
	if !IsNil(o.Provider) {
		toSerialize["provider"] = o.Provider
	}
	if !IsNil(o.Region) {
		toSerialize["region"] = o.Region
	}
	if !IsNil(o.Service) {
		toSerialize["service"] = o.Service
	}
	if !IsNil(o.UsageType) {
		toSerialize["usage_type"] = o.UsageType
	}
	if !IsNil(o.Vm) {
		toSerialize["vm"] = o.Vm
	}
	return toSerialize, nil
}

type NullableGithubComBaselinehqGolangSharedTypesInstance struct {
	value *GithubComBaselinehqGolangSharedTypesInstance
	isSet bool
}

func (v NullableGithubComBaselinehqGolangSharedTypesInstance) Get() *GithubComBaselinehqGolangSharedTypesInstance {
	return v.value
}

func (v *NullableGithubComBaselinehqGolangSharedTypesInstance) Set(val *GithubComBaselinehqGolangSharedTypesInstance) {
	v.value = val
	v.isSet = true
}

func (v NullableGithubComBaselinehqGolangSharedTypesInstance) IsSet() bool {
	return v.isSet
}

func (v *NullableGithubComBaselinehqGolangSharedTypesInstance) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGithubComBaselinehqGolangSharedTypesInstance(val *GithubComBaselinehqGolangSharedTypesInstance) *NullableGithubComBaselinehqGolangSharedTypesInstance {
	return &NullableGithubComBaselinehqGolangSharedTypesInstance{value: val, isSet: true}
}

func (v NullableGithubComBaselinehqGolangSharedTypesInstance) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGithubComBaselinehqGolangSharedTypesInstance) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


