/*
Pricing API

Provides API level access to the Costgraph Services.

API version: 1.0
Contact: contact@baselinehq.cloud
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pricing_api_client

import (
	"encoding/json"
	"fmt"
)

// GithubComBaselinehqGolangSharedTypesService the model 'GithubComBaselinehqGolangSharedTypesService'
type GithubComBaselinehqGolangSharedTypesService string

// List of github_com_baselinehq_golang-shared_types.Service
const (
	ComputeEngine GithubComBaselinehqGolangSharedTypesService = "ComputeEngine"
	AmazonEC2 GithubComBaselinehqGolangSharedTypesService = "AmazonEC2"
	Droplet GithubComBaselinehqGolangSharedTypesService = "Droplet"
	AzureCompute GithubComBaselinehqGolangSharedTypesService = "AzureCompute"
	AzureManagedDisks GithubComBaselinehqGolangSharedTypesService = "AzureManagedDisks"
	HetznerCompute GithubComBaselinehqGolangSharedTypesService = "HetznerCompute"
	OVHPublicCloud GithubComBaselinehqGolangSharedTypesService = "OVHPublicCloud"
	BaseCompute GithubComBaselinehqGolangSharedTypesService = "BaseCompute"
)

// All allowed values of GithubComBaselinehqGolangSharedTypesService enum
var AllowedGithubComBaselinehqGolangSharedTypesServiceEnumValues = []GithubComBaselinehqGolangSharedTypesService{
	"ComputeEngine",
	"AmazonEC2",
	"Droplet",
	"AzureCompute",
	"AzureManagedDisks",
	"HetznerCompute",
	"OVHPublicCloud",
	"BaseCompute",
}

func (v *GithubComBaselinehqGolangSharedTypesService) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := GithubComBaselinehqGolangSharedTypesService(value)
	for _, existing := range AllowedGithubComBaselinehqGolangSharedTypesServiceEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid GithubComBaselinehqGolangSharedTypesService", value)
}

// NewGithubComBaselinehqGolangSharedTypesServiceFromValue returns a pointer to a valid GithubComBaselinehqGolangSharedTypesService
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewGithubComBaselinehqGolangSharedTypesServiceFromValue(v string) (*GithubComBaselinehqGolangSharedTypesService, error) {
	ev := GithubComBaselinehqGolangSharedTypesService(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for GithubComBaselinehqGolangSharedTypesService: valid values are %v", v, AllowedGithubComBaselinehqGolangSharedTypesServiceEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v GithubComBaselinehqGolangSharedTypesService) IsValid() bool {
	for _, existing := range AllowedGithubComBaselinehqGolangSharedTypesServiceEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to github_com_baselinehq_golang-shared_types.Service value
func (v GithubComBaselinehqGolangSharedTypesService) Ptr() *GithubComBaselinehqGolangSharedTypesService {
	return &v
}

type NullableGithubComBaselinehqGolangSharedTypesService struct {
	value *GithubComBaselinehqGolangSharedTypesService
	isSet bool
}

func (v NullableGithubComBaselinehqGolangSharedTypesService) Get() *GithubComBaselinehqGolangSharedTypesService {
	return v.value
}

func (v *NullableGithubComBaselinehqGolangSharedTypesService) Set(val *GithubComBaselinehqGolangSharedTypesService) {
	v.value = val
	v.isSet = true
}

func (v NullableGithubComBaselinehqGolangSharedTypesService) IsSet() bool {
	return v.isSet
}

func (v *NullableGithubComBaselinehqGolangSharedTypesService) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGithubComBaselinehqGolangSharedTypesService(val *GithubComBaselinehqGolangSharedTypesService) *NullableGithubComBaselinehqGolangSharedTypesService {
	return &NullableGithubComBaselinehqGolangSharedTypesService{value: val, isSet: true}
}

func (v NullableGithubComBaselinehqGolangSharedTypesService) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGithubComBaselinehqGolangSharedTypesService) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

