/*
Pricing API

Provides API level access to the Costgraph Services.

API version: 1.0
Contact: support@costgraph.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pricing_api_client

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ComputePricesRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ComputePricesRequest{}

// ComputePricesRequest struct for ComputePricesRequest
type ComputePricesRequest struct {
	Entries []ComputePrice `json:"entries"`
}

type _ComputePricesRequest ComputePricesRequest

// NewComputePricesRequest instantiates a new ComputePricesRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComputePricesRequest(entries []ComputePrice) *ComputePricesRequest {
	this := ComputePricesRequest{}
	this.Entries = entries
	return &this
}

// NewComputePricesRequestWithDefaults instantiates a new ComputePricesRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComputePricesRequestWithDefaults() *ComputePricesRequest {
	this := ComputePricesRequest{}
	return &this
}

// GetEntries returns the Entries field value
func (o *ComputePricesRequest) GetEntries() []ComputePrice {
	if o == nil {
		var ret []ComputePrice
		return ret
	}

	return o.Entries
}

// GetEntriesOk returns a tuple with the Entries field value
// and a boolean to check if the value has been set.
func (o *ComputePricesRequest) GetEntriesOk() ([]ComputePrice, bool) {
	if o == nil {
		return nil, false
	}
	return o.Entries, true
}

// SetEntries sets field value
func (o *ComputePricesRequest) SetEntries(v []ComputePrice) {
	o.Entries = v
}

func (o ComputePricesRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ComputePricesRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["entries"] = o.Entries
	return toSerialize, nil
}

func (o *ComputePricesRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"entries",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varComputePricesRequest := _ComputePricesRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varComputePricesRequest)

	if err != nil {
		return err
	}

	*o = ComputePricesRequest(varComputePricesRequest)

	return err
}

type NullableComputePricesRequest struct {
	value *ComputePricesRequest
	isSet bool
}

func (v NullableComputePricesRequest) Get() *ComputePricesRequest {
	return v.value
}

func (v *NullableComputePricesRequest) Set(val *ComputePricesRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableComputePricesRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableComputePricesRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComputePricesRequest(val *ComputePricesRequest) *NullableComputePricesRequest {
	return &NullableComputePricesRequest{value: val, isSet: true}
}

func (v NullableComputePricesRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComputePricesRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
