/*
Pricing API

Provides API level access to the Costgraph Services.

API version: 1.0
Contact: support@costgraph.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pricing_api_client

import (
	"encoding/json"
)

// checks if the ComputeRecommendationRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ComputeRecommendationRequest{}

// ComputeRecommendationRequest struct for ComputeRecommendationRequest
type ComputeRecommendationRequest struct {
	IncludeMetadata *bool                                         `json:"include_metadata,omitempty"`
	Instance        *GithubComBaselinehqGolangSharedTypesInstance `json:"instance,omitempty"`
	Predicates      *TypesPredicates                              `json:"predicates,omitempty"`
	Usage           *GithubComBaselinehqGolangSharedTypesVM       `json:"usage,omitempty"`
}

// NewComputeRecommendationRequest instantiates a new ComputeRecommendationRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComputeRecommendationRequest() *ComputeRecommendationRequest {
	this := ComputeRecommendationRequest{}
	return &this
}

// NewComputeRecommendationRequestWithDefaults instantiates a new ComputeRecommendationRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComputeRecommendationRequestWithDefaults() *ComputeRecommendationRequest {
	this := ComputeRecommendationRequest{}
	return &this
}

// GetIncludeMetadata returns the IncludeMetadata field value if set, zero value otherwise.
func (o *ComputeRecommendationRequest) GetIncludeMetadata() bool {
	if o == nil || IsNil(o.IncludeMetadata) {
		var ret bool
		return ret
	}
	return *o.IncludeMetadata
}

// GetIncludeMetadataOk returns a tuple with the IncludeMetadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComputeRecommendationRequest) GetIncludeMetadataOk() (*bool, bool) {
	if o == nil || IsNil(o.IncludeMetadata) {
		return nil, false
	}
	return o.IncludeMetadata, true
}

// HasIncludeMetadata returns a boolean if a field has been set.
func (o *ComputeRecommendationRequest) HasIncludeMetadata() bool {
	if o != nil && !IsNil(o.IncludeMetadata) {
		return true
	}

	return false
}

// SetIncludeMetadata gets a reference to the given bool and assigns it to the IncludeMetadata field.
func (o *ComputeRecommendationRequest) SetIncludeMetadata(v bool) {
	o.IncludeMetadata = &v
}

// GetInstance returns the Instance field value if set, zero value otherwise.
func (o *ComputeRecommendationRequest) GetInstance() GithubComBaselinehqGolangSharedTypesInstance {
	if o == nil || IsNil(o.Instance) {
		var ret GithubComBaselinehqGolangSharedTypesInstance
		return ret
	}
	return *o.Instance
}

// GetInstanceOk returns a tuple with the Instance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComputeRecommendationRequest) GetInstanceOk() (*GithubComBaselinehqGolangSharedTypesInstance, bool) {
	if o == nil || IsNil(o.Instance) {
		return nil, false
	}
	return o.Instance, true
}

// HasInstance returns a boolean if a field has been set.
func (o *ComputeRecommendationRequest) HasInstance() bool {
	if o != nil && !IsNil(o.Instance) {
		return true
	}

	return false
}

// SetInstance gets a reference to the given GithubComBaselinehqGolangSharedTypesInstance and assigns it to the Instance field.
func (o *ComputeRecommendationRequest) SetInstance(v GithubComBaselinehqGolangSharedTypesInstance) {
	o.Instance = &v
}

// GetPredicates returns the Predicates field value if set, zero value otherwise.
func (o *ComputeRecommendationRequest) GetPredicates() TypesPredicates {
	if o == nil || IsNil(o.Predicates) {
		var ret TypesPredicates
		return ret
	}
	return *o.Predicates
}

// GetPredicatesOk returns a tuple with the Predicates field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComputeRecommendationRequest) GetPredicatesOk() (*TypesPredicates, bool) {
	if o == nil || IsNil(o.Predicates) {
		return nil, false
	}
	return o.Predicates, true
}

// HasPredicates returns a boolean if a field has been set.
func (o *ComputeRecommendationRequest) HasPredicates() bool {
	if o != nil && !IsNil(o.Predicates) {
		return true
	}

	return false
}

// SetPredicates gets a reference to the given TypesPredicates and assigns it to the Predicates field.
func (o *ComputeRecommendationRequest) SetPredicates(v TypesPredicates) {
	o.Predicates = &v
}

// GetUsage returns the Usage field value if set, zero value otherwise.
func (o *ComputeRecommendationRequest) GetUsage() GithubComBaselinehqGolangSharedTypesVM {
	if o == nil || IsNil(o.Usage) {
		var ret GithubComBaselinehqGolangSharedTypesVM
		return ret
	}
	return *o.Usage
}

// GetUsageOk returns a tuple with the Usage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComputeRecommendationRequest) GetUsageOk() (*GithubComBaselinehqGolangSharedTypesVM, bool) {
	if o == nil || IsNil(o.Usage) {
		return nil, false
	}
	return o.Usage, true
}

// HasUsage returns a boolean if a field has been set.
func (o *ComputeRecommendationRequest) HasUsage() bool {
	if o != nil && !IsNil(o.Usage) {
		return true
	}

	return false
}

// SetUsage gets a reference to the given GithubComBaselinehqGolangSharedTypesVM and assigns it to the Usage field.
func (o *ComputeRecommendationRequest) SetUsage(v GithubComBaselinehqGolangSharedTypesVM) {
	o.Usage = &v
}

func (o ComputeRecommendationRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ComputeRecommendationRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.IncludeMetadata) {
		toSerialize["include_metadata"] = o.IncludeMetadata
	}
	if !IsNil(o.Instance) {
		toSerialize["instance"] = o.Instance
	}
	if !IsNil(o.Predicates) {
		toSerialize["predicates"] = o.Predicates
	}
	if !IsNil(o.Usage) {
		toSerialize["usage"] = o.Usage
	}
	return toSerialize, nil
}

type NullableComputeRecommendationRequest struct {
	value *ComputeRecommendationRequest
	isSet bool
}

func (v NullableComputeRecommendationRequest) Get() *ComputeRecommendationRequest {
	return v.value
}

func (v *NullableComputeRecommendationRequest) Set(val *ComputeRecommendationRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableComputeRecommendationRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableComputeRecommendationRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComputeRecommendationRequest(val *ComputeRecommendationRequest) *NullableComputeRecommendationRequest {
	return &NullableComputeRecommendationRequest{value: val, isSet: true}
}

func (v NullableComputeRecommendationRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComputeRecommendationRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
