/*
Pricing API

Provides API level access to the Costgraph Services.

API version: 1.0
Contact: support@costgraph.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pricing_api_client

import (
	"encoding/json"
)

// checks if the DatabasePriceList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DatabasePriceList{}

// DatabasePriceList struct for DatabasePriceList
type DatabasePriceList struct {
	Providers []DatabasePrice `json:"providers,omitempty"`
}

// NewDatabasePriceList instantiates a new DatabasePriceList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDatabasePriceList() *DatabasePriceList {
	this := DatabasePriceList{}
	return &this
}

// NewDatabasePriceListWithDefaults instantiates a new DatabasePriceList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDatabasePriceListWithDefaults() *DatabasePriceList {
	this := DatabasePriceList{}
	return &this
}

// GetProviders returns the Providers field value if set, zero value otherwise.
func (o *DatabasePriceList) GetProviders() []DatabasePrice {
	if o == nil || IsNil(o.Providers) {
		var ret []DatabasePrice
		return ret
	}
	return o.Providers
}

// GetProvidersOk returns a tuple with the Providers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DatabasePriceList) GetProvidersOk() ([]DatabasePrice, bool) {
	if o == nil || IsNil(o.Providers) {
		return nil, false
	}
	return o.Providers, true
}

// HasProviders returns a boolean if a field has been set.
func (o *DatabasePriceList) HasProviders() bool {
	if o != nil && !IsNil(o.Providers) {
		return true
	}

	return false
}

// SetProviders gets a reference to the given []DatabasePrice and assigns it to the Providers field.
func (o *DatabasePriceList) SetProviders(v []DatabasePrice) {
	o.Providers = v
}

func (o DatabasePriceList) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DatabasePriceList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Providers) {
		toSerialize["providers"] = o.Providers
	}
	return toSerialize, nil
}

type NullableDatabasePriceList struct {
	value *DatabasePriceList
	isSet bool
}

func (v NullableDatabasePriceList) Get() *DatabasePriceList {
	return v.value
}

func (v *NullableDatabasePriceList) Set(val *DatabasePriceList) {
	v.value = val
	v.isSet = true
}

func (v NullableDatabasePriceList) IsSet() bool {
	return v.isSet
}

func (v *NullableDatabasePriceList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDatabasePriceList(val *DatabasePriceList) *NullableDatabasePriceList {
	return &NullableDatabasePriceList{value: val, isSet: true}
}

func (v NullableDatabasePriceList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDatabasePriceList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
