/*
Pricing API

Provides API level access to the Costgraph Services.

API version: 1.0
Contact: support@costgraph.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pricing_api_client

import (
	"encoding/json"
)

// checks if the ComputePricePage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ComputePricePage{}

// ComputePricePage struct for ComputePricePage
type ComputePricePage struct {
	Data []ComputePrice `json:"data,omitempty"`
	Page *Page          `json:"page,omitempty"`
}

// NewComputePricePage instantiates a new ComputePricePage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComputePricePage() *ComputePricePage {
	this := ComputePricePage{}
	return &this
}

// NewComputePricePageWithDefaults instantiates a new ComputePricePage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComputePricePageWithDefaults() *ComputePricePage {
	this := ComputePricePage{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *ComputePricePage) GetData() []ComputePrice {
	if o == nil || IsNil(o.Data) {
		var ret []ComputePrice
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComputePricePage) GetDataOk() ([]ComputePrice, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ComputePricePage) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []ComputePrice and assigns it to the Data field.
func (o *ComputePricePage) SetData(v []ComputePrice) {
	o.Data = v
}

// GetPage returns the Page field value if set, zero value otherwise.
func (o *ComputePricePage) GetPage() Page {
	if o == nil || IsNil(o.Page) {
		var ret Page
		return ret
	}
	return *o.Page
}

// GetPageOk returns a tuple with the Page field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComputePricePage) GetPageOk() (*Page, bool) {
	if o == nil || IsNil(o.Page) {
		return nil, false
	}
	return o.Page, true
}

// HasPage returns a boolean if a field has been set.
func (o *ComputePricePage) HasPage() bool {
	if o != nil && !IsNil(o.Page) {
		return true
	}

	return false
}

// SetPage gets a reference to the given Page and assigns it to the Page field.
func (o *ComputePricePage) SetPage(v Page) {
	o.Page = &v
}

func (o ComputePricePage) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ComputePricePage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Page) {
		toSerialize["page"] = o.Page
	}
	return toSerialize, nil
}

type NullableComputePricePage struct {
	value *ComputePricePage
	isSet bool
}

func (v NullableComputePricePage) Get() *ComputePricePage {
	return v.value
}

func (v *NullableComputePricePage) Set(val *ComputePricePage) {
	v.value = val
	v.isSet = true
}

func (v NullableComputePricePage) IsSet() bool {
	return v.isSet
}

func (v *NullableComputePricePage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComputePricePage(val *ComputePricePage) *NullableComputePricePage {
	return &NullableComputePricePage{value: val, isSet: true}
}

func (v NullableComputePricePage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComputePricePage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
