/*
Pricing API

Provides API level access to the Costgraph Services.

API version: 1.0
Contact: support@costgraph.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pricing_api_client

import (
	"encoding/json"
)

// checks if the FilterSet type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FilterSet{}

// FilterSet struct for FilterSet
type FilterSet struct {
	Filters []string `json:"filters,omitempty"`
	Kind    *string  `json:"kind,omitempty"`
}

// NewFilterSet instantiates a new FilterSet object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFilterSet() *FilterSet {
	this := FilterSet{}
	return &this
}

// NewFilterSetWithDefaults instantiates a new FilterSet object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFilterSetWithDefaults() *FilterSet {
	this := FilterSet{}
	return &this
}

// GetFilters returns the Filters field value if set, zero value otherwise.
func (o *FilterSet) GetFilters() []string {
	if o == nil || IsNil(o.Filters) {
		var ret []string
		return ret
	}
	return o.Filters
}

// GetFiltersOk returns a tuple with the Filters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FilterSet) GetFiltersOk() ([]string, bool) {
	if o == nil || IsNil(o.Filters) {
		return nil, false
	}
	return o.Filters, true
}

// HasFilters returns a boolean if a field has been set.
func (o *FilterSet) HasFilters() bool {
	if o != nil && !IsNil(o.Filters) {
		return true
	}

	return false
}

// SetFilters gets a reference to the given []string and assigns it to the Filters field.
func (o *FilterSet) SetFilters(v []string) {
	o.Filters = v
}

// GetKind returns the Kind field value if set, zero value otherwise.
func (o *FilterSet) GetKind() string {
	if o == nil || IsNil(o.Kind) {
		var ret string
		return ret
	}
	return *o.Kind
}

// GetKindOk returns a tuple with the Kind field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FilterSet) GetKindOk() (*string, bool) {
	if o == nil || IsNil(o.Kind) {
		return nil, false
	}
	return o.Kind, true
}

// HasKind returns a boolean if a field has been set.
func (o *FilterSet) HasKind() bool {
	if o != nil && !IsNil(o.Kind) {
		return true
	}

	return false
}

// SetKind gets a reference to the given string and assigns it to the Kind field.
func (o *FilterSet) SetKind(v string) {
	o.Kind = &v
}

func (o FilterSet) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FilterSet) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Filters) {
		toSerialize["filters"] = o.Filters
	}
	if !IsNil(o.Kind) {
		toSerialize["kind"] = o.Kind
	}
	return toSerialize, nil
}

type NullableFilterSet struct {
	value *FilterSet
	isSet bool
}

func (v NullableFilterSet) Get() *FilterSet {
	return v.value
}

func (v *NullableFilterSet) Set(val *FilterSet) {
	v.value = val
	v.isSet = true
}

func (v NullableFilterSet) IsSet() bool {
	return v.isSet
}

func (v *NullableFilterSet) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFilterSet(val *FilterSet) *NullableFilterSet {
	return &NullableFilterSet{value: val, isSet: true}
}

func (v NullableFilterSet) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFilterSet) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
