/*
Pricing API

Provides API level access to the Costgraph Services.

API version: 1.0
Contact: contact@baselinehq.cloud
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pricing_api_client

import (
	"encoding/json"
)

// checks if the ProviderConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProviderConfig{}

// ProviderConfig struct for ProviderConfig
type ProviderConfig struct {
	Predicates *TypesPredicates `json:"predicates,omitempty"`
	Provider *GithubComBaselinehqGolangSharedTypesProvider `json:"provider,omitempty"`
}

// NewProviderConfig instantiates a new ProviderConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProviderConfig() *ProviderConfig {
	this := ProviderConfig{}
	return &this
}

// NewProviderConfigWithDefaults instantiates a new ProviderConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProviderConfigWithDefaults() *ProviderConfig {
	this := ProviderConfig{}
	return &this
}

// GetPredicates returns the Predicates field value if set, zero value otherwise.
func (o *ProviderConfig) GetPredicates() TypesPredicates {
	if o == nil || IsNil(o.Predicates) {
		var ret TypesPredicates
		return ret
	}
	return *o.Predicates
}

// GetPredicatesOk returns a tuple with the Predicates field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProviderConfig) GetPredicatesOk() (*TypesPredicates, bool) {
	if o == nil || IsNil(o.Predicates) {
		return nil, false
	}
	return o.Predicates, true
}

// HasPredicates returns a boolean if a field has been set.
func (o *ProviderConfig) HasPredicates() bool {
	if o != nil && !IsNil(o.Predicates) {
		return true
	}

	return false
}

// SetPredicates gets a reference to the given TypesPredicates and assigns it to the Predicates field.
func (o *ProviderConfig) SetPredicates(v TypesPredicates) {
	o.Predicates = &v
}

// GetProvider returns the Provider field value if set, zero value otherwise.
func (o *ProviderConfig) GetProvider() GithubComBaselinehqGolangSharedTypesProvider {
	if o == nil || IsNil(o.Provider) {
		var ret GithubComBaselinehqGolangSharedTypesProvider
		return ret
	}
	return *o.Provider
}

// GetProviderOk returns a tuple with the Provider field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProviderConfig) GetProviderOk() (*GithubComBaselinehqGolangSharedTypesProvider, bool) {
	if o == nil || IsNil(o.Provider) {
		return nil, false
	}
	return o.Provider, true
}

// HasProvider returns a boolean if a field has been set.
func (o *ProviderConfig) HasProvider() bool {
	if o != nil && !IsNil(o.Provider) {
		return true
	}

	return false
}

// SetProvider gets a reference to the given GithubComBaselinehqGolangSharedTypesProvider and assigns it to the Provider field.
func (o *ProviderConfig) SetProvider(v GithubComBaselinehqGolangSharedTypesProvider) {
	o.Provider = &v
}

func (o ProviderConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProviderConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Predicates) {
		toSerialize["predicates"] = o.Predicates
	}
	if !IsNil(o.Provider) {
		toSerialize["provider"] = o.Provider
	}
	return toSerialize, nil
}

type NullableProviderConfig struct {
	value *ProviderConfig
	isSet bool
}

func (v NullableProviderConfig) Get() *ProviderConfig {
	return v.value
}

func (v *NullableProviderConfig) Set(val *ProviderConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableProviderConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableProviderConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProviderConfig(val *ProviderConfig) *NullableProviderConfig {
	return &NullableProviderConfig{value: val, isSet: true}
}

func (v NullableProviderConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProviderConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


