/*
Pricing API

Provides API level access to the Costgraph Services.

API version: 1.0
Contact: support@costgraph.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pricing_api_client

import (
	"encoding/json"
)

// checks if the RegisteredDatabasePrices type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RegisteredDatabasePrices{}

// RegisteredDatabasePrices struct for RegisteredDatabasePrices
type RegisteredDatabasePrices struct {
	Entries []DatabasePrice     `json:"entries,omitempty"`
	Status  *RegistrationStatus `json:"status,omitempty"`
}

// NewRegisteredDatabasePrices instantiates a new RegisteredDatabasePrices object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRegisteredDatabasePrices() *RegisteredDatabasePrices {
	this := RegisteredDatabasePrices{}
	return &this
}

// NewRegisteredDatabasePricesWithDefaults instantiates a new RegisteredDatabasePrices object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRegisteredDatabasePricesWithDefaults() *RegisteredDatabasePrices {
	this := RegisteredDatabasePrices{}
	return &this
}

// GetEntries returns the Entries field value if set, zero value otherwise.
func (o *RegisteredDatabasePrices) GetEntries() []DatabasePrice {
	if o == nil || IsNil(o.Entries) {
		var ret []DatabasePrice
		return ret
	}
	return o.Entries
}

// GetEntriesOk returns a tuple with the Entries field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegisteredDatabasePrices) GetEntriesOk() ([]DatabasePrice, bool) {
	if o == nil || IsNil(o.Entries) {
		return nil, false
	}
	return o.Entries, true
}

// HasEntries returns a boolean if a field has been set.
func (o *RegisteredDatabasePrices) HasEntries() bool {
	if o != nil && !IsNil(o.Entries) {
		return true
	}

	return false
}

// SetEntries gets a reference to the given []DatabasePrice and assigns it to the Entries field.
func (o *RegisteredDatabasePrices) SetEntries(v []DatabasePrice) {
	o.Entries = v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *RegisteredDatabasePrices) GetStatus() RegistrationStatus {
	if o == nil || IsNil(o.Status) {
		var ret RegistrationStatus
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegisteredDatabasePrices) GetStatusOk() (*RegistrationStatus, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *RegisteredDatabasePrices) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given RegistrationStatus and assigns it to the Status field.
func (o *RegisteredDatabasePrices) SetStatus(v RegistrationStatus) {
	o.Status = &v
}

func (o RegisteredDatabasePrices) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RegisteredDatabasePrices) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Entries) {
		toSerialize["entries"] = o.Entries
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableRegisteredDatabasePrices struct {
	value *RegisteredDatabasePrices
	isSet bool
}

func (v NullableRegisteredDatabasePrices) Get() *RegisteredDatabasePrices {
	return v.value
}

func (v *NullableRegisteredDatabasePrices) Set(val *RegisteredDatabasePrices) {
	v.value = val
	v.isSet = true
}

func (v NullableRegisteredDatabasePrices) IsSet() bool {
	return v.isSet
}

func (v *NullableRegisteredDatabasePrices) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRegisteredDatabasePrices(val *RegisteredDatabasePrices) *NullableRegisteredDatabasePrices {
	return &NullableRegisteredDatabasePrices{value: val, isSet: true}
}

func (v NullableRegisteredDatabasePrices) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRegisteredDatabasePrices) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
