/*
Pricing API

Provides API level access to the Costgraph Services.

API version: 1.0
Contact: contact@baselinehq.cloud
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pricing_api_client

import (
	"encoding/json"
)

// checks if the HandlerErrorResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HandlerErrorResponse{}

// HandlerErrorResponse struct for HandlerErrorResponse
type HandlerErrorResponse struct {
	Error *string `json:"error,omitempty"`
}

// NewHandlerErrorResponse instantiates a new HandlerErrorResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHandlerErrorResponse() *HandlerErrorResponse {
	this := HandlerErrorResponse{}
	return &this
}

// NewHandlerErrorResponseWithDefaults instantiates a new HandlerErrorResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHandlerErrorResponseWithDefaults() *HandlerErrorResponse {
	this := HandlerErrorResponse{}
	return &this
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *HandlerErrorResponse) GetError() string {
	if o == nil || IsNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HandlerErrorResponse) GetErrorOk() (*string, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *HandlerErrorResponse) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *HandlerErrorResponse) SetError(v string) {
	o.Error = &v
}

func (o HandlerErrorResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HandlerErrorResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	return toSerialize, nil
}

type NullableHandlerErrorResponse struct {
	value *HandlerErrorResponse
	isSet bool
}

func (v NullableHandlerErrorResponse) Get() *HandlerErrorResponse {
	return v.value
}

func (v *NullableHandlerErrorResponse) Set(val *HandlerErrorResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableHandlerErrorResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableHandlerErrorResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHandlerErrorResponse(val *HandlerErrorResponse) *NullableHandlerErrorResponse {
	return &NullableHandlerErrorResponse{value: val, isSet: true}
}

func (v NullableHandlerErrorResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHandlerErrorResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
