/*
Pricing API

Provides API level access to the Costgraph Services.

API version: 1.0
Contact: contact@baselinehq.cloud
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pricing_api_client

import (
	"encoding/json"
)

// checks if the TypesCustomPricingResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TypesCustomPricingResponse{}

// TypesCustomPricingResponse struct for TypesCustomPricingResponse
type TypesCustomPricingResponse struct {
	Entries []SchemaComputePricingsRow `json:"entries,omitempty"`
	Status *GithubComBaselinehqPricingapiPkgTypesStatus `json:"status,omitempty"`
}

// NewTypesCustomPricingResponse instantiates a new TypesCustomPricingResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTypesCustomPricingResponse() *TypesCustomPricingResponse {
	this := TypesCustomPricingResponse{}
	return &this
}

// NewTypesCustomPricingResponseWithDefaults instantiates a new TypesCustomPricingResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTypesCustomPricingResponseWithDefaults() *TypesCustomPricingResponse {
	this := TypesCustomPricingResponse{}
	return &this
}

// GetEntries returns the Entries field value if set, zero value otherwise.
func (o *TypesCustomPricingResponse) GetEntries() []SchemaComputePricingsRow {
	if o == nil || IsNil(o.Entries) {
		var ret []SchemaComputePricingsRow
		return ret
	}
	return o.Entries
}

// GetEntriesOk returns a tuple with the Entries field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TypesCustomPricingResponse) GetEntriesOk() ([]SchemaComputePricingsRow, bool) {
	if o == nil || IsNil(o.Entries) {
		return nil, false
	}
	return o.Entries, true
}

// HasEntries returns a boolean if a field has been set.
func (o *TypesCustomPricingResponse) HasEntries() bool {
	if o != nil && !IsNil(o.Entries) {
		return true
	}

	return false
}

// SetEntries gets a reference to the given []SchemaComputePricingsRow and assigns it to the Entries field.
func (o *TypesCustomPricingResponse) SetEntries(v []SchemaComputePricingsRow) {
	o.Entries = v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *TypesCustomPricingResponse) GetStatus() GithubComBaselinehqPricingapiPkgTypesStatus {
	if o == nil || IsNil(o.Status) {
		var ret GithubComBaselinehqPricingapiPkgTypesStatus
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TypesCustomPricingResponse) GetStatusOk() (*GithubComBaselinehqPricingapiPkgTypesStatus, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *TypesCustomPricingResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given GithubComBaselinehqPricingapiPkgTypesStatus and assigns it to the Status field.
func (o *TypesCustomPricingResponse) SetStatus(v GithubComBaselinehqPricingapiPkgTypesStatus) {
	o.Status = &v
}

func (o TypesCustomPricingResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TypesCustomPricingResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Entries) {
		toSerialize["entries"] = o.Entries
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableTypesCustomPricingResponse struct {
	value *TypesCustomPricingResponse
	isSet bool
}

func (v NullableTypesCustomPricingResponse) Get() *TypesCustomPricingResponse {
	return v.value
}

func (v *NullableTypesCustomPricingResponse) Set(val *TypesCustomPricingResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableTypesCustomPricingResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableTypesCustomPricingResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTypesCustomPricingResponse(val *TypesCustomPricingResponse) *NullableTypesCustomPricingResponse {
	return &NullableTypesCustomPricingResponse{value: val, isSet: true}
}

func (v NullableTypesCustomPricingResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTypesCustomPricingResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


