/*
Pricing API

Provides API level access to the Costgraph Services.

API version: 1.0
Contact: support@costgraph.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pricing_api_client

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the DiskPricesRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DiskPricesRequest{}

// DiskPricesRequest struct for DiskPricesRequest
type DiskPricesRequest struct {
	Entries []DiskPrice `json:"entries"`
}

type _DiskPricesRequest DiskPricesRequest

// NewDiskPricesRequest instantiates a new DiskPricesRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDiskPricesRequest(entries []DiskPrice) *DiskPricesRequest {
	this := DiskPricesRequest{}
	this.Entries = entries
	return &this
}

// NewDiskPricesRequestWithDefaults instantiates a new DiskPricesRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDiskPricesRequestWithDefaults() *DiskPricesRequest {
	this := DiskPricesRequest{}
	return &this
}

// GetEntries returns the Entries field value
func (o *DiskPricesRequest) GetEntries() []DiskPrice {
	if o == nil {
		var ret []DiskPrice
		return ret
	}

	return o.Entries
}

// GetEntriesOk returns a tuple with the Entries field value
// and a boolean to check if the value has been set.
func (o *DiskPricesRequest) GetEntriesOk() ([]DiskPrice, bool) {
	if o == nil {
		return nil, false
	}
	return o.Entries, true
}

// SetEntries sets field value
func (o *DiskPricesRequest) SetEntries(v []DiskPrice) {
	o.Entries = v
}

func (o DiskPricesRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DiskPricesRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["entries"] = o.Entries
	return toSerialize, nil
}

func (o *DiskPricesRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"entries",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDiskPricesRequest := _DiskPricesRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDiskPricesRequest)

	if err != nil {
		return err
	}

	*o = DiskPricesRequest(varDiskPricesRequest)

	return err
}

type NullableDiskPricesRequest struct {
	value *DiskPricesRequest
	isSet bool
}

func (v NullableDiskPricesRequest) Get() *DiskPricesRequest {
	return v.value
}

func (v *NullableDiskPricesRequest) Set(val *DiskPricesRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDiskPricesRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDiskPricesRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDiskPricesRequest(val *DiskPricesRequest) *NullableDiskPricesRequest {
	return &NullableDiskPricesRequest{value: val, isSet: true}
}

func (v NullableDiskPricesRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDiskPricesRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
