/*
Pricing API

Provides API level access to the Costgraph Services.

API version: 1.0
Contact: support@costgraph.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pricing_api_client

import (
	"encoding/json"
)

// checks if the Disk type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Disk{}

// Disk struct for Disk
type Disk struct {
	AvailabilityZone      *string                                        `json:"availability_zone,omitempty"`
	CapacityGb            *float32                                       `json:"capacity_gb,omitempty"`
	FallbackToBasePricing *bool                                          `json:"fallback_to_base_pricing,omitempty"`
	Id                    *string                                        `json:"id,omitempty"`
	Iops                  *float32                                       `json:"iops,omitempty"`
	Provider              *GithubComBaselinehqGolangSharedTypesProvider  `json:"provider,omitempty"`
	Region                *string                                        `json:"region,omitempty"`
	Service               *TypesService                                  `json:"service,omitempty"`
	ThroughputMbps        *float32                                       `json:"throughput_mbps,omitempty"`
	Type                  *string                                        `json:"type,omitempty"`
	UsageType             *GithubComBaselinehqGolangSharedTypesUsageType `json:"usage_type,omitempty"`
}

// NewDisk instantiates a new Disk object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDisk() *Disk {
	this := Disk{}
	return &this
}

// NewDiskWithDefaults instantiates a new Disk object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDiskWithDefaults() *Disk {
	this := Disk{}
	return &this
}

// GetAvailabilityZone returns the AvailabilityZone field value if set, zero value otherwise.
func (o *Disk) GetAvailabilityZone() string {
	if o == nil || IsNil(o.AvailabilityZone) {
		var ret string
		return ret
	}
	return *o.AvailabilityZone
}

// GetAvailabilityZoneOk returns a tuple with the AvailabilityZone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Disk) GetAvailabilityZoneOk() (*string, bool) {
	if o == nil || IsNil(o.AvailabilityZone) {
		return nil, false
	}
	return o.AvailabilityZone, true
}

// HasAvailabilityZone returns a boolean if a field has been set.
func (o *Disk) HasAvailabilityZone() bool {
	if o != nil && !IsNil(o.AvailabilityZone) {
		return true
	}

	return false
}

// SetAvailabilityZone gets a reference to the given string and assigns it to the AvailabilityZone field.
func (o *Disk) SetAvailabilityZone(v string) {
	o.AvailabilityZone = &v
}

// GetCapacityGb returns the CapacityGb field value if set, zero value otherwise.
func (o *Disk) GetCapacityGb() float32 {
	if o == nil || IsNil(o.CapacityGb) {
		var ret float32
		return ret
	}
	return *o.CapacityGb
}

// GetCapacityGbOk returns a tuple with the CapacityGb field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Disk) GetCapacityGbOk() (*float32, bool) {
	if o == nil || IsNil(o.CapacityGb) {
		return nil, false
	}
	return o.CapacityGb, true
}

// HasCapacityGb returns a boolean if a field has been set.
func (o *Disk) HasCapacityGb() bool {
	if o != nil && !IsNil(o.CapacityGb) {
		return true
	}

	return false
}

// SetCapacityGb gets a reference to the given float32 and assigns it to the CapacityGb field.
func (o *Disk) SetCapacityGb(v float32) {
	o.CapacityGb = &v
}

// GetFallbackToBasePricing returns the FallbackToBasePricing field value if set, zero value otherwise.
func (o *Disk) GetFallbackToBasePricing() bool {
	if o == nil || IsNil(o.FallbackToBasePricing) {
		var ret bool
		return ret
	}
	return *o.FallbackToBasePricing
}

// GetFallbackToBasePricingOk returns a tuple with the FallbackToBasePricing field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Disk) GetFallbackToBasePricingOk() (*bool, bool) {
	if o == nil || IsNil(o.FallbackToBasePricing) {
		return nil, false
	}
	return o.FallbackToBasePricing, true
}

// HasFallbackToBasePricing returns a boolean if a field has been set.
func (o *Disk) HasFallbackToBasePricing() bool {
	if o != nil && !IsNil(o.FallbackToBasePricing) {
		return true
	}

	return false
}

// SetFallbackToBasePricing gets a reference to the given bool and assigns it to the FallbackToBasePricing field.
func (o *Disk) SetFallbackToBasePricing(v bool) {
	o.FallbackToBasePricing = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Disk) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Disk) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *Disk) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *Disk) SetId(v string) {
	o.Id = &v
}

// GetIops returns the Iops field value if set, zero value otherwise.
func (o *Disk) GetIops() float32 {
	if o == nil || IsNil(o.Iops) {
		var ret float32
		return ret
	}
	return *o.Iops
}

// GetIopsOk returns a tuple with the Iops field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Disk) GetIopsOk() (*float32, bool) {
	if o == nil || IsNil(o.Iops) {
		return nil, false
	}
	return o.Iops, true
}

// HasIops returns a boolean if a field has been set.
func (o *Disk) HasIops() bool {
	if o != nil && !IsNil(o.Iops) {
		return true
	}

	return false
}

// SetIops gets a reference to the given float32 and assigns it to the Iops field.
func (o *Disk) SetIops(v float32) {
	o.Iops = &v
}

// GetProvider returns the Provider field value if set, zero value otherwise.
func (o *Disk) GetProvider() GithubComBaselinehqGolangSharedTypesProvider {
	if o == nil || IsNil(o.Provider) {
		var ret GithubComBaselinehqGolangSharedTypesProvider
		return ret
	}
	return *o.Provider
}

// GetProviderOk returns a tuple with the Provider field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Disk) GetProviderOk() (*GithubComBaselinehqGolangSharedTypesProvider, bool) {
	if o == nil || IsNil(o.Provider) {
		return nil, false
	}
	return o.Provider, true
}

// HasProvider returns a boolean if a field has been set.
func (o *Disk) HasProvider() bool {
	if o != nil && !IsNil(o.Provider) {
		return true
	}

	return false
}

// SetProvider gets a reference to the given GithubComBaselinehqGolangSharedTypesProvider and assigns it to the Provider field.
func (o *Disk) SetProvider(v GithubComBaselinehqGolangSharedTypesProvider) {
	o.Provider = &v
}

// GetRegion returns the Region field value if set, zero value otherwise.
func (o *Disk) GetRegion() string {
	if o == nil || IsNil(o.Region) {
		var ret string
		return ret
	}
	return *o.Region
}

// GetRegionOk returns a tuple with the Region field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Disk) GetRegionOk() (*string, bool) {
	if o == nil || IsNil(o.Region) {
		return nil, false
	}
	return o.Region, true
}

// HasRegion returns a boolean if a field has been set.
func (o *Disk) HasRegion() bool {
	if o != nil && !IsNil(o.Region) {
		return true
	}

	return false
}

// SetRegion gets a reference to the given string and assigns it to the Region field.
func (o *Disk) SetRegion(v string) {
	o.Region = &v
}

// GetService returns the Service field value if set, zero value otherwise.
func (o *Disk) GetService() TypesService {
	if o == nil || IsNil(o.Service) {
		var ret TypesService
		return ret
	}
	return *o.Service
}

// GetServiceOk returns a tuple with the Service field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Disk) GetServiceOk() (*TypesService, bool) {
	if o == nil || IsNil(o.Service) {
		return nil, false
	}
	return o.Service, true
}

// HasService returns a boolean if a field has been set.
func (o *Disk) HasService() bool {
	if o != nil && !IsNil(o.Service) {
		return true
	}

	return false
}

// SetService gets a reference to the given TypesService and assigns it to the Service field.
func (o *Disk) SetService(v TypesService) {
	o.Service = &v
}

// GetThroughputMbps returns the ThroughputMbps field value if set, zero value otherwise.
func (o *Disk) GetThroughputMbps() float32 {
	if o == nil || IsNil(o.ThroughputMbps) {
		var ret float32
		return ret
	}
	return *o.ThroughputMbps
}

// GetThroughputMbpsOk returns a tuple with the ThroughputMbps field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Disk) GetThroughputMbpsOk() (*float32, bool) {
	if o == nil || IsNil(o.ThroughputMbps) {
		return nil, false
	}
	return o.ThroughputMbps, true
}

// HasThroughputMbps returns a boolean if a field has been set.
func (o *Disk) HasThroughputMbps() bool {
	if o != nil && !IsNil(o.ThroughputMbps) {
		return true
	}

	return false
}

// SetThroughputMbps gets a reference to the given float32 and assigns it to the ThroughputMbps field.
func (o *Disk) SetThroughputMbps(v float32) {
	o.ThroughputMbps = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *Disk) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Disk) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *Disk) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *Disk) SetType(v string) {
	o.Type = &v
}

// GetUsageType returns the UsageType field value if set, zero value otherwise.
func (o *Disk) GetUsageType() GithubComBaselinehqGolangSharedTypesUsageType {
	if o == nil || IsNil(o.UsageType) {
		var ret GithubComBaselinehqGolangSharedTypesUsageType
		return ret
	}
	return *o.UsageType
}

// GetUsageTypeOk returns a tuple with the UsageType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Disk) GetUsageTypeOk() (*GithubComBaselinehqGolangSharedTypesUsageType, bool) {
	if o == nil || IsNil(o.UsageType) {
		return nil, false
	}
	return o.UsageType, true
}

// HasUsageType returns a boolean if a field has been set.
func (o *Disk) HasUsageType() bool {
	if o != nil && !IsNil(o.UsageType) {
		return true
	}

	return false
}

// SetUsageType gets a reference to the given GithubComBaselinehqGolangSharedTypesUsageType and assigns it to the UsageType field.
func (o *Disk) SetUsageType(v GithubComBaselinehqGolangSharedTypesUsageType) {
	o.UsageType = &v
}

func (o Disk) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Disk) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AvailabilityZone) {
		toSerialize["availability_zone"] = o.AvailabilityZone
	}
	if !IsNil(o.CapacityGb) {
		toSerialize["capacity_gb"] = o.CapacityGb
	}
	if !IsNil(o.FallbackToBasePricing) {
		toSerialize["fallback_to_base_pricing"] = o.FallbackToBasePricing
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Iops) {
		toSerialize["iops"] = o.Iops
	}
	if !IsNil(o.Provider) {
		toSerialize["provider"] = o.Provider
	}
	if !IsNil(o.Region) {
		toSerialize["region"] = o.Region
	}
	if !IsNil(o.Service) {
		toSerialize["service"] = o.Service
	}
	if !IsNil(o.ThroughputMbps) {
		toSerialize["throughput_mbps"] = o.ThroughputMbps
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.UsageType) {
		toSerialize["usage_type"] = o.UsageType
	}
	return toSerialize, nil
}

type NullableDisk struct {
	value *Disk
	isSet bool
}

func (v NullableDisk) Get() *Disk {
	return v.value
}

func (v *NullableDisk) Set(val *Disk) {
	v.value = val
	v.isSet = true
}

func (v NullableDisk) IsSet() bool {
	return v.isSet
}

func (v *NullableDisk) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDisk(val *Disk) *NullableDisk {
	return &NullableDisk{value: val, isSet: true}
}

func (v NullableDisk) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDisk) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
