/*
Pricing API

Provides API level access to the Costgraph Services.

API version: 1.0
Contact: support@costgraph.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pricing_api_client

import (
	"encoding/json"
)

// checks if the ComputeRecommendation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ComputeRecommendation{}

// ComputeRecommendation struct for ComputeRecommendation
type ComputeRecommendation struct {
	Pricing *ComputePrice `json:"pricing,omitempty"`
	Savings *TypesSavings `json:"savings,omitempty"`
}

// NewComputeRecommendation instantiates a new ComputeRecommendation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComputeRecommendation() *ComputeRecommendation {
	this := ComputeRecommendation{}
	return &this
}

// NewComputeRecommendationWithDefaults instantiates a new ComputeRecommendation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComputeRecommendationWithDefaults() *ComputeRecommendation {
	this := ComputeRecommendation{}
	return &this
}

// GetPricing returns the Pricing field value if set, zero value otherwise.
func (o *ComputeRecommendation) GetPricing() ComputePrice {
	if o == nil || IsNil(o.Pricing) {
		var ret ComputePrice
		return ret
	}
	return *o.Pricing
}

// GetPricingOk returns a tuple with the Pricing field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComputeRecommendation) GetPricingOk() (*ComputePrice, bool) {
	if o == nil || IsNil(o.Pricing) {
		return nil, false
	}
	return o.Pricing, true
}

// HasPricing returns a boolean if a field has been set.
func (o *ComputeRecommendation) HasPricing() bool {
	if o != nil && !IsNil(o.Pricing) {
		return true
	}

	return false
}

// SetPricing gets a reference to the given ComputePrice and assigns it to the Pricing field.
func (o *ComputeRecommendation) SetPricing(v ComputePrice) {
	o.Pricing = &v
}

// GetSavings returns the Savings field value if set, zero value otherwise.
func (o *ComputeRecommendation) GetSavings() TypesSavings {
	if o == nil || IsNil(o.Savings) {
		var ret TypesSavings
		return ret
	}
	return *o.Savings
}

// GetSavingsOk returns a tuple with the Savings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComputeRecommendation) GetSavingsOk() (*TypesSavings, bool) {
	if o == nil || IsNil(o.Savings) {
		return nil, false
	}
	return o.Savings, true
}

// HasSavings returns a boolean if a field has been set.
func (o *ComputeRecommendation) HasSavings() bool {
	if o != nil && !IsNil(o.Savings) {
		return true
	}

	return false
}

// SetSavings gets a reference to the given TypesSavings and assigns it to the Savings field.
func (o *ComputeRecommendation) SetSavings(v TypesSavings) {
	o.Savings = &v
}

func (o ComputeRecommendation) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ComputeRecommendation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Pricing) {
		toSerialize["pricing"] = o.Pricing
	}
	if !IsNil(o.Savings) {
		toSerialize["savings"] = o.Savings
	}
	return toSerialize, nil
}

type NullableComputeRecommendation struct {
	value *ComputeRecommendation
	isSet bool
}

func (v NullableComputeRecommendation) Get() *ComputeRecommendation {
	return v.value
}

func (v *NullableComputeRecommendation) Set(val *ComputeRecommendation) {
	v.value = val
	v.isSet = true
}

func (v NullableComputeRecommendation) IsSet() bool {
	return v.isSet
}

func (v *NullableComputeRecommendation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComputeRecommendation(val *ComputeRecommendation) *NullableComputeRecommendation {
	return &NullableComputeRecommendation{value: val, isSet: true}
}

func (v NullableComputeRecommendation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComputeRecommendation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
