/*
Pricing API

Provides API level access to the Costgraph Services.

API version: 1.0
Contact: contact@baselinehq.cloud
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pricing_api_client

import (
	"encoding/json"
)

// checks if the TypesDiskRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TypesDiskRequest{}

// TypesDiskRequest struct for TypesDiskRequest
type TypesDiskRequest struct {
	IncludeMetadata *bool `json:"include_metadata,omitempty"`
	Instance *TypesDisk `json:"instance,omitempty"`
	Predicates *TypesPredicates `json:"predicates,omitempty"`
	Usage *TypesDisk `json:"usage,omitempty"`
}

// NewTypesDiskRequest instantiates a new TypesDiskRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTypesDiskRequest() *TypesDiskRequest {
	this := TypesDiskRequest{}
	return &this
}

// NewTypesDiskRequestWithDefaults instantiates a new TypesDiskRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTypesDiskRequestWithDefaults() *TypesDiskRequest {
	this := TypesDiskRequest{}
	return &this
}

// GetIncludeMetadata returns the IncludeMetadata field value if set, zero value otherwise.
func (o *TypesDiskRequest) GetIncludeMetadata() bool {
	if o == nil || IsNil(o.IncludeMetadata) {
		var ret bool
		return ret
	}
	return *o.IncludeMetadata
}

// GetIncludeMetadataOk returns a tuple with the IncludeMetadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TypesDiskRequest) GetIncludeMetadataOk() (*bool, bool) {
	if o == nil || IsNil(o.IncludeMetadata) {
		return nil, false
	}
	return o.IncludeMetadata, true
}

// HasIncludeMetadata returns a boolean if a field has been set.
func (o *TypesDiskRequest) HasIncludeMetadata() bool {
	if o != nil && !IsNil(o.IncludeMetadata) {
		return true
	}

	return false
}

// SetIncludeMetadata gets a reference to the given bool and assigns it to the IncludeMetadata field.
func (o *TypesDiskRequest) SetIncludeMetadata(v bool) {
	o.IncludeMetadata = &v
}

// GetInstance returns the Instance field value if set, zero value otherwise.
func (o *TypesDiskRequest) GetInstance() TypesDisk {
	if o == nil || IsNil(o.Instance) {
		var ret TypesDisk
		return ret
	}
	return *o.Instance
}

// GetInstanceOk returns a tuple with the Instance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TypesDiskRequest) GetInstanceOk() (*TypesDisk, bool) {
	if o == nil || IsNil(o.Instance) {
		return nil, false
	}
	return o.Instance, true
}

// HasInstance returns a boolean if a field has been set.
func (o *TypesDiskRequest) HasInstance() bool {
	if o != nil && !IsNil(o.Instance) {
		return true
	}

	return false
}

// SetInstance gets a reference to the given TypesDisk and assigns it to the Instance field.
func (o *TypesDiskRequest) SetInstance(v TypesDisk) {
	o.Instance = &v
}

// GetPredicates returns the Predicates field value if set, zero value otherwise.
func (o *TypesDiskRequest) GetPredicates() TypesPredicates {
	if o == nil || IsNil(o.Predicates) {
		var ret TypesPredicates
		return ret
	}
	return *o.Predicates
}

// GetPredicatesOk returns a tuple with the Predicates field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TypesDiskRequest) GetPredicatesOk() (*TypesPredicates, bool) {
	if o == nil || IsNil(o.Predicates) {
		return nil, false
	}
	return o.Predicates, true
}

// HasPredicates returns a boolean if a field has been set.
func (o *TypesDiskRequest) HasPredicates() bool {
	if o != nil && !IsNil(o.Predicates) {
		return true
	}

	return false
}

// SetPredicates gets a reference to the given TypesPredicates and assigns it to the Predicates field.
func (o *TypesDiskRequest) SetPredicates(v TypesPredicates) {
	o.Predicates = &v
}

// GetUsage returns the Usage field value if set, zero value otherwise.
func (o *TypesDiskRequest) GetUsage() TypesDisk {
	if o == nil || IsNil(o.Usage) {
		var ret TypesDisk
		return ret
	}
	return *o.Usage
}

// GetUsageOk returns a tuple with the Usage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TypesDiskRequest) GetUsageOk() (*TypesDisk, bool) {
	if o == nil || IsNil(o.Usage) {
		return nil, false
	}
	return o.Usage, true
}

// HasUsage returns a boolean if a field has been set.
func (o *TypesDiskRequest) HasUsage() bool {
	if o != nil && !IsNil(o.Usage) {
		return true
	}

	return false
}

// SetUsage gets a reference to the given TypesDisk and assigns it to the Usage field.
func (o *TypesDiskRequest) SetUsage(v TypesDisk) {
	o.Usage = &v
}

func (o TypesDiskRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TypesDiskRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.IncludeMetadata) {
		toSerialize["include_metadata"] = o.IncludeMetadata
	}
	if !IsNil(o.Instance) {
		toSerialize["instance"] = o.Instance
	}
	if !IsNil(o.Predicates) {
		toSerialize["predicates"] = o.Predicates
	}
	if !IsNil(o.Usage) {
		toSerialize["usage"] = o.Usage
	}
	return toSerialize, nil
}

type NullableTypesDiskRequest struct {
	value *TypesDiskRequest
	isSet bool
}

func (v NullableTypesDiskRequest) Get() *TypesDiskRequest {
	return v.value
}

func (v *NullableTypesDiskRequest) Set(val *TypesDiskRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableTypesDiskRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableTypesDiskRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTypesDiskRequest(val *TypesDiskRequest) *NullableTypesDiskRequest {
	return &NullableTypesDiskRequest{value: val, isSet: true}
}

func (v NullableTypesDiskRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTypesDiskRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


