/*
Pricing API

Provides API level access to the Costgraph Services.

API version: 1.0
Contact: contact@baselinehq.cloud
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pricing_api_client

import (
	"encoding/json"
	"fmt"
)

// GithubComBaselinehqGolangSharedTypesUsageType the model 'GithubComBaselinehqGolangSharedTypesUsageType'
type GithubComBaselinehqGolangSharedTypesUsageType string

// List of github_com_baselinehq_golang-shared_types.UsageType
const (
	SPOT_PREEMPTIBLE GithubComBaselinehqGolangSharedTypesUsageType = "SPOT_PREEMPTIBLE"
	ONDEMAND GithubComBaselinehqGolangSharedTypesUsageType = "ONDEMAND"
	RESERVED GithubComBaselinehqGolangSharedTypesUsageType = "RESERVED"
	ONDEMAND_CUSTOM GithubComBaselinehqGolangSharedTypesUsageType = "ONDEMAND_CUSTOM"
	SPOT_PREEMPTIBLE_CUSTOM GithubComBaselinehqGolangSharedTypesUsageType = "SPOT_PREEMPTIBLE_CUSTOM"
	RESERVED_CUSTOM GithubComBaselinehqGolangSharedTypesUsageType = "RESERVED_CUSTOM"
	SOLE_TENANCY GithubComBaselinehqGolangSharedTypesUsageType = "SOLE_TENANCY"
	CUSTOM GithubComBaselinehqGolangSharedTypesUsageType = "CUSTOM"
	EXTENDED GithubComBaselinehqGolangSharedTypesUsageType = "EXTENDED"
)

// All allowed values of GithubComBaselinehqGolangSharedTypesUsageType enum
var AllowedGithubComBaselinehqGolangSharedTypesUsageTypeEnumValues = []GithubComBaselinehqGolangSharedTypesUsageType{
	"SPOT_PREEMPTIBLE",
	"ONDEMAND",
	"RESERVED",
	"ONDEMAND_CUSTOM",
	"SPOT_PREEMPTIBLE_CUSTOM",
	"RESERVED_CUSTOM",
	"SOLE_TENANCY",
	"CUSTOM",
	"EXTENDED",
}

func (v *GithubComBaselinehqGolangSharedTypesUsageType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := GithubComBaselinehqGolangSharedTypesUsageType(value)
	for _, existing := range AllowedGithubComBaselinehqGolangSharedTypesUsageTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid GithubComBaselinehqGolangSharedTypesUsageType", value)
}

// NewGithubComBaselinehqGolangSharedTypesUsageTypeFromValue returns a pointer to a valid GithubComBaselinehqGolangSharedTypesUsageType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewGithubComBaselinehqGolangSharedTypesUsageTypeFromValue(v string) (*GithubComBaselinehqGolangSharedTypesUsageType, error) {
	ev := GithubComBaselinehqGolangSharedTypesUsageType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for GithubComBaselinehqGolangSharedTypesUsageType: valid values are %v", v, AllowedGithubComBaselinehqGolangSharedTypesUsageTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v GithubComBaselinehqGolangSharedTypesUsageType) IsValid() bool {
	for _, existing := range AllowedGithubComBaselinehqGolangSharedTypesUsageTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to github_com_baselinehq_golang-shared_types.UsageType value
func (v GithubComBaselinehqGolangSharedTypesUsageType) Ptr() *GithubComBaselinehqGolangSharedTypesUsageType {
	return &v
}

type NullableGithubComBaselinehqGolangSharedTypesUsageType struct {
	value *GithubComBaselinehqGolangSharedTypesUsageType
	isSet bool
}

func (v NullableGithubComBaselinehqGolangSharedTypesUsageType) Get() *GithubComBaselinehqGolangSharedTypesUsageType {
	return v.value
}

func (v *NullableGithubComBaselinehqGolangSharedTypesUsageType) Set(val *GithubComBaselinehqGolangSharedTypesUsageType) {
	v.value = val
	v.isSet = true
}

func (v NullableGithubComBaselinehqGolangSharedTypesUsageType) IsSet() bool {
	return v.isSet
}

func (v *NullableGithubComBaselinehqGolangSharedTypesUsageType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGithubComBaselinehqGolangSharedTypesUsageType(val *GithubComBaselinehqGolangSharedTypesUsageType) *NullableGithubComBaselinehqGolangSharedTypesUsageType {
	return &NullableGithubComBaselinehqGolangSharedTypesUsageType{value: val, isSet: true}
}

func (v NullableGithubComBaselinehqGolangSharedTypesUsageType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGithubComBaselinehqGolangSharedTypesUsageType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

