/*
Pricing API

Provides API level access to the Costgraph Services.

API version: 1.0
Contact: support@costgraph.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pricing_api_client

import (
	"encoding/json"
	"fmt"
)

// RegistrationStatus the model 'RegistrationStatus'
type RegistrationStatus string

// List of RegistrationStatus
const (
	Registered RegistrationStatus = "Registered"
	Deleted    RegistrationStatus = "Deleted"
)

// All allowed values of RegistrationStatus enum
var AllowedRegistrationStatusEnumValues = []RegistrationStatus{
	"Registered",
	"Deleted",
}

func (v *RegistrationStatus) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := RegistrationStatus(value)
	for _, existing := range AllowedRegistrationStatusEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid RegistrationStatus", value)
}

// NewRegistrationStatusFromValue returns a pointer to a valid RegistrationStatus
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewRegistrationStatusFromValue(v string) (*RegistrationStatus, error) {
	ev := RegistrationStatus(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for RegistrationStatus: valid values are %v", v, AllowedRegistrationStatusEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v RegistrationStatus) IsValid() bool {
	for _, existing := range AllowedRegistrationStatusEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to RegistrationStatus value
func (v RegistrationStatus) Ptr() *RegistrationStatus {
	return &v
}

type NullableRegistrationStatus struct {
	value *RegistrationStatus
	isSet bool
}

func (v NullableRegistrationStatus) Get() *RegistrationStatus {
	return v.value
}

func (v *NullableRegistrationStatus) Set(val *RegistrationStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableRegistrationStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableRegistrationStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRegistrationStatus(val *RegistrationStatus) *NullableRegistrationStatus {
	return &NullableRegistrationStatus{value: val, isSet: true}
}

func (v NullableRegistrationStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRegistrationStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
