/*
Pricing API

Provides API level access to the Costgraph Services.

API version: 1.0
Contact: contact@baselinehq.cloud
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pricing_api_client

import (
	"encoding/json"
	"fmt"
)

// GithubComBaselinehqGolangSharedTypesProvider the model 'GithubComBaselinehqGolangSharedTypesProvider'
type GithubComBaselinehqGolangSharedTypesProvider string

// List of github_com_baselinehq_golang-shared_types.Provider
const (
	GCP GithubComBaselinehqGolangSharedTypesProvider = "GCP"
	AWS GithubComBaselinehqGolangSharedTypesProvider = "AWS"
	DigitalOcean GithubComBaselinehqGolangSharedTypesProvider = "DigitalOcean"
	Azure GithubComBaselinehqGolangSharedTypesProvider = "Azure"
	Hetzner GithubComBaselinehqGolangSharedTypesProvider = "Hetzner"
	OVHCloud GithubComBaselinehqGolangSharedTypesProvider = "OVHCloud"
	Base GithubComBaselinehqGolangSharedTypesProvider = "Base"
)

// All allowed values of GithubComBaselinehqGolangSharedTypesProvider enum
var AllowedGithubComBaselinehqGolangSharedTypesProviderEnumValues = []GithubComBaselinehqGolangSharedTypesProvider{
	"GCP",
	"AWS",
	"DigitalOcean",
	"Azure",
	"Hetzner",
	"OVHCloud",
	"Base",
}

func (v *GithubComBaselinehqGolangSharedTypesProvider) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := GithubComBaselinehqGolangSharedTypesProvider(value)
	for _, existing := range AllowedGithubComBaselinehqGolangSharedTypesProviderEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid GithubComBaselinehqGolangSharedTypesProvider", value)
}

// NewGithubComBaselinehqGolangSharedTypesProviderFromValue returns a pointer to a valid GithubComBaselinehqGolangSharedTypesProvider
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewGithubComBaselinehqGolangSharedTypesProviderFromValue(v string) (*GithubComBaselinehqGolangSharedTypesProvider, error) {
	ev := GithubComBaselinehqGolangSharedTypesProvider(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for GithubComBaselinehqGolangSharedTypesProvider: valid values are %v", v, AllowedGithubComBaselinehqGolangSharedTypesProviderEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v GithubComBaselinehqGolangSharedTypesProvider) IsValid() bool {
	for _, existing := range AllowedGithubComBaselinehqGolangSharedTypesProviderEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to github_com_baselinehq_golang-shared_types.Provider value
func (v GithubComBaselinehqGolangSharedTypesProvider) Ptr() *GithubComBaselinehqGolangSharedTypesProvider {
	return &v
}

type NullableGithubComBaselinehqGolangSharedTypesProvider struct {
	value *GithubComBaselinehqGolangSharedTypesProvider
	isSet bool
}

func (v NullableGithubComBaselinehqGolangSharedTypesProvider) Get() *GithubComBaselinehqGolangSharedTypesProvider {
	return v.value
}

func (v *NullableGithubComBaselinehqGolangSharedTypesProvider) Set(val *GithubComBaselinehqGolangSharedTypesProvider) {
	v.value = val
	v.isSet = true
}

func (v NullableGithubComBaselinehqGolangSharedTypesProvider) IsSet() bool {
	return v.isSet
}

func (v *NullableGithubComBaselinehqGolangSharedTypesProvider) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGithubComBaselinehqGolangSharedTypesProvider(val *GithubComBaselinehqGolangSharedTypesProvider) *NullableGithubComBaselinehqGolangSharedTypesProvider {
	return &NullableGithubComBaselinehqGolangSharedTypesProvider{value: val, isSet: true}
}

func (v NullableGithubComBaselinehqGolangSharedTypesProvider) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGithubComBaselinehqGolangSharedTypesProvider) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

