/*
Pricing API

Provides API level access to the Costgraph Services.

API version: 1.0
Contact: support@costgraph.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pricing_api_client

import (
	"encoding/json"
)

// checks if the RegisteredComputePrices type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RegisteredComputePrices{}

// RegisteredComputePrices struct for RegisteredComputePrices
type RegisteredComputePrices struct {
	Entries []ComputePrice      `json:"entries,omitempty"`
	Status  *RegistrationStatus `json:"status,omitempty"`
}

// NewRegisteredComputePrices instantiates a new RegisteredComputePrices object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRegisteredComputePrices() *RegisteredComputePrices {
	this := RegisteredComputePrices{}
	return &this
}

// NewRegisteredComputePricesWithDefaults instantiates a new RegisteredComputePrices object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRegisteredComputePricesWithDefaults() *RegisteredComputePrices {
	this := RegisteredComputePrices{}
	return &this
}

// GetEntries returns the Entries field value if set, zero value otherwise.
func (o *RegisteredComputePrices) GetEntries() []ComputePrice {
	if o == nil || IsNil(o.Entries) {
		var ret []ComputePrice
		return ret
	}
	return o.Entries
}

// GetEntriesOk returns a tuple with the Entries field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegisteredComputePrices) GetEntriesOk() ([]ComputePrice, bool) {
	if o == nil || IsNil(o.Entries) {
		return nil, false
	}
	return o.Entries, true
}

// HasEntries returns a boolean if a field has been set.
func (o *RegisteredComputePrices) HasEntries() bool {
	if o != nil && !IsNil(o.Entries) {
		return true
	}

	return false
}

// SetEntries gets a reference to the given []ComputePrice and assigns it to the Entries field.
func (o *RegisteredComputePrices) SetEntries(v []ComputePrice) {
	o.Entries = v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *RegisteredComputePrices) GetStatus() RegistrationStatus {
	if o == nil || IsNil(o.Status) {
		var ret RegistrationStatus
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegisteredComputePrices) GetStatusOk() (*RegistrationStatus, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *RegisteredComputePrices) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given RegistrationStatus and assigns it to the Status field.
func (o *RegisteredComputePrices) SetStatus(v RegistrationStatus) {
	o.Status = &v
}

func (o RegisteredComputePrices) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RegisteredComputePrices) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Entries) {
		toSerialize["entries"] = o.Entries
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableRegisteredComputePrices struct {
	value *RegisteredComputePrices
	isSet bool
}

func (v NullableRegisteredComputePrices) Get() *RegisteredComputePrices {
	return v.value
}

func (v *NullableRegisteredComputePrices) Set(val *RegisteredComputePrices) {
	v.value = val
	v.isSet = true
}

func (v NullableRegisteredComputePrices) IsSet() bool {
	return v.isSet
}

func (v *NullableRegisteredComputePrices) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRegisteredComputePrices(val *RegisteredComputePrices) *NullableRegisteredComputePrices {
	return &NullableRegisteredComputePrices{value: val, isSet: true}
}

func (v NullableRegisteredComputePrices) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRegisteredComputePrices) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
