/*
Pricing API

Provides API level access to the Costgraph Services.

API version: 1.0
Contact: contact@baselinehq.cloud
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pricing_api_client

import (
	"encoding/json"
)

// checks if the ProviderConfigs type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProviderConfigs{}

// ProviderConfigs struct for ProviderConfigs
type ProviderConfigs struct {
	AdditionalProperties map[string]interface{}
}

type _ProviderConfigs ProviderConfigs

// NewProviderConfigs instantiates a new ProviderConfigs object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProviderConfigs() *ProviderConfigs {
	this := ProviderConfigs{}
	return &this
}

// NewProviderConfigsWithDefaults instantiates a new ProviderConfigs object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProviderConfigsWithDefaults() *ProviderConfigs {
	this := ProviderConfigs{}
	return &this
}

func (o ProviderConfigs) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProviderConfigs) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ProviderConfigs) UnmarshalJSON(data []byte) (err error) {
	varProviderConfigs := _ProviderConfigs{}

	err = json.Unmarshal(data, &varProviderConfigs)

	if err != nil {
		return err
	}

	*o = ProviderConfigs(varProviderConfigs)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableProviderConfigs struct {
	value *ProviderConfigs
	isSet bool
}

func (v NullableProviderConfigs) Get() *ProviderConfigs {
	return v.value
}

func (v *NullableProviderConfigs) Set(val *ProviderConfigs) {
	v.value = val
	v.isSet = true
}

func (v NullableProviderConfigs) IsSet() bool {
	return v.isSet
}

func (v *NullableProviderConfigs) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProviderConfigs(val *ProviderConfigs) *NullableProviderConfigs {
	return &NullableProviderConfigs{value: val, isSet: true}
}

func (v NullableProviderConfigs) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProviderConfigs) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


