/*
Pricing API

Provides API level access to the Costgraph Services.

API version: 1.0
Contact: contact@baselinehq.cloud
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pricing_api_client

import (
	"encoding/json"
)

// checks if the GithubComBaselinehqGolangSharedTypesVM type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GithubComBaselinehqGolangSharedTypesVM{}

// GithubComBaselinehqGolangSharedTypesVM struct for GithubComBaselinehqGolangSharedTypesVM
type GithubComBaselinehqGolangSharedTypesVM struct {
	CpuCores *float32 `json:"cpu_cores,omitempty"`
	RamGb *float32 `json:"ram_gb,omitempty"`
}

// NewGithubComBaselinehqGolangSharedTypesVM instantiates a new GithubComBaselinehqGolangSharedTypesVM object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGithubComBaselinehqGolangSharedTypesVM() *GithubComBaselinehqGolangSharedTypesVM {
	this := GithubComBaselinehqGolangSharedTypesVM{}
	return &this
}

// NewGithubComBaselinehqGolangSharedTypesVMWithDefaults instantiates a new GithubComBaselinehqGolangSharedTypesVM object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGithubComBaselinehqGolangSharedTypesVMWithDefaults() *GithubComBaselinehqGolangSharedTypesVM {
	this := GithubComBaselinehqGolangSharedTypesVM{}
	return &this
}

// GetCpuCores returns the CpuCores field value if set, zero value otherwise.
func (o *GithubComBaselinehqGolangSharedTypesVM) GetCpuCores() float32 {
	if o == nil || IsNil(o.CpuCores) {
		var ret float32
		return ret
	}
	return *o.CpuCores
}

// GetCpuCoresOk returns a tuple with the CpuCores field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GithubComBaselinehqGolangSharedTypesVM) GetCpuCoresOk() (*float32, bool) {
	if o == nil || IsNil(o.CpuCores) {
		return nil, false
	}
	return o.CpuCores, true
}

// HasCpuCores returns a boolean if a field has been set.
func (o *GithubComBaselinehqGolangSharedTypesVM) HasCpuCores() bool {
	if o != nil && !IsNil(o.CpuCores) {
		return true
	}

	return false
}

// SetCpuCores gets a reference to the given float32 and assigns it to the CpuCores field.
func (o *GithubComBaselinehqGolangSharedTypesVM) SetCpuCores(v float32) {
	o.CpuCores = &v
}

// GetRamGb returns the RamGb field value if set, zero value otherwise.
func (o *GithubComBaselinehqGolangSharedTypesVM) GetRamGb() float32 {
	if o == nil || IsNil(o.RamGb) {
		var ret float32
		return ret
	}
	return *o.RamGb
}

// GetRamGbOk returns a tuple with the RamGb field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GithubComBaselinehqGolangSharedTypesVM) GetRamGbOk() (*float32, bool) {
	if o == nil || IsNil(o.RamGb) {
		return nil, false
	}
	return o.RamGb, true
}

// HasRamGb returns a boolean if a field has been set.
func (o *GithubComBaselinehqGolangSharedTypesVM) HasRamGb() bool {
	if o != nil && !IsNil(o.RamGb) {
		return true
	}

	return false
}

// SetRamGb gets a reference to the given float32 and assigns it to the RamGb field.
func (o *GithubComBaselinehqGolangSharedTypesVM) SetRamGb(v float32) {
	o.RamGb = &v
}

func (o GithubComBaselinehqGolangSharedTypesVM) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GithubComBaselinehqGolangSharedTypesVM) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CpuCores) {
		toSerialize["cpu_cores"] = o.CpuCores
	}
	if !IsNil(o.RamGb) {
		toSerialize["ram_gb"] = o.RamGb
	}
	return toSerialize, nil
}

type NullableGithubComBaselinehqGolangSharedTypesVM struct {
	value *GithubComBaselinehqGolangSharedTypesVM
	isSet bool
}

func (v NullableGithubComBaselinehqGolangSharedTypesVM) Get() *GithubComBaselinehqGolangSharedTypesVM {
	return v.value
}

func (v *NullableGithubComBaselinehqGolangSharedTypesVM) Set(val *GithubComBaselinehqGolangSharedTypesVM) {
	v.value = val
	v.isSet = true
}

func (v NullableGithubComBaselinehqGolangSharedTypesVM) IsSet() bool {
	return v.isSet
}

func (v *NullableGithubComBaselinehqGolangSharedTypesVM) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGithubComBaselinehqGolangSharedTypesVM(val *GithubComBaselinehqGolangSharedTypesVM) *NullableGithubComBaselinehqGolangSharedTypesVM {
	return &NullableGithubComBaselinehqGolangSharedTypesVM{value: val, isSet: true}
}

func (v NullableGithubComBaselinehqGolangSharedTypesVM) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGithubComBaselinehqGolangSharedTypesVM) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


