/*
Pricing API

Provides API level access to the Costgraph Services.

API version: 1.0
Contact: support@costgraph.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pricing_api_client

import (
	"encoding/json"
)

// checks if the RegisteredModelPrices type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RegisteredModelPrices{}

// RegisteredModelPrices struct for RegisteredModelPrices
type RegisteredModelPrices struct {
	Entries []ModelPrice        `json:"entries,omitempty"`
	Status  *RegistrationStatus `json:"status,omitempty"`
}

// NewRegisteredModelPrices instantiates a new RegisteredModelPrices object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRegisteredModelPrices() *RegisteredModelPrices {
	this := RegisteredModelPrices{}
	return &this
}

// NewRegisteredModelPricesWithDefaults instantiates a new RegisteredModelPrices object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRegisteredModelPricesWithDefaults() *RegisteredModelPrices {
	this := RegisteredModelPrices{}
	return &this
}

// GetEntries returns the Entries field value if set, zero value otherwise.
func (o *RegisteredModelPrices) GetEntries() []ModelPrice {
	if o == nil || IsNil(o.Entries) {
		var ret []ModelPrice
		return ret
	}
	return o.Entries
}

// GetEntriesOk returns a tuple with the Entries field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegisteredModelPrices) GetEntriesOk() ([]ModelPrice, bool) {
	if o == nil || IsNil(o.Entries) {
		return nil, false
	}
	return o.Entries, true
}

// HasEntries returns a boolean if a field has been set.
func (o *RegisteredModelPrices) HasEntries() bool {
	if o != nil && !IsNil(o.Entries) {
		return true
	}

	return false
}

// SetEntries gets a reference to the given []ModelPrice and assigns it to the Entries field.
func (o *RegisteredModelPrices) SetEntries(v []ModelPrice) {
	o.Entries = v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *RegisteredModelPrices) GetStatus() RegistrationStatus {
	if o == nil || IsNil(o.Status) {
		var ret RegistrationStatus
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegisteredModelPrices) GetStatusOk() (*RegistrationStatus, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *RegisteredModelPrices) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given RegistrationStatus and assigns it to the Status field.
func (o *RegisteredModelPrices) SetStatus(v RegistrationStatus) {
	o.Status = &v
}

func (o RegisteredModelPrices) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RegisteredModelPrices) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Entries) {
		toSerialize["entries"] = o.Entries
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableRegisteredModelPrices struct {
	value *RegisteredModelPrices
	isSet bool
}

func (v NullableRegisteredModelPrices) Get() *RegisteredModelPrices {
	return v.value
}

func (v *NullableRegisteredModelPrices) Set(val *RegisteredModelPrices) {
	v.value = val
	v.isSet = true
}

func (v NullableRegisteredModelPrices) IsSet() bool {
	return v.isSet
}

func (v *NullableRegisteredModelPrices) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRegisteredModelPrices(val *RegisteredModelPrices) *NullableRegisteredModelPrices {
	return &NullableRegisteredModelPrices{value: val, isSet: true}
}

func (v NullableRegisteredModelPrices) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRegisteredModelPrices) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
