/*
Pricing API

Provides API level access to the Costgraph Services.

API version: 1.0
Contact: contact@baselinehq.cloud
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pricing_api_client

import (
	"encoding/json"
)

// checks if the TypesMarketplaceDiskProvidersResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TypesMarketplaceDiskProvidersResponse{}

// TypesMarketplaceDiskProvidersResponse struct for TypesMarketplaceDiskProvidersResponse
type TypesMarketplaceDiskProvidersResponse struct {
	Providers []SchemaDiskPricingsRow `json:"providers,omitempty"`
}

// NewTypesMarketplaceDiskProvidersResponse instantiates a new TypesMarketplaceDiskProvidersResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTypesMarketplaceDiskProvidersResponse() *TypesMarketplaceDiskProvidersResponse {
	this := TypesMarketplaceDiskProvidersResponse{}
	return &this
}

// NewTypesMarketplaceDiskProvidersResponseWithDefaults instantiates a new TypesMarketplaceDiskProvidersResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTypesMarketplaceDiskProvidersResponseWithDefaults() *TypesMarketplaceDiskProvidersResponse {
	this := TypesMarketplaceDiskProvidersResponse{}
	return &this
}

// GetProviders returns the Providers field value if set, zero value otherwise.
func (o *TypesMarketplaceDiskProvidersResponse) GetProviders() []SchemaDiskPricingsRow {
	if o == nil || IsNil(o.Providers) {
		var ret []SchemaDiskPricingsRow
		return ret
	}
	return o.Providers
}

// GetProvidersOk returns a tuple with the Providers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TypesMarketplaceDiskProvidersResponse) GetProvidersOk() ([]SchemaDiskPricingsRow, bool) {
	if o == nil || IsNil(o.Providers) {
		return nil, false
	}
	return o.Providers, true
}

// HasProviders returns a boolean if a field has been set.
func (o *TypesMarketplaceDiskProvidersResponse) HasProviders() bool {
	if o != nil && !IsNil(o.Providers) {
		return true
	}

	return false
}

// SetProviders gets a reference to the given []SchemaDiskPricingsRow and assigns it to the Providers field.
func (o *TypesMarketplaceDiskProvidersResponse) SetProviders(v []SchemaDiskPricingsRow) {
	o.Providers = v
}

func (o TypesMarketplaceDiskProvidersResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TypesMarketplaceDiskProvidersResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Providers) {
		toSerialize["providers"] = o.Providers
	}
	return toSerialize, nil
}

type NullableTypesMarketplaceDiskProvidersResponse struct {
	value *TypesMarketplaceDiskProvidersResponse
	isSet bool
}

func (v NullableTypesMarketplaceDiskProvidersResponse) Get() *TypesMarketplaceDiskProvidersResponse {
	return v.value
}

func (v *NullableTypesMarketplaceDiskProvidersResponse) Set(val *TypesMarketplaceDiskProvidersResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableTypesMarketplaceDiskProvidersResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableTypesMarketplaceDiskProvidersResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTypesMarketplaceDiskProvidersResponse(val *TypesMarketplaceDiskProvidersResponse) *NullableTypesMarketplaceDiskProvidersResponse {
	return &NullableTypesMarketplaceDiskProvidersResponse{value: val, isSet: true}
}

func (v NullableTypesMarketplaceDiskProvidersResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTypesMarketplaceDiskProvidersResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
