/*
Pricing API

Provides API level access to the Costgraph Services.

API version: 1.0
Contact: support@costgraph.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pricing_api_client

import (
	"encoding/json"
)

// checks if the PublishedDatabasePrices type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PublishedDatabasePrices{}

// PublishedDatabasePrices struct for PublishedDatabasePrices
type PublishedDatabasePrices struct {
	Data []DatabasePrice `json:"data,omitempty"`
}

// NewPublishedDatabasePrices instantiates a new PublishedDatabasePrices object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPublishedDatabasePrices() *PublishedDatabasePrices {
	this := PublishedDatabasePrices{}
	return &this
}

// NewPublishedDatabasePricesWithDefaults instantiates a new PublishedDatabasePrices object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPublishedDatabasePricesWithDefaults() *PublishedDatabasePrices {
	this := PublishedDatabasePrices{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *PublishedDatabasePrices) GetData() []DatabasePrice {
	if o == nil || IsNil(o.Data) {
		var ret []DatabasePrice
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PublishedDatabasePrices) GetDataOk() ([]DatabasePrice, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *PublishedDatabasePrices) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []DatabasePrice and assigns it to the Data field.
func (o *PublishedDatabasePrices) SetData(v []DatabasePrice) {
	o.Data = v
}

func (o PublishedDatabasePrices) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PublishedDatabasePrices) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullablePublishedDatabasePrices struct {
	value *PublishedDatabasePrices
	isSet bool
}

func (v NullablePublishedDatabasePrices) Get() *PublishedDatabasePrices {
	return v.value
}

func (v *NullablePublishedDatabasePrices) Set(val *PublishedDatabasePrices) {
	v.value = val
	v.isSet = true
}

func (v NullablePublishedDatabasePrices) IsSet() bool {
	return v.isSet
}

func (v *NullablePublishedDatabasePrices) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePublishedDatabasePrices(val *PublishedDatabasePrices) *NullablePublishedDatabasePrices {
	return &NullablePublishedDatabasePrices{value: val, isSet: true}
}

func (v NullablePublishedDatabasePrices) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePublishedDatabasePrices) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
