/*
Pricing API

Provides API level access to the Costgraph Services.

API version: 1.0
Contact: contact@baselinehq.cloud
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pricing_api_client

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the TypesCustomDiskPriceRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TypesCustomDiskPriceRequest{}

// TypesCustomDiskPriceRequest struct for TypesCustomDiskPriceRequest
type TypesCustomDiskPriceRequest struct {
	Entries []SchemaDiskPricingsRow `json:"entries"`
}

type _TypesCustomDiskPriceRequest TypesCustomDiskPriceRequest

// NewTypesCustomDiskPriceRequest instantiates a new TypesCustomDiskPriceRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTypesCustomDiskPriceRequest(entries []SchemaDiskPricingsRow) *TypesCustomDiskPriceRequest {
	this := TypesCustomDiskPriceRequest{}
	this.Entries = entries
	return &this
}

// NewTypesCustomDiskPriceRequestWithDefaults instantiates a new TypesCustomDiskPriceRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTypesCustomDiskPriceRequestWithDefaults() *TypesCustomDiskPriceRequest {
	this := TypesCustomDiskPriceRequest{}
	return &this
}

// GetEntries returns the Entries field value
func (o *TypesCustomDiskPriceRequest) GetEntries() []SchemaDiskPricingsRow {
	if o == nil {
		var ret []SchemaDiskPricingsRow
		return ret
	}

	return o.Entries
}

// GetEntriesOk returns a tuple with the Entries field value
// and a boolean to check if the value has been set.
func (o *TypesCustomDiskPriceRequest) GetEntriesOk() ([]SchemaDiskPricingsRow, bool) {
	if o == nil {
		return nil, false
	}
	return o.Entries, true
}

// SetEntries sets field value
func (o *TypesCustomDiskPriceRequest) SetEntries(v []SchemaDiskPricingsRow) {
	o.Entries = v
}

func (o TypesCustomDiskPriceRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TypesCustomDiskPriceRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["entries"] = o.Entries
	return toSerialize, nil
}

func (o *TypesCustomDiskPriceRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"entries",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTypesCustomDiskPriceRequest := _TypesCustomDiskPriceRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTypesCustomDiskPriceRequest)

	if err != nil {
		return err
	}

	*o = TypesCustomDiskPriceRequest(varTypesCustomDiskPriceRequest)

	return err
}

type NullableTypesCustomDiskPriceRequest struct {
	value *TypesCustomDiskPriceRequest
	isSet bool
}

func (v NullableTypesCustomDiskPriceRequest) Get() *TypesCustomDiskPriceRequest {
	return v.value
}

func (v *NullableTypesCustomDiskPriceRequest) Set(val *TypesCustomDiskPriceRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableTypesCustomDiskPriceRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableTypesCustomDiskPriceRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTypesCustomDiskPriceRequest(val *TypesCustomDiskPriceRequest) *NullableTypesCustomDiskPriceRequest {
	return &NullableTypesCustomDiskPriceRequest{value: val, isSet: true}
}

func (v NullableTypesCustomDiskPriceRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTypesCustomDiskPriceRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
