/*
Pricing API

Provides API level access to the Costgraph Services.

API version: 1.0
Contact: contact@baselinehq.cloud
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pricing_api_client

import (
	"encoding/json"
)

// checks if the TypesPredicates type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TypesPredicates{}

// TypesPredicates struct for TypesPredicates
type TypesPredicates struct {
	AvailabilityZones []string `json:"availability_zones,omitempty"`
	DiskTypes []string `json:"disk_types,omitempty"`
	InstanceTypes []string `json:"instance_types,omitempty"`
	OperatingSystems []string `json:"operating_systems,omitempty"`
	Providers []string `json:"providers,omitempty"`
	Regions []string `json:"regions,omitempty"`
	Services []string `json:"services,omitempty"`
	UsageTypes []string `json:"usage_types,omitempty"`
}

// NewTypesPredicates instantiates a new TypesPredicates object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTypesPredicates() *TypesPredicates {
	this := TypesPredicates{}
	return &this
}

// NewTypesPredicatesWithDefaults instantiates a new TypesPredicates object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTypesPredicatesWithDefaults() *TypesPredicates {
	this := TypesPredicates{}
	return &this
}

// GetAvailabilityZones returns the AvailabilityZones field value if set, zero value otherwise.
func (o *TypesPredicates) GetAvailabilityZones() []string {
	if o == nil || IsNil(o.AvailabilityZones) {
		var ret []string
		return ret
	}
	return o.AvailabilityZones
}

// GetAvailabilityZonesOk returns a tuple with the AvailabilityZones field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TypesPredicates) GetAvailabilityZonesOk() ([]string, bool) {
	if o == nil || IsNil(o.AvailabilityZones) {
		return nil, false
	}
	return o.AvailabilityZones, true
}

// HasAvailabilityZones returns a boolean if a field has been set.
func (o *TypesPredicates) HasAvailabilityZones() bool {
	if o != nil && !IsNil(o.AvailabilityZones) {
		return true
	}

	return false
}

// SetAvailabilityZones gets a reference to the given []string and assigns it to the AvailabilityZones field.
func (o *TypesPredicates) SetAvailabilityZones(v []string) {
	o.AvailabilityZones = v
}

// GetDiskTypes returns the DiskTypes field value if set, zero value otherwise.
func (o *TypesPredicates) GetDiskTypes() []string {
	if o == nil || IsNil(o.DiskTypes) {
		var ret []string
		return ret
	}
	return o.DiskTypes
}

// GetDiskTypesOk returns a tuple with the DiskTypes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TypesPredicates) GetDiskTypesOk() ([]string, bool) {
	if o == nil || IsNil(o.DiskTypes) {
		return nil, false
	}
	return o.DiskTypes, true
}

// HasDiskTypes returns a boolean if a field has been set.
func (o *TypesPredicates) HasDiskTypes() bool {
	if o != nil && !IsNil(o.DiskTypes) {
		return true
	}

	return false
}

// SetDiskTypes gets a reference to the given []string and assigns it to the DiskTypes field.
func (o *TypesPredicates) SetDiskTypes(v []string) {
	o.DiskTypes = v
}

// GetInstanceTypes returns the InstanceTypes field value if set, zero value otherwise.
func (o *TypesPredicates) GetInstanceTypes() []string {
	if o == nil || IsNil(o.InstanceTypes) {
		var ret []string
		return ret
	}
	return o.InstanceTypes
}

// GetInstanceTypesOk returns a tuple with the InstanceTypes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TypesPredicates) GetInstanceTypesOk() ([]string, bool) {
	if o == nil || IsNil(o.InstanceTypes) {
		return nil, false
	}
	return o.InstanceTypes, true
}

// HasInstanceTypes returns a boolean if a field has been set.
func (o *TypesPredicates) HasInstanceTypes() bool {
	if o != nil && !IsNil(o.InstanceTypes) {
		return true
	}

	return false
}

// SetInstanceTypes gets a reference to the given []string and assigns it to the InstanceTypes field.
func (o *TypesPredicates) SetInstanceTypes(v []string) {
	o.InstanceTypes = v
}

// GetOperatingSystems returns the OperatingSystems field value if set, zero value otherwise.
func (o *TypesPredicates) GetOperatingSystems() []string {
	if o == nil || IsNil(o.OperatingSystems) {
		var ret []string
		return ret
	}
	return o.OperatingSystems
}

// GetOperatingSystemsOk returns a tuple with the OperatingSystems field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TypesPredicates) GetOperatingSystemsOk() ([]string, bool) {
	if o == nil || IsNil(o.OperatingSystems) {
		return nil, false
	}
	return o.OperatingSystems, true
}

// HasOperatingSystems returns a boolean if a field has been set.
func (o *TypesPredicates) HasOperatingSystems() bool {
	if o != nil && !IsNil(o.OperatingSystems) {
		return true
	}

	return false
}

// SetOperatingSystems gets a reference to the given []string and assigns it to the OperatingSystems field.
func (o *TypesPredicates) SetOperatingSystems(v []string) {
	o.OperatingSystems = v
}

// GetProviders returns the Providers field value if set, zero value otherwise.
func (o *TypesPredicates) GetProviders() []string {
	if o == nil || IsNil(o.Providers) {
		var ret []string
		return ret
	}
	return o.Providers
}

// GetProvidersOk returns a tuple with the Providers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TypesPredicates) GetProvidersOk() ([]string, bool) {
	if o == nil || IsNil(o.Providers) {
		return nil, false
	}
	return o.Providers, true
}

// HasProviders returns a boolean if a field has been set.
func (o *TypesPredicates) HasProviders() bool {
	if o != nil && !IsNil(o.Providers) {
		return true
	}

	return false
}

// SetProviders gets a reference to the given []string and assigns it to the Providers field.
func (o *TypesPredicates) SetProviders(v []string) {
	o.Providers = v
}

// GetRegions returns the Regions field value if set, zero value otherwise.
func (o *TypesPredicates) GetRegions() []string {
	if o == nil || IsNil(o.Regions) {
		var ret []string
		return ret
	}
	return o.Regions
}

// GetRegionsOk returns a tuple with the Regions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TypesPredicates) GetRegionsOk() ([]string, bool) {
	if o == nil || IsNil(o.Regions) {
		return nil, false
	}
	return o.Regions, true
}

// HasRegions returns a boolean if a field has been set.
func (o *TypesPredicates) HasRegions() bool {
	if o != nil && !IsNil(o.Regions) {
		return true
	}

	return false
}

// SetRegions gets a reference to the given []string and assigns it to the Regions field.
func (o *TypesPredicates) SetRegions(v []string) {
	o.Regions = v
}

// GetServices returns the Services field value if set, zero value otherwise.
func (o *TypesPredicates) GetServices() []string {
	if o == nil || IsNil(o.Services) {
		var ret []string
		return ret
	}
	return o.Services
}

// GetServicesOk returns a tuple with the Services field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TypesPredicates) GetServicesOk() ([]string, bool) {
	if o == nil || IsNil(o.Services) {
		return nil, false
	}
	return o.Services, true
}

// HasServices returns a boolean if a field has been set.
func (o *TypesPredicates) HasServices() bool {
	if o != nil && !IsNil(o.Services) {
		return true
	}

	return false
}

// SetServices gets a reference to the given []string and assigns it to the Services field.
func (o *TypesPredicates) SetServices(v []string) {
	o.Services = v
}

// GetUsageTypes returns the UsageTypes field value if set, zero value otherwise.
func (o *TypesPredicates) GetUsageTypes() []string {
	if o == nil || IsNil(o.UsageTypes) {
		var ret []string
		return ret
	}
	return o.UsageTypes
}

// GetUsageTypesOk returns a tuple with the UsageTypes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TypesPredicates) GetUsageTypesOk() ([]string, bool) {
	if o == nil || IsNil(o.UsageTypes) {
		return nil, false
	}
	return o.UsageTypes, true
}

// HasUsageTypes returns a boolean if a field has been set.
func (o *TypesPredicates) HasUsageTypes() bool {
	if o != nil && !IsNil(o.UsageTypes) {
		return true
	}

	return false
}

// SetUsageTypes gets a reference to the given []string and assigns it to the UsageTypes field.
func (o *TypesPredicates) SetUsageTypes(v []string) {
	o.UsageTypes = v
}

func (o TypesPredicates) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TypesPredicates) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AvailabilityZones) {
		toSerialize["availability_zones"] = o.AvailabilityZones
	}
	if !IsNil(o.DiskTypes) {
		toSerialize["disk_types"] = o.DiskTypes
	}
	if !IsNil(o.InstanceTypes) {
		toSerialize["instance_types"] = o.InstanceTypes
	}
	if !IsNil(o.OperatingSystems) {
		toSerialize["operating_systems"] = o.OperatingSystems
	}
	if !IsNil(o.Providers) {
		toSerialize["providers"] = o.Providers
	}
	if !IsNil(o.Regions) {
		toSerialize["regions"] = o.Regions
	}
	if !IsNil(o.Services) {
		toSerialize["services"] = o.Services
	}
	if !IsNil(o.UsageTypes) {
		toSerialize["usage_types"] = o.UsageTypes
	}
	return toSerialize, nil
}

type NullableTypesPredicates struct {
	value *TypesPredicates
	isSet bool
}

func (v NullableTypesPredicates) Get() *TypesPredicates {
	return v.value
}

func (v *NullableTypesPredicates) Set(val *TypesPredicates) {
	v.value = val
	v.isSet = true
}

func (v NullableTypesPredicates) IsSet() bool {
	return v.isSet
}

func (v *NullableTypesPredicates) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTypesPredicates(val *TypesPredicates) *NullableTypesPredicates {
	return &NullableTypesPredicates{value: val, isSet: true}
}

func (v NullableTypesPredicates) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTypesPredicates) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


