/*
Pricing API

Provides API level access to the Costgraph Services.

API version: 1.0
Contact: contact@baselinehq.cloud
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pricing_api_client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TypesCustomPriceRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TypesCustomPriceRequest{}

// TypesCustomPriceRequest struct for TypesCustomPriceRequest
type TypesCustomPriceRequest struct {
	Entries []SchemaComputePricingsRow `json:"entries"`
}

type _TypesCustomPriceRequest TypesCustomPriceRequest

// NewTypesCustomPriceRequest instantiates a new TypesCustomPriceRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTypesCustomPriceRequest(entries []SchemaComputePricingsRow) *TypesCustomPriceRequest {
	this := TypesCustomPriceRequest{}
	this.Entries = entries
	return &this
}

// NewTypesCustomPriceRequestWithDefaults instantiates a new TypesCustomPriceRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTypesCustomPriceRequestWithDefaults() *TypesCustomPriceRequest {
	this := TypesCustomPriceRequest{}
	return &this
}

// GetEntries returns the Entries field value
func (o *TypesCustomPriceRequest) GetEntries() []SchemaComputePricingsRow {
	if o == nil {
		var ret []SchemaComputePricingsRow
		return ret
	}

	return o.Entries
}

// GetEntriesOk returns a tuple with the Entries field value
// and a boolean to check if the value has been set.
func (o *TypesCustomPriceRequest) GetEntriesOk() ([]SchemaComputePricingsRow, bool) {
	if o == nil {
		return nil, false
	}
	return o.Entries, true
}

// SetEntries sets field value
func (o *TypesCustomPriceRequest) SetEntries(v []SchemaComputePricingsRow) {
	o.Entries = v
}

func (o TypesCustomPriceRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TypesCustomPriceRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["entries"] = o.Entries
	return toSerialize, nil
}

func (o *TypesCustomPriceRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"entries",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTypesCustomPriceRequest := _TypesCustomPriceRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTypesCustomPriceRequest)

	if err != nil {
		return err
	}

	*o = TypesCustomPriceRequest(varTypesCustomPriceRequest)

	return err
}

type NullableTypesCustomPriceRequest struct {
	value *TypesCustomPriceRequest
	isSet bool
}

func (v NullableTypesCustomPriceRequest) Get() *TypesCustomPriceRequest {
	return v.value
}

func (v *NullableTypesCustomPriceRequest) Set(val *TypesCustomPriceRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableTypesCustomPriceRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableTypesCustomPriceRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTypesCustomPriceRequest(val *TypesCustomPriceRequest) *NullableTypesCustomPriceRequest {
	return &NullableTypesCustomPriceRequest{value: val, isSet: true}
}

func (v NullableTypesCustomPriceRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTypesCustomPriceRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


