/*
Pricing API

Provides API level access to the Costgraph Services.

API version: 1.0
Contact: support@costgraph.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pricing_api_client

import (
	"encoding/json"
)

// checks if the RegisteredDiskPrices type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RegisteredDiskPrices{}

// RegisteredDiskPrices struct for RegisteredDiskPrices
type RegisteredDiskPrices struct {
	Entries []DiskPrice         `json:"entries,omitempty"`
	Status  *RegistrationStatus `json:"status,omitempty"`
}

// NewRegisteredDiskPrices instantiates a new RegisteredDiskPrices object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRegisteredDiskPrices() *RegisteredDiskPrices {
	this := RegisteredDiskPrices{}
	return &this
}

// NewRegisteredDiskPricesWithDefaults instantiates a new RegisteredDiskPrices object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRegisteredDiskPricesWithDefaults() *RegisteredDiskPrices {
	this := RegisteredDiskPrices{}
	return &this
}

// GetEntries returns the Entries field value if set, zero value otherwise.
func (o *RegisteredDiskPrices) GetEntries() []DiskPrice {
	if o == nil || IsNil(o.Entries) {
		var ret []DiskPrice
		return ret
	}
	return o.Entries
}

// GetEntriesOk returns a tuple with the Entries field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegisteredDiskPrices) GetEntriesOk() ([]DiskPrice, bool) {
	if o == nil || IsNil(o.Entries) {
		return nil, false
	}
	return o.Entries, true
}

// HasEntries returns a boolean if a field has been set.
func (o *RegisteredDiskPrices) HasEntries() bool {
	if o != nil && !IsNil(o.Entries) {
		return true
	}

	return false
}

// SetEntries gets a reference to the given []DiskPrice and assigns it to the Entries field.
func (o *RegisteredDiskPrices) SetEntries(v []DiskPrice) {
	o.Entries = v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *RegisteredDiskPrices) GetStatus() RegistrationStatus {
	if o == nil || IsNil(o.Status) {
		var ret RegistrationStatus
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegisteredDiskPrices) GetStatusOk() (*RegistrationStatus, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *RegisteredDiskPrices) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given RegistrationStatus and assigns it to the Status field.
func (o *RegisteredDiskPrices) SetStatus(v RegistrationStatus) {
	o.Status = &v
}

func (o RegisteredDiskPrices) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RegisteredDiskPrices) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Entries) {
		toSerialize["entries"] = o.Entries
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableRegisteredDiskPrices struct {
	value *RegisteredDiskPrices
	isSet bool
}

func (v NullableRegisteredDiskPrices) Get() *RegisteredDiskPrices {
	return v.value
}

func (v *NullableRegisteredDiskPrices) Set(val *RegisteredDiskPrices) {
	v.value = val
	v.isSet = true
}

func (v NullableRegisteredDiskPrices) IsSet() bool {
	return v.isSet
}

func (v *NullableRegisteredDiskPrices) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRegisteredDiskPrices(val *RegisteredDiskPrices) *NullableRegisteredDiskPrices {
	return &NullableRegisteredDiskPrices{value: val, isSet: true}
}

func (v NullableRegisteredDiskPrices) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRegisteredDiskPrices) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
