/*
Pricing API

Provides API level access to the Costgraph Services.

API version: 1.0
Contact: contact@baselinehq.cloud
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pricing_api_client

import (
	"encoding/json"
)

// checks if the TypesMarketplaceProvidersResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TypesMarketplaceProvidersResponse{}

// TypesMarketplaceProvidersResponse struct for TypesMarketplaceProvidersResponse
type TypesMarketplaceProvidersResponse struct {
	Providers []SchemaComputePricingsRow `json:"providers,omitempty"`
}

// NewTypesMarketplaceProvidersResponse instantiates a new TypesMarketplaceProvidersResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTypesMarketplaceProvidersResponse() *TypesMarketplaceProvidersResponse {
	this := TypesMarketplaceProvidersResponse{}
	return &this
}

// NewTypesMarketplaceProvidersResponseWithDefaults instantiates a new TypesMarketplaceProvidersResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTypesMarketplaceProvidersResponseWithDefaults() *TypesMarketplaceProvidersResponse {
	this := TypesMarketplaceProvidersResponse{}
	return &this
}

// GetProviders returns the Providers field value if set, zero value otherwise.
func (o *TypesMarketplaceProvidersResponse) GetProviders() []SchemaComputePricingsRow {
	if o == nil || IsNil(o.Providers) {
		var ret []SchemaComputePricingsRow
		return ret
	}
	return o.Providers
}

// GetProvidersOk returns a tuple with the Providers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TypesMarketplaceProvidersResponse) GetProvidersOk() ([]SchemaComputePricingsRow, bool) {
	if o == nil || IsNil(o.Providers) {
		return nil, false
	}
	return o.Providers, true
}

// HasProviders returns a boolean if a field has been set.
func (o *TypesMarketplaceProvidersResponse) HasProviders() bool {
	if o != nil && !IsNil(o.Providers) {
		return true
	}

	return false
}

// SetProviders gets a reference to the given []SchemaComputePricingsRow and assigns it to the Providers field.
func (o *TypesMarketplaceProvidersResponse) SetProviders(v []SchemaComputePricingsRow) {
	o.Providers = v
}

func (o TypesMarketplaceProvidersResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TypesMarketplaceProvidersResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Providers) {
		toSerialize["providers"] = o.Providers
	}
	return toSerialize, nil
}

type NullableTypesMarketplaceProvidersResponse struct {
	value *TypesMarketplaceProvidersResponse
	isSet bool
}

func (v NullableTypesMarketplaceProvidersResponse) Get() *TypesMarketplaceProvidersResponse {
	return v.value
}

func (v *NullableTypesMarketplaceProvidersResponse) Set(val *TypesMarketplaceProvidersResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableTypesMarketplaceProvidersResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableTypesMarketplaceProvidersResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTypesMarketplaceProvidersResponse(val *TypesMarketplaceProvidersResponse) *NullableTypesMarketplaceProvidersResponse {
	return &NullableTypesMarketplaceProvidersResponse{value: val, isSet: true}
}

func (v NullableTypesMarketplaceProvidersResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTypesMarketplaceProvidersResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


