/*
Pricing API

Provides API level access to the Costgraph Services.

API version: 1.0
Contact: support@costgraph.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pricing_api_client

import (
	"encoding/json"
)

// checks if the ComputePrice type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ComputePrice{}

// ComputePrice struct for ComputePrice
type ComputePrice struct {
	Architecture        *string                `json:"architecture,omitempty"`
	AvailabilityZone    *string                `json:"availability_zone,omitempty"`
	CostPerHour         *float32               `json:"cost_per_hour,omitempty"`
	CpuCores            *float32               `json:"cpu_cores,omitempty"`
	CpuCoresCostPerHour *float32               `json:"cpu_cores_cost_per_hour,omitempty"`
	CreatedAt           *string                `json:"created_at,omitempty"`
	Currency            *string                `json:"currency,omitempty"`
	GpuCostPerHour      *float32               `json:"gpu_cost_per_hour,omitempty"`
	GpuCount            *float32               `json:"gpu_count,omitempty"`
	GpuType             *string                `json:"gpu_type,omitempty"`
	Id                  *string                `json:"id,omitempty"`
	InstanceType        *string                `json:"instance_type,omitempty"`
	NativeCostPerHour   *float32               `json:"native_cost_per_hour,omitempty"`
	OperatingSystem     *string                `json:"operating_system,omitempty"`
	PeriodBillingHours  *float32               `json:"period_billing_hours,omitempty"`
	Provider            *string                `json:"provider,omitempty"`
	RamGb               *float32               `json:"ram_gb,omitempty"`
	RamGbCostPerHour    *float32               `json:"ram_gb_cost_per_hour,omitempty"`
	RawPricingData      map[string]interface{} `json:"raw_pricing_data,omitempty"`
	Region              *string                `json:"region,omitempty"`
	Service             *string                `json:"service,omitempty"`
	Tags                map[string]interface{} `json:"tags,omitempty"`
	UpdatedAt           *string                `json:"updated_at,omitempty"`
	UsageType           *string                `json:"usage_type,omitempty"`
}

// NewComputePrice instantiates a new ComputePrice object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComputePrice() *ComputePrice {
	this := ComputePrice{}
	return &this
}

// NewComputePriceWithDefaults instantiates a new ComputePrice object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComputePriceWithDefaults() *ComputePrice {
	this := ComputePrice{}
	return &this
}

// GetArchitecture returns the Architecture field value if set, zero value otherwise.
func (o *ComputePrice) GetArchitecture() string {
	if o == nil || IsNil(o.Architecture) {
		var ret string
		return ret
	}
	return *o.Architecture
}

// GetArchitectureOk returns a tuple with the Architecture field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComputePrice) GetArchitectureOk() (*string, bool) {
	if o == nil || IsNil(o.Architecture) {
		return nil, false
	}
	return o.Architecture, true
}

// HasArchitecture returns a boolean if a field has been set.
func (o *ComputePrice) HasArchitecture() bool {
	if o != nil && !IsNil(o.Architecture) {
		return true
	}

	return false
}

// SetArchitecture gets a reference to the given string and assigns it to the Architecture field.
func (o *ComputePrice) SetArchitecture(v string) {
	o.Architecture = &v
}

// GetAvailabilityZone returns the AvailabilityZone field value if set, zero value otherwise.
func (o *ComputePrice) GetAvailabilityZone() string {
	if o == nil || IsNil(o.AvailabilityZone) {
		var ret string
		return ret
	}
	return *o.AvailabilityZone
}

// GetAvailabilityZoneOk returns a tuple with the AvailabilityZone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComputePrice) GetAvailabilityZoneOk() (*string, bool) {
	if o == nil || IsNil(o.AvailabilityZone) {
		return nil, false
	}
	return o.AvailabilityZone, true
}

// HasAvailabilityZone returns a boolean if a field has been set.
func (o *ComputePrice) HasAvailabilityZone() bool {
	if o != nil && !IsNil(o.AvailabilityZone) {
		return true
	}

	return false
}

// SetAvailabilityZone gets a reference to the given string and assigns it to the AvailabilityZone field.
func (o *ComputePrice) SetAvailabilityZone(v string) {
	o.AvailabilityZone = &v
}

// GetCostPerHour returns the CostPerHour field value if set, zero value otherwise.
func (o *ComputePrice) GetCostPerHour() float32 {
	if o == nil || IsNil(o.CostPerHour) {
		var ret float32
		return ret
	}
	return *o.CostPerHour
}

// GetCostPerHourOk returns a tuple with the CostPerHour field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComputePrice) GetCostPerHourOk() (*float32, bool) {
	if o == nil || IsNil(o.CostPerHour) {
		return nil, false
	}
	return o.CostPerHour, true
}

// HasCostPerHour returns a boolean if a field has been set.
func (o *ComputePrice) HasCostPerHour() bool {
	if o != nil && !IsNil(o.CostPerHour) {
		return true
	}

	return false
}

// SetCostPerHour gets a reference to the given float32 and assigns it to the CostPerHour field.
func (o *ComputePrice) SetCostPerHour(v float32) {
	o.CostPerHour = &v
}

// GetCpuCores returns the CpuCores field value if set, zero value otherwise.
func (o *ComputePrice) GetCpuCores() float32 {
	if o == nil || IsNil(o.CpuCores) {
		var ret float32
		return ret
	}
	return *o.CpuCores
}

// GetCpuCoresOk returns a tuple with the CpuCores field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComputePrice) GetCpuCoresOk() (*float32, bool) {
	if o == nil || IsNil(o.CpuCores) {
		return nil, false
	}
	return o.CpuCores, true
}

// HasCpuCores returns a boolean if a field has been set.
func (o *ComputePrice) HasCpuCores() bool {
	if o != nil && !IsNil(o.CpuCores) {
		return true
	}

	return false
}

// SetCpuCores gets a reference to the given float32 and assigns it to the CpuCores field.
func (o *ComputePrice) SetCpuCores(v float32) {
	o.CpuCores = &v
}

// GetCpuCoresCostPerHour returns the CpuCoresCostPerHour field value if set, zero value otherwise.
func (o *ComputePrice) GetCpuCoresCostPerHour() float32 {
	if o == nil || IsNil(o.CpuCoresCostPerHour) {
		var ret float32
		return ret
	}
	return *o.CpuCoresCostPerHour
}

// GetCpuCoresCostPerHourOk returns a tuple with the CpuCoresCostPerHour field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComputePrice) GetCpuCoresCostPerHourOk() (*float32, bool) {
	if o == nil || IsNil(o.CpuCoresCostPerHour) {
		return nil, false
	}
	return o.CpuCoresCostPerHour, true
}

// HasCpuCoresCostPerHour returns a boolean if a field has been set.
func (o *ComputePrice) HasCpuCoresCostPerHour() bool {
	if o != nil && !IsNil(o.CpuCoresCostPerHour) {
		return true
	}

	return false
}

// SetCpuCoresCostPerHour gets a reference to the given float32 and assigns it to the CpuCoresCostPerHour field.
func (o *ComputePrice) SetCpuCoresCostPerHour(v float32) {
	o.CpuCoresCostPerHour = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *ComputePrice) GetCreatedAt() string {
	if o == nil || IsNil(o.CreatedAt) {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComputePrice) GetCreatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *ComputePrice) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *ComputePrice) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *ComputePrice) GetCurrency() string {
	if o == nil || IsNil(o.Currency) {
		var ret string
		return ret
	}
	return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComputePrice) GetCurrencyOk() (*string, bool) {
	if o == nil || IsNil(o.Currency) {
		return nil, false
	}
	return o.Currency, true
}

// HasCurrency returns a boolean if a field has been set.
func (o *ComputePrice) HasCurrency() bool {
	if o != nil && !IsNil(o.Currency) {
		return true
	}

	return false
}

// SetCurrency gets a reference to the given string and assigns it to the Currency field.
func (o *ComputePrice) SetCurrency(v string) {
	o.Currency = &v
}

// GetGpuCostPerHour returns the GpuCostPerHour field value if set, zero value otherwise.
func (o *ComputePrice) GetGpuCostPerHour() float32 {
	if o == nil || IsNil(o.GpuCostPerHour) {
		var ret float32
		return ret
	}
	return *o.GpuCostPerHour
}

// GetGpuCostPerHourOk returns a tuple with the GpuCostPerHour field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComputePrice) GetGpuCostPerHourOk() (*float32, bool) {
	if o == nil || IsNil(o.GpuCostPerHour) {
		return nil, false
	}
	return o.GpuCostPerHour, true
}

// HasGpuCostPerHour returns a boolean if a field has been set.
func (o *ComputePrice) HasGpuCostPerHour() bool {
	if o != nil && !IsNil(o.GpuCostPerHour) {
		return true
	}

	return false
}

// SetGpuCostPerHour gets a reference to the given float32 and assigns it to the GpuCostPerHour field.
func (o *ComputePrice) SetGpuCostPerHour(v float32) {
	o.GpuCostPerHour = &v
}

// GetGpuCount returns the GpuCount field value if set, zero value otherwise.
func (o *ComputePrice) GetGpuCount() float32 {
	if o == nil || IsNil(o.GpuCount) {
		var ret float32
		return ret
	}
	return *o.GpuCount
}

// GetGpuCountOk returns a tuple with the GpuCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComputePrice) GetGpuCountOk() (*float32, bool) {
	if o == nil || IsNil(o.GpuCount) {
		return nil, false
	}
	return o.GpuCount, true
}

// HasGpuCount returns a boolean if a field has been set.
func (o *ComputePrice) HasGpuCount() bool {
	if o != nil && !IsNil(o.GpuCount) {
		return true
	}

	return false
}

// SetGpuCount gets a reference to the given float32 and assigns it to the GpuCount field.
func (o *ComputePrice) SetGpuCount(v float32) {
	o.GpuCount = &v
}

// GetGpuType returns the GpuType field value if set, zero value otherwise.
func (o *ComputePrice) GetGpuType() string {
	if o == nil || IsNil(o.GpuType) {
		var ret string
		return ret
	}
	return *o.GpuType
}

// GetGpuTypeOk returns a tuple with the GpuType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComputePrice) GetGpuTypeOk() (*string, bool) {
	if o == nil || IsNil(o.GpuType) {
		return nil, false
	}
	return o.GpuType, true
}

// HasGpuType returns a boolean if a field has been set.
func (o *ComputePrice) HasGpuType() bool {
	if o != nil && !IsNil(o.GpuType) {
		return true
	}

	return false
}

// SetGpuType gets a reference to the given string and assigns it to the GpuType field.
func (o *ComputePrice) SetGpuType(v string) {
	o.GpuType = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ComputePrice) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComputePrice) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ComputePrice) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ComputePrice) SetId(v string) {
	o.Id = &v
}

// GetInstanceType returns the InstanceType field value if set, zero value otherwise.
func (o *ComputePrice) GetInstanceType() string {
	if o == nil || IsNil(o.InstanceType) {
		var ret string
		return ret
	}
	return *o.InstanceType
}

// GetInstanceTypeOk returns a tuple with the InstanceType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComputePrice) GetInstanceTypeOk() (*string, bool) {
	if o == nil || IsNil(o.InstanceType) {
		return nil, false
	}
	return o.InstanceType, true
}

// HasInstanceType returns a boolean if a field has been set.
func (o *ComputePrice) HasInstanceType() bool {
	if o != nil && !IsNil(o.InstanceType) {
		return true
	}

	return false
}

// SetInstanceType gets a reference to the given string and assigns it to the InstanceType field.
func (o *ComputePrice) SetInstanceType(v string) {
	o.InstanceType = &v
}

// GetNativeCostPerHour returns the NativeCostPerHour field value if set, zero value otherwise.
func (o *ComputePrice) GetNativeCostPerHour() float32 {
	if o == nil || IsNil(o.NativeCostPerHour) {
		var ret float32
		return ret
	}
	return *o.NativeCostPerHour
}

// GetNativeCostPerHourOk returns a tuple with the NativeCostPerHour field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComputePrice) GetNativeCostPerHourOk() (*float32, bool) {
	if o == nil || IsNil(o.NativeCostPerHour) {
		return nil, false
	}
	return o.NativeCostPerHour, true
}

// HasNativeCostPerHour returns a boolean if a field has been set.
func (o *ComputePrice) HasNativeCostPerHour() bool {
	if o != nil && !IsNil(o.NativeCostPerHour) {
		return true
	}

	return false
}

// SetNativeCostPerHour gets a reference to the given float32 and assigns it to the NativeCostPerHour field.
func (o *ComputePrice) SetNativeCostPerHour(v float32) {
	o.NativeCostPerHour = &v
}

// GetOperatingSystem returns the OperatingSystem field value if set, zero value otherwise.
func (o *ComputePrice) GetOperatingSystem() string {
	if o == nil || IsNil(o.OperatingSystem) {
		var ret string
		return ret
	}
	return *o.OperatingSystem
}

// GetOperatingSystemOk returns a tuple with the OperatingSystem field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComputePrice) GetOperatingSystemOk() (*string, bool) {
	if o == nil || IsNil(o.OperatingSystem) {
		return nil, false
	}
	return o.OperatingSystem, true
}

// HasOperatingSystem returns a boolean if a field has been set.
func (o *ComputePrice) HasOperatingSystem() bool {
	if o != nil && !IsNil(o.OperatingSystem) {
		return true
	}

	return false
}

// SetOperatingSystem gets a reference to the given string and assigns it to the OperatingSystem field.
func (o *ComputePrice) SetOperatingSystem(v string) {
	o.OperatingSystem = &v
}

// GetPeriodBillingHours returns the PeriodBillingHours field value if set, zero value otherwise.
func (o *ComputePrice) GetPeriodBillingHours() float32 {
	if o == nil || IsNil(o.PeriodBillingHours) {
		var ret float32
		return ret
	}
	return *o.PeriodBillingHours
}

// GetPeriodBillingHoursOk returns a tuple with the PeriodBillingHours field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComputePrice) GetPeriodBillingHoursOk() (*float32, bool) {
	if o == nil || IsNil(o.PeriodBillingHours) {
		return nil, false
	}
	return o.PeriodBillingHours, true
}

// HasPeriodBillingHours returns a boolean if a field has been set.
func (o *ComputePrice) HasPeriodBillingHours() bool {
	if o != nil && !IsNil(o.PeriodBillingHours) {
		return true
	}

	return false
}

// SetPeriodBillingHours gets a reference to the given float32 and assigns it to the PeriodBillingHours field.
func (o *ComputePrice) SetPeriodBillingHours(v float32) {
	o.PeriodBillingHours = &v
}

// GetProvider returns the Provider field value if set, zero value otherwise.
func (o *ComputePrice) GetProvider() string {
	if o == nil || IsNil(o.Provider) {
		var ret string
		return ret
	}
	return *o.Provider
}

// GetProviderOk returns a tuple with the Provider field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComputePrice) GetProviderOk() (*string, bool) {
	if o == nil || IsNil(o.Provider) {
		return nil, false
	}
	return o.Provider, true
}

// HasProvider returns a boolean if a field has been set.
func (o *ComputePrice) HasProvider() bool {
	if o != nil && !IsNil(o.Provider) {
		return true
	}

	return false
}

// SetProvider gets a reference to the given string and assigns it to the Provider field.
func (o *ComputePrice) SetProvider(v string) {
	o.Provider = &v
}

// GetRamGb returns the RamGb field value if set, zero value otherwise.
func (o *ComputePrice) GetRamGb() float32 {
	if o == nil || IsNil(o.RamGb) {
		var ret float32
		return ret
	}
	return *o.RamGb
}

// GetRamGbOk returns a tuple with the RamGb field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComputePrice) GetRamGbOk() (*float32, bool) {
	if o == nil || IsNil(o.RamGb) {
		return nil, false
	}
	return o.RamGb, true
}

// HasRamGb returns a boolean if a field has been set.
func (o *ComputePrice) HasRamGb() bool {
	if o != nil && !IsNil(o.RamGb) {
		return true
	}

	return false
}

// SetRamGb gets a reference to the given float32 and assigns it to the RamGb field.
func (o *ComputePrice) SetRamGb(v float32) {
	o.RamGb = &v
}

// GetRamGbCostPerHour returns the RamGbCostPerHour field value if set, zero value otherwise.
func (o *ComputePrice) GetRamGbCostPerHour() float32 {
	if o == nil || IsNil(o.RamGbCostPerHour) {
		var ret float32
		return ret
	}
	return *o.RamGbCostPerHour
}

// GetRamGbCostPerHourOk returns a tuple with the RamGbCostPerHour field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComputePrice) GetRamGbCostPerHourOk() (*float32, bool) {
	if o == nil || IsNil(o.RamGbCostPerHour) {
		return nil, false
	}
	return o.RamGbCostPerHour, true
}

// HasRamGbCostPerHour returns a boolean if a field has been set.
func (o *ComputePrice) HasRamGbCostPerHour() bool {
	if o != nil && !IsNil(o.RamGbCostPerHour) {
		return true
	}

	return false
}

// SetRamGbCostPerHour gets a reference to the given float32 and assigns it to the RamGbCostPerHour field.
func (o *ComputePrice) SetRamGbCostPerHour(v float32) {
	o.RamGbCostPerHour = &v
}

// GetRawPricingData returns the RawPricingData field value if set, zero value otherwise.
func (o *ComputePrice) GetRawPricingData() map[string]interface{} {
	if o == nil || IsNil(o.RawPricingData) {
		var ret map[string]interface{}
		return ret
	}
	return o.RawPricingData
}

// GetRawPricingDataOk returns a tuple with the RawPricingData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComputePrice) GetRawPricingDataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.RawPricingData) {
		return map[string]interface{}{}, false
	}
	return o.RawPricingData, true
}

// HasRawPricingData returns a boolean if a field has been set.
func (o *ComputePrice) HasRawPricingData() bool {
	if o != nil && !IsNil(o.RawPricingData) {
		return true
	}

	return false
}

// SetRawPricingData gets a reference to the given map[string]interface{} and assigns it to the RawPricingData field.
func (o *ComputePrice) SetRawPricingData(v map[string]interface{}) {
	o.RawPricingData = v
}

// GetRegion returns the Region field value if set, zero value otherwise.
func (o *ComputePrice) GetRegion() string {
	if o == nil || IsNil(o.Region) {
		var ret string
		return ret
	}
	return *o.Region
}

// GetRegionOk returns a tuple with the Region field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComputePrice) GetRegionOk() (*string, bool) {
	if o == nil || IsNil(o.Region) {
		return nil, false
	}
	return o.Region, true
}

// HasRegion returns a boolean if a field has been set.
func (o *ComputePrice) HasRegion() bool {
	if o != nil && !IsNil(o.Region) {
		return true
	}

	return false
}

// SetRegion gets a reference to the given string and assigns it to the Region field.
func (o *ComputePrice) SetRegion(v string) {
	o.Region = &v
}

// GetService returns the Service field value if set, zero value otherwise.
func (o *ComputePrice) GetService() string {
	if o == nil || IsNil(o.Service) {
		var ret string
		return ret
	}
	return *o.Service
}

// GetServiceOk returns a tuple with the Service field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComputePrice) GetServiceOk() (*string, bool) {
	if o == nil || IsNil(o.Service) {
		return nil, false
	}
	return o.Service, true
}

// HasService returns a boolean if a field has been set.
func (o *ComputePrice) HasService() bool {
	if o != nil && !IsNil(o.Service) {
		return true
	}

	return false
}

// SetService gets a reference to the given string and assigns it to the Service field.
func (o *ComputePrice) SetService(v string) {
	o.Service = &v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *ComputePrice) GetTags() map[string]interface{} {
	if o == nil || IsNil(o.Tags) {
		var ret map[string]interface{}
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComputePrice) GetTagsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Tags) {
		return map[string]interface{}{}, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *ComputePrice) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given map[string]interface{} and assigns it to the Tags field.
func (o *ComputePrice) SetTags(v map[string]interface{}) {
	o.Tags = v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *ComputePrice) GetUpdatedAt() string {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret string
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComputePrice) GetUpdatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *ComputePrice) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given string and assigns it to the UpdatedAt field.
func (o *ComputePrice) SetUpdatedAt(v string) {
	o.UpdatedAt = &v
}

// GetUsageType returns the UsageType field value if set, zero value otherwise.
func (o *ComputePrice) GetUsageType() string {
	if o == nil || IsNil(o.UsageType) {
		var ret string
		return ret
	}
	return *o.UsageType
}

// GetUsageTypeOk returns a tuple with the UsageType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComputePrice) GetUsageTypeOk() (*string, bool) {
	if o == nil || IsNil(o.UsageType) {
		return nil, false
	}
	return o.UsageType, true
}

// HasUsageType returns a boolean if a field has been set.
func (o *ComputePrice) HasUsageType() bool {
	if o != nil && !IsNil(o.UsageType) {
		return true
	}

	return false
}

// SetUsageType gets a reference to the given string and assigns it to the UsageType field.
func (o *ComputePrice) SetUsageType(v string) {
	o.UsageType = &v
}

func (o ComputePrice) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ComputePrice) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Architecture) {
		toSerialize["architecture"] = o.Architecture
	}
	if !IsNil(o.AvailabilityZone) {
		toSerialize["availability_zone"] = o.AvailabilityZone
	}
	if !IsNil(o.CostPerHour) {
		toSerialize["cost_per_hour"] = o.CostPerHour
	}
	if !IsNil(o.CpuCores) {
		toSerialize["cpu_cores"] = o.CpuCores
	}
	if !IsNil(o.CpuCoresCostPerHour) {
		toSerialize["cpu_cores_cost_per_hour"] = o.CpuCoresCostPerHour
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.Currency) {
		toSerialize["currency"] = o.Currency
	}
	if !IsNil(o.GpuCostPerHour) {
		toSerialize["gpu_cost_per_hour"] = o.GpuCostPerHour
	}
	if !IsNil(o.GpuCount) {
		toSerialize["gpu_count"] = o.GpuCount
	}
	if !IsNil(o.GpuType) {
		toSerialize["gpu_type"] = o.GpuType
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.InstanceType) {
		toSerialize["instance_type"] = o.InstanceType
	}
	if !IsNil(o.NativeCostPerHour) {
		toSerialize["native_cost_per_hour"] = o.NativeCostPerHour
	}
	if !IsNil(o.OperatingSystem) {
		toSerialize["operating_system"] = o.OperatingSystem
	}
	if !IsNil(o.PeriodBillingHours) {
		toSerialize["period_billing_hours"] = o.PeriodBillingHours
	}
	if !IsNil(o.Provider) {
		toSerialize["provider"] = o.Provider
	}
	if !IsNil(o.RamGb) {
		toSerialize["ram_gb"] = o.RamGb
	}
	if !IsNil(o.RamGbCostPerHour) {
		toSerialize["ram_gb_cost_per_hour"] = o.RamGbCostPerHour
	}
	if !IsNil(o.RawPricingData) {
		toSerialize["raw_pricing_data"] = o.RawPricingData
	}
	if !IsNil(o.Region) {
		toSerialize["region"] = o.Region
	}
	if !IsNil(o.Service) {
		toSerialize["service"] = o.Service
	}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	if !IsNil(o.UsageType) {
		toSerialize["usage_type"] = o.UsageType
	}
	return toSerialize, nil
}

type NullableComputePrice struct {
	value *ComputePrice
	isSet bool
}

func (v NullableComputePrice) Get() *ComputePrice {
	return v.value
}

func (v *NullableComputePrice) Set(val *ComputePrice) {
	v.value = val
	v.isSet = true
}

func (v NullableComputePrice) IsSet() bool {
	return v.isSet
}

func (v *NullableComputePrice) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComputePrice(val *ComputePrice) *NullableComputePrice {
	return &NullableComputePrice{value: val, isSet: true}
}

func (v NullableComputePrice) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComputePrice) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
